### ISSUE TITLE
🚀 [Feature] Save names of Users for old Transactions even tho the user changed it

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1005]
## 🚀 Feature

Save names of Users for old Transactions even tho the user changed it.

Users can change their First+Lastname. This will immediately affect all transactions. This mechanic can be used to confuse the user or even commit fraud.

As solution we therefore propose to save the history of the usernames for a user with the timestamp where he changed it. This will allow us to figure out how the user was named back then.

Transactions could look like this:
`-500 sent to Peter Lustig (now known as "Petra Lustiger")`

The "now known as" will then always reference the current users name and could therefore change again.

**Comment by clauspeterhuebner** [comment]
This requirement is obsolet with the issue #2913 by adding the users firstname and lastname valid at the transactions creation timestamp. 
So it is always possible to see the original users name of transaction creation time even if the user change his name afterwards.
This issue can be closed.
