### ISSUE TITLE
🔧 [Refactor] Refactor Numbers of the Transaction List to always be aligned by the comma.

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1006]
## 🔧 Refactor ticket

Refactor Numbers of the Transaction List to always be aligned by the comma.

This is due to readability.

Currently:
```
+ 115.00
- 3.00
----
+ 112.00
```

Suggested:
```
+ 115.00
-   3.00
----
+ 112.00
```

**Comment by ogerly** [comment]
?  where exactly do you mean
