### ISSUE TITLE
💥 [DevOps] Visualize and refine the register process

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1011]
## 💥 DevOps ticket

We changed the register process to start at our end. A good start, but many things are still unclear especially with obligations regarding law when it comes to the newsletter and if everything is understandable for the user.

This ticket is to:
- Visualize the process
- Analyse the process using the Visualization
- Optimize the Process

User can login without confirming his EMail. He then can subscribe manually to the Newsletter without confirming the EMail.

**Comment by ulfgebhardt** [comment]
@clauspeterhuebner 

> 1. Do we support a state for an account to distingue between a new but not confirmed yet account during registration process?
We have a flag `email_checked` in the database. We can use this to control the process flow.

> 2. Is there an invokation of GDT-Server after confirmation of the new account to check and create for this user a GDT-account too?
GDT is a blackbox and its unclear how it works. Furthermore the login server has a table `login_elopage_buys` where it is unclear how its filled.
We need to figure out what webhook endpoints are available on our services and which webhooks land where. @einhornimmond 

> 3. At which time in the registration-process is klicktipp informed about the new email?
Klicktipp is registered when the user logs in and activates the newsletter - even without email confirmation.
Or when the user confirms his EMail. To have things setup correctly we need to make sure the user confirms his EMail **before** he can login. See #1088

> 4. Is there an invokation from GDT-Server to Apollo-Server after GDT-account-creation, which was started in Elopage with a payment-registration?
Not to the Apolloserver. Communication happens via the magical table `login_elopage_buys`

> 5. Can we distingue in GDT per Elopage-Webhooks if the elopage account was created by a payment-registration, by a deeplink from gradido or by a normal elopage-registration?
unknown, but the magical table `login_elopage_buys` contains detailed data like `event` and alike. Therefore chances are good.

**Comment by einhornimmond** [comment]
2. GDT an Login-Server a both listen on the Elopage Webhook-Call. The Login- and Community Server only talk with the GDT Server if they want to know how many GDT an user (email) has.
GDT create a GDT Entry for every transaction caming from elopage with more than 0 revenue or from form, csv import or digistore24 import with the user email as indentificator. For every unknown email a new entry in contacts will be created. The user hasn't exactly an account on the GDT Server which he can login on it. 
The Login-Server creates for every user which he gets from elopage which has one of the hardcoded product ids and haven't an account yet an account and send him an activation email. 
elopage_buys on login server will be filled from elopage webhook call as long as the event isn't a lesson. 
The details you can find in src/cpp/HTTPInterface/ElopageWebhook.cpp and h in login-server code.

5. I dont' know how a "normal" elopage registration or deeplink registration looks like on webhook side. Maybe it contain the same product ids like the registration by payment. This needs to be examined more closely.

**Comment by BerndHueckstaedt** [comment]
There is no "normal" Elopage registration. The registration is always associated with a product.

**Comment by Elweyn** [comment]
Now we have it like following:
Case 1 User register on the Wallet vue:
- User arrives on http://gdd1.gradido.net/vue/
- User has no account => Click on "register new account" => Enter the data => Submit. Now the User get's a validation link to activate his account.
- If the User tries to login without clicking the link in the activation email => Users get's redirected to a site where he is noticed that he need to activate his account with the link that he should have in his emails. 
- User clicks on the activation link => Asks to set a Password and activate the account if done successfully

Case 2 User register on the EloPage process: 
- User arrives on http://elopage-gradido-url/ => Creates an EloPage subscriber account
- Our wallet gets a hook that creates an account without Password!?
- User tries to login on wallet => Get's redirected to set password!?
For this szenario I don't really know how to test it for now!

Case of ForgotPassword we send a ResetPassword link to the Users email and he has 10 minutes to activate it, if the time has expired we send the user again to the resetpassword form with a message that the other code has expired.

**Comment by Elweyn** [comment]
@clauspeterhuebner, @ogerly and I looked at the registration graphic what looks nearly to what we have.
We can add that the Apollo server get the EloPage hooks.
And for the questions: 
- "Does GDT Server create an inactive account?", for know it is done by the login server, I did not analyse the apollo hook interpretations but they should take over this task.
- "GDD Account set to active link to GDT Account existens possible?" Yes if a User make a donation on EloPage we create an GDT Account and an "inactive" GDD Account. So when the User activate the GDD Account their is already a GDT Account.
- Question that was made: "We may want to give the User the possibility to send an activation link again in the error page 'Account not activate yet....'"
TODO:
- [ ] On error page "Your account has not been activated, please check your emails" Implement a button "Resend activation link"

**Comment by clauspeterhuebner** [comment]
rework details about checkEmail and Apollo-Elopage-Webhook processing
