### ISSUE TITLE
🚀 [Feature] Display "You have no Gradidos yet" when trying to send with 0 Balance

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1015]
## 🚀 Feature

Display "You have no Gradidos yet" when trying to send with 0 Balance.
here is the question wether we have to differentiate between a user with zero transactions or an user with a 0 balance.

Could the text be "You currently have no Gradidos to send" and correspondingly "Du hast zur Zeit keine Gradidos zum versenden"

```
ich versuche zu überweisen (habe noch keine Gradidos)

Meldung unter dem Betrag-Feld:
Das Feld Betrag muss eine Zahl zwischen 0,01 und 0,00 mit höchstens zwei Nachkommastellen sein

Muss heißen: 
Du hast noch keine Gradidos auf deinem Konto.
```

**Comment by BerndHueckstaedt** [comment]
"You currently have no Gradidos to send" and correspondingly "Du hast zur Zeit keine Gradidos zum versenden" sounds good.

**Comment by ulfgebhardt** [comment]
@Elweyn @ogerly is this fixed?

**Comment by ulfgebhardt** [comment]
@clauspeterhuebner I agree
