### ISSUE TITLE
🐛 [Bug] No decay is incorrect - its just less then 0.00

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1018]
## 🐛 Bugreport

No decay is incorrect - its just less then 0.00 and we should communicate this to the user.

![image](https://user-images.githubusercontent.com/1238238/137587771-d4c834bd-2a44-42ef-8339-75d2a7dff607.png)

```
“Keine Vergänglichkeit” ist falsch (die Vergänglichkeit ist lediglich kleiner als 1 Cent). 
Muss heißen: - 0,00
```

**Comment by ogerly** [comment]
we decided that together once. how can it be wrong if it was decided that way? i didn't think it up myself! 
it has now been decided differently and should now be called 0.00. 

What about the icon then? Shouldn't I rather write "Vergänglichkeit / Decay" there?
