### ISSUE TITLE
💬 [Question] What about gradido.com

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1030]
## 💬 Question

We have https://gradido.com/ where we can also pass a PID https://gradido.com/1234
What do we want to do with that?

**Comment by BerndHueckstaedt** [comment]
I think, we should have this for all communities as a part of each community server.

**Comment by Elweyn** [comment]
Oh yeah we have it on https://gradido.com/1234 but not on https://gdd1.gradido.com/1234 or https://gdd1.gradido.com/vue/1234
So their would be the following ToDo:
- [ ] Link https://gdd1.gradido.com/1234 or https://gdd1.gradido.com/vue/1234 to https://gdd1.gradido.com/vue/register/?pid=1234
