### ISSUE TITLE
🐛 [Doku] Fehler beim anlegen eines neuen Users in der Lokalen Umgebung

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1049]
## 🐛 Bugreport
Fehler beim anlegen eines neuen Users in der Lokalen Umgebung

Ich musste leider alles neu aufsetzen da ich docker neu aufgesetzt habe und alle meine daten verloren gegangen sind. 
es scheiterte schon beim anmelden eines neuen users. 

schritt 1 
ich habe auf das PR gewechselt https://github.com/gradido/gradido/pull/1046 
dann ging das anmelden. 

Datenbanken: 
1. unter user http://localhost:8074/index.php?route=/sql&server=1&db=gradido_login&table=users&pos=0 
ist der angemeldete user zu sehen 

2. unter http://localhost:8074/index.php?route=/sql&server=1&db=gradido_login&table=email_opt_in&pos=0  findest du die userid unter id und nimmst da den ***verification_code***

3. gib im browser http://localhost:3000/vue/checkEmail/***verification_code*** ein und du solltest einen hinweis bekommen das klicktip nicht funktioniert .. (Das ist zwar nicht sauber aber zeigt das die email geprüft wurde. Das ist der selbe link de rin der email an den User gesendet wird.) 

4. du kannst nochmal testen unter http://localhost:8074/index.php?route=/sql&server=1&db=gradido_login&table=users&pos=0  sollte hinter deinem user in der tabelle ***email_checked*** eine **1** stehen. 

 Du solltest dich jetzt anmelden können. 
 

Um lokal ohne Docker

Nginx einrichten auf dem Local
Mariadb installieren

Admin Rolle für User:
>  INSERT INTO `user_roles` (`id`, `user_id`, `role_id`) VALUES (NULL, '1', '1');

> Cake PHP authentication (Community_server): http://localhost/server-users/add Schöpfungsseiten Zugriff

http://localhost/transaction-creations/create-multi /!\ Keine Schöpfung für sich selbst/!\
Step 1 :
User 1 : 1000 GDD
> Transaktion unterschrieben: http://localhost/account/checkTransactions   
Pending_tasks tabelle in login server Für nicht acceptierte Transaktionen

http://localhost/transactions/add /!\ Decay Block /!\

**Comment by Elweyn** [comment]
@ogerly what is with this issue?

**Comment by ogerly** [comment]
since this is now changing due to the seeding of the database, I am closing this issue.
