### ISSUE TITLE
🐛 [Bug] Should 'Gradido-Akademie' in the copyright line really link to the login page?

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#105]
## :bug: Bugreport

Should 'Gradido-Akademie' in the copyright line really link to the login page?

**Comment by Mogge** [comment]
![image](https://user-images.githubusercontent.com/15882241/114563592-d55ee100-9c6f-11eb-929a-059c09f2f32f.png)

We agreed on removing Gradido in the foot line and replace the link of Gradido-Akademie to the one in Gradido.
