### ISSUE TITLE
Concept of Operations Requirements

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#1055]
Define and describe the following aspects:

* which Staging levels are needed? e.g. Local, DEV, INT, PROD
* define for each Stage the necessary resources like CPU, RAM, Storage, network, SLAs
* search and select "professionell" providers, which fulfills the requirements with acceptable conditions
* search and define the services and licensemodel of the selected providers
* which aspects will be kept in the responsibility of the gradido-team
* ...

**Comment by einhornimmond** [comment]
Currently we have DEV for local development on developers pc,
STAGING for testing before releasing and PRODUCTION. 
I think for the moment that's enough. 

Ressourcen: 
DEV: default developers pc, linux or windows 10 with docker, maybe mac is working also, but I don't know
STAGING: at least 4 GB Ram (if swap is allowd, else more)
PRODUCTION: the same as STAGING

**Comment by ulfgebhardt** [comment]
closing this since we have a working setup with several stages
