### ISSUE TITLE
💬 [Question] Max Mustermann has GDT on the live system

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1066]
## 💬 Question

According to our research `Max Mustermann` (dummy user) has a significant amount of GDT on the production-GDT-server.

- Is this true?
- Does it make sense?
- How could this happen?
- What do we have to do?

**Comment by einhornimmond** [comment]
I cannot find any GDT Entrie for Max Mustermann on production GDT, but on staging GDT, yes he has many gdts.
