### ISSUE TITLE
🐛 [Bug] Coin creation error email unify target_date DE locale & Add User link 

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#1074]
## 🐛 Bugreport
We got the message from support: "Ich bekomme Fehlermeldungen, obwohl korrekt geschöpft wurde (Altes Konto-Login)."
After @einhornimmond analyse it could be a missunderstanding of the german word usage "Zieldatum" instead of "Verrechnungsdatum" in the email, cause the coin creation has done what was intended.
Local Test: 
- Creation for October => Success
- 2nd Creation for October => Fail
- Creation for September => Success

## TODO
- [ ] Unify Locale DE target_date "Zieldatum" & "Verrechnungsdatum"
- [ ] Add user profil link to error email: "/state-users/view/$id"

**Comment by ulfgebhardt** [comment]
This is not an issue in the new admin anymore
