### ISSUE TITLE
🐛 [Bug] Creation works, but nevertheless a error message is sended

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#1076]
## 🐛 Bugreport
A Creation user Reports she gets a error message for creation transaction, but the creation transaction has worked. 
So maybe the transaction sending was triggered two times. And so the protection for this in login-server don't work properly.
Maybe it is a good idea to enhance the UI so the user sees direct if the other user has already get creation in the target month.
Maybe it has to do with pending tasks manager in login-server which in past resend transaction which couldn't send properly,
after restart.

**Comment by ulfgebhardt** [comment]
Not a known problem anymore
