### ISSUE TITLE
🐛 [Bug] Make sure user confirms EMail before login

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1088]
## 🐛 Bugreport

Make sure user confirms EMail before login. Currently the user can login without confirming his EMail and he is even advised to do so after register.

1. Register
2. "Hey we sent you an EMail - make sure to confirm it"-Page
3. Login
4. Redirect to "Hey you did not confirm your EMail yet - want a new Email?"-Page, not logged in
5. Click on Link in Email -> "Hey nice, lets go and login"
6. Login
7. Cool

**Comment by Elweyn** [comment]
## TODOs
- [ ] Login when not Activated > Redirect to "Hey you did not confirm your EMail yet - want a new Email?"-Page, not logged in
- [ ] Click on Link in Email -> "Hey nice, lets go and login"
