### ISSUE TITLE
🐛 [Bug] Existing passwords with space don't work any longer

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#1089]
## 🐛 Bugreport
In the past passwords with space where allowed, with the new password check code on frontend they are not longer allowed. 
In frontend/src/components/Inputs/InputPasswordConfirmation there is a rule noWhitespaceCharacter which prevent space in password. For new passwords we can make it this way (even if I not know why we has decided that) but at least old passwords should still work. 

My proposal would be to make parameter or so which this rule (noWhitespaceCharacter) can be switched on or off and don't use it on login, only for create user, reset password and password change.

**Comment by ulfgebhardt** [comment]
- Evaluate how this affects old passwords
- Consider a change of current behaviour

**Comment by einhornimmond** [comment]
>     * Evaluate how this affects old passwords

That's the point. Older passwords with space don't work any longer, we get the info from support that they have some requests because of that. Some User cannot login any longer and that I like to fix. As fast as possible.

**Comment by einhornimmond** [comment]
The check for password rules on login is only for performance reasons. 
With the Apollo Server we are leaving the path of performance anyway, so we probably don't need that anymore.

**Comment by Mogge** [comment]
I am sorry, but I cannot see a problem here. On the Login page we do not have any password validation in the frontend. So a user should be able to login with a password which does not follow our new rules. Please close this issue

**Comment by einhornimmond** [comment]
I have open this issue because of reports from support that some people not able to login any longer with her old passwords. 
Maybe the password check in new frontend has since been removed so there isn't any longer a problem.

**Comment by ulfgebhardt** [comment]
Trace Neues Frontend:
1. Apollo `login`: <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/backend/src/graphql/resolver/UserResolver.ts#L39>
2. Login Server `JsonUnsecureLogin::handle`: <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/JSONInterface/JsonUnsecureLogin.cpp#L89>
3. Login Server `SessionManager::checkPwdValidation`:  <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L601>
4. Login Server `SessionManager::isValid`  in Verbindung mit `SessionManager::init`: 
<https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L106>
<https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L49> 
Auf <https://regex101.com/> mit `^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9 \\t\\n\\r]).{8,}$` zu testen. Hier gibt es einen match auf  `peter lustig123ABC!`  aber nicht auf `peter lustig123ABC`
5. ...
6. Ruft nun `Session::loadUser` auf wie unten beschrieben. Der check wird dort nochmals wiederholt

Trace Altes Frontend:
1. Community Server `requestLogin`: <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/community_server/src/Controller/AppController.php#L195>
2. Login Server `PageRequestHandlerFactory::createRequestHandler` : <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/HTTPInterface/PageRequestHandlerFactory.cpp#L229>
3. Login Server `Login.cpsp`: <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpsp/Login.cpsp#L143>
4. Login Server `Session::loadUser` : <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/model/Session.cpp#L538>
5. Login Server `SessionManager::checkPwdValidation`:  <https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L601>
6. Login Server `SessionManager::isValid`  in Verbindung mit `SessionManager::init`: 
<https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L106>
<https://github.com/gradido/gradido/blob/login_hotfixes_1.5.1_reopen/login_server/src/cpp/SingletonManager/SessionManager.cpp#L49> 

Auffällig ist hier, dass beides mal die Funktion `checkPwdValidation`  aufgerufen wird, aber anscheinend mit verschiedenen Ergebnissen - bzw die Nutzer sind per se immer geladen und es triggern noch andere Teile des Codes - das ist unklar und ohne tiefergehendes Debugging nicht herauszufinden. Es scheint aber einen Unterschied zwischen `loadUser` alleine und der darum gelegten Kapsel `unsecureLogin` zu geben, die dazu führt, dass gültige Passwörter abgelehnt werden.

Im neuen Frontend mit der neuen Implementierung wird lediglich die Gültigkeit des Passwort hashes geprüft:
1.  Apollo `login`: <https://github.com/gradido/gradido/blob/master/backend/src/graphql/resolver/UserResolver.ts#L214> Das wirft entweder den Fehler `No user with this credentials` oder der Login ist erfolgreich (sofern die Datenbank zwischendrin nicht stirbt). Die konkrete Implementierung des Password-Hash-Berechnungs-Verfahrens ist in `SecretKeyCryptographyCreateKey` zu finden: <https://github.com/gradido/gradido/blob/master/backend/src/graphql/resolver/UserResolver.ts#L92>

**Comment by einhornimmond** [comment]
If you get it working in the new frontend, all is good.

**Comment by ulfgebhardt** [comment]
Closing this - its a problem in the old backend, but fixed in the new one
