### ISSUE TITLE
amendments for Registration-Process

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#1094]
This is a high prior feature and should be deployed in production as soon as possible!

As figured out in the picture 
https://github.com/gradido/gradido/blob/1011-Visualize_and_refine_the_register_process/docu/Concepts/BusinessRequirements/image/RegistrationProcess.png

the following parts have to be implemented in the new registration process:
- add a control flag to a new GDD account to create it in state "inactive"
- this flag will protect a login for a user with an inactive account
- if the user trys to login on an inactive account an error message will be shown with the hint to confirm his email address first and the possibility to resend the confirmation email again.
- as soon the user confirms his email address by the confirmation-link and the registration on klicktipp was successfull, this flag will be switch to state "active"
- the login for a GDD account will only be possible for an account in state "active"

Technical requirements:
- in case of implementation as a hotfix, the changes has to base on the TAG of the last release
- on the current master branch Dario had inserted two fixes for the next release

**Comment by clauspeterhuebner** [comment]
@ulfgebhardt: this ticket can be closed with the last hotfix rollout, right?

**Comment by ulfgebhardt** [comment]
I#d like to keep it open actually till we have refactored the login_server calls relating to this. I will assign myself tho and unassign you if thats cool with you.
