### ISSUE TITLE
🔧 [Refactor] First transaction cannot be expanded

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1106]
## 🔧 Refactor ticket

The first transaction has no decay block since no decay can happen between two decay blocks due to the fact only one exists. The decay for this account starts with this first transaction if its after the decay start block.

We implemented it that way, that the entry for a transaction is only expendable if a decay block is present (if its of type `sendCoin`). Since this is not aligned with the other transactions which are all expendable it is requested to explain the user why this transaction has no decay block in the expendable pane.

## TODO
- [ ] Add in transactionList a variable firstTransaction that would only be true wenn state_balance has no entrie for the user.
- [ ] Frontend react to firstTransaction flag

**Comment by ogerly** [comment]
@ulfgebhardt @Elweyn @Mogge 
wie im bild ersichtlich .. wird aud dem backend kein wert / keine werte für die erste transaktion mitgesendet. 
dadurch gibt es auch keinen button, weil auch in den aufklappbaren box - text nichts drin stehen würde. 

1. entweder ist dies so .. und der erste button ist eben nicht da. 
2. oder es müssen daten mitgesendet werden. die ich eintragen kann. 
3. oder ich mach den button hin .. aber es wird sich ncihts aufklappen. 

![FireShot Capture 921 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/150100332-ede4886a-01be-473d-a5ca-d526ff381aad.png)

**Comment by ulfgebhardt** [comment]
@ogerly Die Idee ist anzuzeigen, dass es der erste Eintrag ist und daher kein Decay block vorhanden ist - wie oben beschrieben.

**Comment by ulfgebhardt** [comment]
We need an marker for the first transaction from the backend since there can be transactions before the decay start block
