### ISSUE TITLE
🚀 [Feature] Team Page on Wordpress

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1117]
## 🚀 Feature

Present our Team to our stakeholders on Wordpress. The idea is to give the initiative a face besides @BerndHueckstaedt and show interested parties that its not just a small initiative but a whole team behind it.

We should consider to group people by profession/tasks but avoid to display a hierarchy if possible.

Examples:
![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/b0284f11-b5d3-4ab3-a080-d291e8643060)
https://css-tricks.com/creating-meet-team-page-wordpress/

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/923b797a-5f76-46aa-9064-ca1d2cdb7b68)
https://wordpress.org/plugins/tlp-team/

And here are several plugins for Wordpress in comparison: https://athemes.com/collections/best-team-members-plugins-for-wordpress/

**Comment by Mogge** [comment]
We have a team page! Oh yeah!
