### ISSUE TITLE
🚀 [Feature] Adminbereich Datenbank anfrage, abfrage Querys

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1124]
## 🚀 Feature
Für den Adminbereich werden folgende abfragen und anfragen für die Datenbanken benötigt. 

###Pages:
- Overview
- Usersuche
- Massenschöpfung
- Schöpfungen bestätigen
- Logdatei

 

   #### GET
- [x] Alle offenen **Schöpfungen** zum bestätigen abrufen
- [x] **Mitgliedersuche** nach Vorname, Name und Email, openCreations
- [x] **Mitgliedersuche** aller Mitglieder die ihre Email nicht bestätigt haben

   #### POST
- [x] Eine **Schöpfung** zum bestätigen speichern
- [x] Viele **Schöpfungen** zum bestätigen speichern
- [x] Eine **Schöpfung** endgültig bestätigen und speichern

   #### UPDATE
- [x] Eine **Schöpfung** zum bestätigen überschreiben / ändern

   #### DELETE
- [x] Eine **Schöpfung** löschen die zum bestätigen bereit ist

**Comment by ulfgebhardt** [comment]
- offene Schöpfungen anzahl
- User Suche -> Liste der User
- schöpfen für User
- Liste offener Schöpfungen
- offene Schöpfung verwerfen
- Schöpfung bestätigen (1x und nx)

**Comment by ogerly** [comment]
erledigt
