### ISSUE TITLE
🚀 [Feature] Send new Users Gradido

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1170]
## 🚀 Feature

Allow users to send Gradido to users not yet registred.

Two options:
- via EMail (e.g. in the send Formular)
- via Link (e.g for Social Media)

**Comment by clauspeterhuebner** [comment]
Start to describe the business requirement document for the use case "UC_Send_Users_Gradido.md"

**Comment by ulfgebhardt** [comment]
planning is done, implementation is started
