### ISSUE TITLE
🐛 [Bug] When not logging out session expires on next visit

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1177]
## 🐛 Bugreport

When not logging out, session expires on next visit.

1. Login locally
2. Close tab
3. Wait 30mins
4. Visit http://localhost/vue
5. Be greeted by "Session Expired" Error.

We should detect when a user comes back to the page and clear the token in the local storage.

**Comment by Mogge** [comment]
Cannot reproduce this behavior.
1. login
2. close tab
3. open localhost
4. I am on the login page without any errors

**Comment by Mogge** [comment]
I think this one was fixed with your refactoring of the JWT @ulfgebhardt

**Comment by ulfgebhardt** [comment]
closing
