### ISSUE TITLE
🐛 [Bug] Admin Creation Fields clear on Error

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1190]
## 🐛 Bugreport

When creating a new Creation in the Admin interface and an error occurs all fields clear - this was unexpected behaviour to me and force me to input all fields again. Imagine an admin losing net inbetween after typing a long message in the Memo field - he will be mad.

Do no clear the fields on error

**Comment by ogerly** [comment]
dieser fall tritt nicht mehr ein. es wird im vorfeld alles getstetet was fehler werfen könnte. man kann kein formular mehr absenden wenn bedingungn nicht erfüllt sind. es dürfte normal kein absenden möglich sein. es sollte also auch kein fehler merh geworfen werden.
