### ISSUE TITLE
🐛 [Bug] Vergänglichkeit besser darstellen

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1227]
## 🐛 Bugreport
Aufgabe: Die Vergänglichkeit sollte an dieser Stelle irgendwie besser erklärt werden. Sie kommt aus der Zeitspanne der letzten Anmeldung und der ersten folgenden Transaktion des Nutzers. (Informationsdesign)

![FireShot_Capture_879_-_Gradido_Account_-_localhost](https://user-images.githubusercontent.com/1324583/148235487-fc3e5682-454e-4477-8736-59c572abfb0f.png)

**Comment by BerndHueckstaedt** [comment]
Bitte Text und Reihenfolge ändern (Wörter wie "Zahlung", "bezahlen" usw. bitte vermeiden):

**Bestätige deine Transaktion – bitte überprüfe nochmal alle Daten!**

Aktueller Kontostand
Vergänglichkeit seit letzter Buchung
Verfügbarer Betrag
Deine Transaktion
Zu erwartender Kontostand nach Bestätigung
