### ISSUE TITLE
🚀 [Feature] Register EMail & Process

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#124]
## :rocket: Feature

Make the Register Process started via EMail fully implemented in vue.

We currently have a 3-Step Registration process. At least parts are implemented in community/login server. The frontend parts of those must be moved to the vue client

![image](https://user-images.githubusercontent.com/1238238/113835728-7f300080-978c-11eb-9ba8-2aee3f88c68e.png)

**Comment by ogerly** [comment]
#160 ist das das schon? @ulfgebhardt

**Comment by ulfgebhardt** [comment]
Nein @ogerly Dieses ticket beschäftigt sich mit dem Registrierungsprozess an sich.
Wir wollen das ganze Prozedere in unserem Interface implementieren. Ist ein 3-Stufiger Prozess und im Nachgang dann ggf. vereinfachen.

**Comment by ulfgebhardt** [comment]
How will the process be?
A: User registers on gradido and elopage account is created
B: or User registers on elopage and gradido account is created

**Comment by ogerly** [comment]
wie soll damit verfahren werden ?

**Comment by ulfgebhardt** [comment]
duplicate of #264
