### ISSUE TITLE
🐛 [Bug] Wallet - Page content layouting

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1253]
## 🐛 Bugreport

The layout of the page content changed and is not uniform anymore. I liked the `stick to the left and do not have full size` approach:

Move to the left:
![image](https://user-images.githubusercontent.com/1238238/148474612-4418b678-d42a-4953-8fc3-eef103dc2376.png)

make smaller and pin it to the left:
![image](https://user-images.githubusercontent.com/1238238/148474651-91fc71cf-a210-4da5-893e-17c91528d852.png)

Same:
![image](https://user-images.githubusercontent.com/1238238/148474683-ca4c15a6-3b72-498c-a35b-11e38aef439c.png)

Compare with this currently seen on gdd1.gradido.com:
![image](https://user-images.githubusercontent.com/1238238/148474766-683a0548-b6fe-45a7-a6f1-72bed1ba07d5.png)

**Comment by ogerly** [comment]
close isssues .. wenn neues design dann wird dies überfällig
