### ISSUE TITLE
🐛 [Bug] Registration does not work for Bernd

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1304]
## 🐛 Bugreport

Fazit: Registrieren ist mir leider nicht gelungen.
-> Unclear why and how
-> steps not 100% documented
-> please see Document for some more hints: https://docs.google.com/document/d/17d5eHI0Mv4b2aUylrsLjWcTFtEW-dyVbsa9W6UOk2Co/edit#heading=h.g2wjeyyvraby

**Comment by Mogge** [comment]
i think this is working now
