### ISSUE TITLE
🐛 [Bug] Error Message on first login

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1305]
## 🐛 Bugreport

I often get an error message when trying to login with correct credentials - on the second try it works. Could this be redirect related @Mogge ? Can you reproduce the problem? It seems to happen when building a new version of the frontend - probl. with exist local storage

Beim 1. Versuch als peter@lustig.de einzuloggen kam Fehlermeldung.
Das 2. Mal ging es dann.

![image](https://user-images.githubusercontent.com/1238238/150367765-23b38e0c-0fb3-4e62-beb4-600e5f310e62.png)

**Comment by Mogge** [comment]
Is this still a problem? Looks like the same issue as closing the tab and then login again, which should be fixed.

**Comment by BerndHueckstaedt** [comment]
Das ist mir heute Morgen wieder passiert. Allerdings vermute ich, dass ich beim Passwort ein Leerzeichen zu viel kopiert habe. Das ist ein häufiger Bedienungsfehler bei vielen Usern, und ich verstehe ehrlich gesagt nicht, warum man das Passwort nicht trimmen kann bzw. will. Da Leerzeichen  bei Passwörtern nicht zugelassen und auch unüblich sind, würde ich einfach alle Leerzeichen im Passwort-Feld rausnehmen. replace (" "; "") o.ä.
