### ISSUE TITLE
🐛 [Bug] ADMIN - Berechnung Schöpfungen falsch

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1323]
## 🐛 Bugreport
In der User Transaktionsliste sind die angaben der geschöpften Summen und der noch offenen Beträge für Schöpfungen nicht richtig. 1. es dürfen pro Monat nie mehr als 1000 GDD geschöpft werden
2. der geschöpfte Betrag und der noch offenen zu schöpfenden Betrag müssen in der Addition immer 1000 GDD ergeben!

![FireShot Capture 925 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/150176729-c9da8b33-e8db-4a74-b26b-21a732f50e44.png)

![FireShot Capture 927 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/150176737-86eaf836-c3cd-4e28-8199-959452a7f848.png)

![FireShot Capture 928 - Gradido Admin Interface - localhost](https://user-images.githubusercontent.com/1324583/150176743-b6608af8-2884-49c3-8ce4-76e544360a6b.png)

**Comment by Elweyn** [comment]
Hi @ogerly,
OK that it should not work like this but we need some detailed user story to understand how the error has been generated!
- For the first picture I would say that the user story would be: Admin creates two creations the first would be 500 for the month december and the second would be 190 also for december.
After that as Admin I would expect that the user has 1000 -  690 = 310 as open creation for december but as we see on the screenshot it is still 1000.
Question: Is this still the case after a refresh?
- For the second picture the User Story should be something like: As Admin I create for a User two creations (600 and 390) after this their should only be 10 gradido left for creation. But when I go on the massCreation and select the previous User in the list and create 500 Gradidos for the month this user get's also 500 when he should only get 10 or nothing.
- For the third picture it is the same behavior as picture 1 or do I miss something?

**Comment by Elweyn** [comment]
@ogerly wie ist das zur stande gekommen???
Ich kann es lokal nicht nachvollziehen:
Habe 2 Schöpfung für Bibi erstellt eine von 600 GDD die zweite mit 360 GDD. Dann habe ich versucht eine Mehrfach schöpfung zu erstellen mit 3 User in höhe von 500 GDDs, diese wurde für 2 User erstellt aber nicht für Bibi was meiner Meinung nach das richtige Verhalten wäre.

**Comment by ogerly** [comment]
> @ogerly wie ist das zur stande gekommen??? Ich kann es lokal nicht nachvollziehen: Habe 2 Schöpfung für Bibi erstellt ....

ich bin mir nicht sicher ob es einfach daran liegt das ich viele daten drin habe und diese nie gelöscht habe. ich muss mal meine DB resten und dies noch mal versuchen. 
mir ist es einfach aufgefallen. das die daten nicht stimmten. wenn ich die transaktionliste aufrufte. 
wenn also bei dir keine fehler mehr auftauchen .. dann könnte alles passen.

**Comment by Elweyn** [comment]
Dann setze ich das Ticket jetzt erstmal in die Review Spalte!
Damit wir darauf noch ein Auge halten kann

**Comment by ogerly** [comment]
es scheint zu funktionieren.
