### ISSUE TITLE
🔧 [Refactor] ADMIN - Search not good enough for admin interface 

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1340]
## 🔧 Refactor ticket
Search not good enough for admin interface - search for ulf returns empty

**Comment by ogerly** [comment]
glaube ich nicht! die suche auf der frontendseite wenn alle user geladen sind funktioniert über klein oder grossschreibung. vor und zuname und email. dabei wird alles durchssucht. der anfang eines string sowie im string.
wenn ulf also in der liste vorhanden ist und in der suche der filter über die liste fäuft muss er ohne probleme gefunden werden.


leider kann ich es nicht testen. da ich kein admin bin. 

- ist ulf schon in der liste bevor gesucht wird? 
- wenn nein. wie wird ulf auf der backendseite gesucht bzw. gefiltert? 
.where(
        'user.firstName like :name or user.lastName like :lastName or user.email like :email',
        {
          name: %${searchCriteria}%,
          lastName: %${searchCriteria}%,
          email: %${searchCriteria}%,
        },

ich sehe  hier kein problem. 

ich muss das sehen, es kann nicht sein das ulf lehr bleibt. es muss ein anders problem geben!?

**Comment by ulfgebhardt** [comment]
Was an encoding problem
