### ISSUE TITLE
🌟 [EPIC] Wallet: Send Users Gradido

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1381]
### Link & QR-Code

(https://github.com/gradido/gradido/blob/1170_Send_new_Users_Gradido/docu/Concepts/BusinessRequirements/UC_Send_Users_Gradido.md)

In this issue, the requirements for the use case "Send Users Gradido" are to be collected and the individual issues are to be listed.

### issue liste
- wallet frontend: grafische anforderungen für link erstellen
- wallet frontend: grafische anforderungen für qr-code erstellen
- wallet frontend: grafische anforderungen für link darstellen
- wallet frontend: grafische anforderungen für qr-code darstellen

- wallet backend: technische anforderung für link erstellen, speichern, zeitspanne und löschen 
- wallet backend: technische anforderung für qr-code erstellen, speichern , zeitspanne und löschen  
- wallet backend: technische anforderung für gespeicherten link abrufen und ans frontend übergeben 
- wallet backend: technische anforderung für gespeicherten qr-code abrufen und ans frontend übergeben  

- wallet frontend und backend testen.

**Comment by ulfgebhardt** [comment]
closing in favor of #1544
