### ISSUE TITLE
🐛 [Bug] GDT has several severe issues

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1395]
## 🐛 Bugreport

The GDT Service (live) has several issues:

1. If a payment is cancled the GDT are still valued
`bei Gerda *** gerda@***.ch wurden GDT gebucht, trotz Abbruch der Zahlung. Ist das vielleicht ein grundsätzlicher Fehler?`

2. GDT events are evaluated twice on some accounts. This is not happening with every account, just some
![image](https://user-images.githubusercontent.com/1238238/151860788-51ce543b-65b9-46ce-92ff-9ce5e9fbbeba.png)

**Comment by einhornimmond** [comment]
1. Ja, scheint so. Elopage hat wohl wieder mal ihre Api verändert und es gibt jetzt das event payment.canceled oder es hat bisher keiner seine payments gecanceld daher kannte ich das noch nicht. Der erste Eintrag mit diesem Event ist vom 2020-04-30.
Ich werde meinen Code entsprechend anpassen, darauf zu reagieren. 
2. Obwohl ich nun schon Table- und Filelock benutze um zu verhindern das es zweimal berechnet wird, wenn der Apollo Server zweimal gleichzeitig die Daten für einen Benutzer abrufen will. Ich überlege mir eine andere Lösung.

**Comment by einhornimmond** [comment]
1. fixed, for elopage transactions with the event = payment.canceled no gdt entry will be created, I also deleted all gdt entries which are linked to elopage_transactions with the event = payment.canceled, and deleted the modificator entries for this, so that they can be recalculated next time the gdt entries will be requested.

**Comment by einhornimmond** [comment]
2. fixed, in case that table lock and file lock failed, the new code can detect gdt entries doubletten from global modificator and remove them.
