### ISSUE TITLE
🐛 [Bug] GDT has to display the correct amount

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#142]
## :bug: Bugreport

GDT has to display the correct amount. On our test it was not divided by 10.000. We should investigate more how to do this division transition with an component/mixin

- [X] GDT has to display the correct amount divided by 10k
- [ ] Have a component/mixin for this division

**Comment by ulfgebhardt** [comment]
Testen nur möglich auf staging

**Comment by Mogge** [comment]
I would like to close this issue.The GDT amount is rendered only in one place by know with the correct amount. Later we should receive the correct value from the server

**Comment by einhornimmond** [comment]
GDT has only 2 places after zero, divide by 100 is enough.
