### ISSUE TITLE
🚀 [Feature] Hide GDT display when 0

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#143]
## :rocket: Feature

Hide GDT display when 0

Discussion:

Is this useful? Should we use it as incentive to get some? @BerndHueckstaedt 
-> "Buy some GDT today"

**Comment by BerndHueckstaedt** [comment]
I would not hide. I would show 0

Good idea: "Support Gradido now and be thanked with 15x GDT.".

**Comment by ulfgebhardt** [comment]
closing in favor of https://github.com/gradido/gradido/issues/188
-> No change for displaying the 0 GDT
-> Needs concept for advertising buy options
