### ISSUE TITLE
🚀 [Feature] Admin Password reset

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#146]
## :rocket: Feature

This seems obsolete, since the user can reset his own password?

![image](https://user-images.githubusercontent.com/1238238/113839295-db485400-978f-11eb-89ea-904a04dc6402.png)

Whats the purpose of this @einhornimmond ?

**Comment by einhornimmond** [comment]
Der Private Key der Benutzer wird mit ihren Passwörtern verschlüsselt. Wenn das Passwort verloren geht, haben sie kein Zugang mehr zu ihren Privat Keys. Damit wäre ein Passwort Reset unmöglich. 
Um das zu umgehen haben wir anfangs mit Passphrasen wie Bitcoin und Co. gearbeitet. 
Die Benutzer haben bei der Registrierung ihre Passphrase gezeigt bekommen und sie wurden gebeten sie sicher zu speichern. 
Aber das hat zu vielen Irritationen geführt. Darum haben wir das erstmal aus dem Interface verbannt. 

Stattdessen ist meine Idee die Passphrasen zusätzlich mit dem/einen Admin Public Key zu verschlüsseln so das nur noch der Admin neben den Beutzer Zugriff auf diese Daten hat. Wenn dann der Benutzer sein Password vergisst muss der Admin die Passphrase wieder freischalten und kann dem User dann so eine E-Mail schicken. 
Das würde eigentlich auch in die Benutzer-Suche gehören, aber als ich das geschrieben habe, gab es die noch nicht, ist also ein Vorläufer. 

Aktuell werden die Passphrasen noch unverschlüsselt gespeichert und solange das der Fall ist, ist eine einfachere Umsetzung der Password vergessen Methode möglich. Das ist aber nur ein Übergangsschritt. So aktuell wird das nicht gebraucht, aber vielleicht brauche in Zukunft Code Teile davon.. daher ist es noch da. Ich tue mich generell schwer damit Code einfach wegzuschmeißen (._.);

**Comment by ulfgebhardt** [comment]
Was bedeutet das Passwort wird unverschlüsselt gespeichert?
`Aktuell werden die Passphrasen noch unverschlüsselt gespeichert  [...] `
Also nur gesaltet und mit einer definierten passphrase gesichert?

**Comment by einhornimmond** [comment]
Eine Passphrase besteht aus 24 Wörtern in einer definierten Reihenfolge. Genauso im Klartext in Englischer Sprache werden sie gespeichert. Die englische Wortliste ist dieselbe die auch Bitcoin verwendet in derselben Reihenfolge. Die Deutsche Wortliste ist pseudo-zufällig sortiert. Damit ist die deutsche Passphrase im Prinzip gesalzen. 
Hiermit wird die Deutsche Wortliste erstellt: https://github.com/gradido/mnemonic/blob/HEAD/call.sh 
dabei ist 281726334 das Salz.
Solange es alles öffentlich auf github ist, bringt es natürlich kaum Nutzen, aber es ist einfach möglich eine eigene Wortlistensortierung zu erzeugen indem man die Nummer verändert. Dann sind die deutschen Passphrasen die davon ausgegeben werden, nur mit dem ausgebendem Login-Server kompatibel. Das allerdings würde verhindern das man mit seiner Passphrase auf einen anderen Login-Server umziehen kann, Hoheit über die eigenen Daten. Das Konzept ist noch nicht final. 

Wie auch immer, die 24 indices werden als Input für sha512 genutzt sowie die Passphrase selbst, also die Englische Version, die 24 Wörter mit jeweils ein Leerzeichen Abstand dazwischen und eines am Ende als ein string. 
Dieser Hash wird dann als Seed benutzt um das ed25519 Schlüsselpaar (public und private) zu erzeugen.

Jedenfalls diese Passphrase bestehend aus 24 englischen Wörtern wird im Klartext gespeichert. Das meinte ich mit unverschlüsselt. 
Und wenn jemand ein Password Reset macht, wird aus der Passphrase das Schlüsselpaar neu generiert und der private key mit der neuen E-Mail-Passwort Kombination verschlüsselt.
Sobald die Passphrase verschlüsselt gespeichert wird, geht das natürlich nicht mehr.

**Comment by ulfgebhardt** [comment]
obsolete
