### ISSUE TITLE
🚀 [Feature] Contact ability when receiving GDD

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1488]
## 🚀 Feature

Contact ability when receiving GDD. Currently the one who receives GDD has no way to contact the sender or send GDD back. Since we currently do not have an anonymized Gradido-ID, we must provide the email in the email sent out and also have the user-name clickable in the transaction list.

- [x] Provide email of sender when receiving GDD
- [x] Click on Sender's Username in transaction list opens the sendGDD formular with the correct email filled in
- [x] Followup Issue to make this work without the email, but an Gradido-ID

**Comment by BerndHueckstaedt** [comment]
If we allow zero transactions, i.e. with amount 0.00, we would have a simple message system integrated.

**Comment by ulfgebhardt** [comment]
This is done & merged
