### ISSUE TITLE
🚀 [Feature] Backup Cron

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1489]
## 🚀 Feature

Have a cron on our deployments to backup data every day/week automatically

**Comment by clauspeterhuebner** [comment]
add a cronjob for user gradido to invoke each day at 3:00 am the script backup.sh on the stages:
- stage2
- production

the crontab-entry:
0 3 * * * ~/gradido/deployment/bare_metal/backup.sh
