### ISSUE TITLE
🐛 [Bug] Error messages are somehow encoded

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#15]
## :bug: Bugreport

![image](https://user-images.githubusercontent.com/1238238/109227726-0dde5480-77c1-11eb-80b1-e8f952b13b4c.png)

As seen in the screenshot the error messages are somehow encoded. Json can handle utf8. I recommend to use utf8 and leave encoding to the client/frontend

**Comment by einhornimmond** [comment]
It is html encoded because utf8 in c++-source on windows is a pain in the ass. 
But you are right it isn't ideal. It isn't final, in the end the message in code should be in english and then translatet via gettext. 
So should I priorize that update?

**Comment by ulfgebhardt** [comment]
Nah its fine.its just something we should change longterm
