### ISSUE TITLE
🚀 [Feature] Anonymous Identifier for the User

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#150]
## :rocket: Feature

We need an anonymous Identifier for the User so we do not need to expose his email address for payment.
The main question here is how?
- human readable slug?
- username (unique?)
- public key (not human readable)?
- user defined?
- ...

Do we expect the user to expose his user name? His real name? Whats the policy here?

Do you have some more ideas or preferences @einhornimmond ?

**Comment by einhornimmond** [comment]
Username unique per community is the best in my eyes. 
Username unique in whole gradido network ist difficult.

**Comment by BerndHueckstaedt** [comment]
community.tld/u/username
can also be used as Gradido-Link

**Comment by einhornimmond** [comment]
Transactions can be created with user email, username or public_key. 
For me this issue is closed with that, what do you think @ulfgebhardt ?

**Comment by clauspeterhuebner** [comment]
is solved with the alias-concept, see #2874
this ticket will be closed
