### ISSUE TITLE
🚀 [Feature] Disallow creation for deleted Accounts

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1509]
## 🚀 Feature

While this might be already implemented in #1504 we should warn the admin when trying to create GDD for an disabled account.

Creating GDD for disabled accounts must be impossible

Scenario:
- Admin starts creation
- Other Admin disables account
- Admin confirms creation

**Comment by Mogge** [comment]
The backend does not allow to create creations for deleted users. As I cannot see any way to confirm a not existing creation, I think we are good here.

**Comment by Mogge** [comment]
OK. Now I saw the scenario. I will fix this.
