### ISSUE TITLE
🚀 [Feature] Marketplace

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#151]
## :rocket: Feature

Have a Marketplace for Gradido.

We have multiple options to archieve this:
- In the Software integrated
- External, but self-made product
- External Software implementing the required features + Gradido integration (e.g. Ocelot)

### Additional context

The Marketplace would need:
- A way to promote a Product
- Chat
- Location
- Pricing for a Product

**Comment by BerndHueckstaedt** [comment]
We decided together yesterday not to develop a marketplace ourselves. Instead, a simple Gradido button. Initially, this only needs to contain the Gradido link.

**Comment by ulfgebhardt** [comment]
We will use Ebay Kleinanzeigen - closing
