### ISSUE TITLE
🐛 [Bug] Admin - the admin frontend seems to define the field `creationDate`

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1561]
## 🐛 Bugreport

the admin frontend seems to define the field `creationDate`. While it is the first of the month for the months in the past, it always is the current date for the current month.
This value must be properly checked, verified and generated in the backend.

**Comment by Mogge** [comment]
Where is the problem? Do you want to have the first day of the month for the current month too? I do not understand this issue.

**Comment by ulfgebhardt** [comment]
I am closing this since it most likely will be refactored for the contributions and at current time its unclear what date would be correct.
