### ISSUE TITLE
🚀 [Feature] Concept to introduce Gradido-ID

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#1574]
describe the introduction of the Gradido-ID and all its concerning aspects:

* DB-Migration
   - in Nutzertabelle Feld UUID einführen
   - in Nutzertabelle Feld Alias einführen
   - Versionsfeld für Passwort-Verschlüsselung
       * V1: Email
       * V2: UUID
   - Community-Tabelle mit Community-ID
	 
* Prozesse:
      - Registrierung / Login
      - Passwort-Verschlüsselung
	    * muss versioniert werden
		* mit Login wird dann ein Update der Verschlüsselung auf UUID umgestellt
		* 
      - Umzugsservice
	    * Prüfung auf existente UUID
		* Trigger für Weiterleitung
      - Identity-Mapper
	    * von email -> UUID
	    * von alias -> UUID
	    * von... -> UUID
      - Umbenennung der Community
      - Community/Nutzer (aus-)sperren
         * Blockchain als Doppelte unabhängige Datenbasis
	 * Node-Server Betrieb auf Community-Ebene + als Gemeinwohl einzelner Nerds
     -

**Comment by ulfgebhardt** [comment]
@clauspeterhuebner Can you please investigate this issue and make a followup ticket for stuff still missing?

**Comment by ulfgebhardt** [comment]
@clauspeterhuebner You can just put them into ice box or leave them in New Issues - I will take care in given time.

**Comment by clauspeterhuebner** [comment]
@ulfgebhardt nice...
i attach the new tickets with the Epic Gradido-ID, right? O ris there an other place, where they should documented?

**Comment by clauspeterhuebner** [comment]
@ulfgebhardt i assume, that the password encryption change from Joseji contains the requirements of https://github.com/gradido/gradido/blob/master/docu/Concepts/TechnicalRequirements/UC_Introduction_of_Gradido-ID.md#2nd-stage, right?

**Comment by ulfgebhardt** [comment]
> 

I think stage2 is complted once the cleanup PR of @jjimenezgarcia is merged.
