### ISSUE TITLE
🚀 [Feature] User identification via username or slug

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#163]
## :rocket: Feature

User identification via username or slug.

We need to identify the user consistently via an username or slug instead of the email.

The suggestion is to furthermore to have a link to that user using the username/slug

`community.tld/u/usernameorslug`

This is rquired for #148

**Comment by einhornimmond** [comment]
The user can be identified with a username since #478
Do you need more for this Issue to finished @ulfgebhardt ?

**Comment by clauspeterhuebner** [comment]
Decition in Meeting 28.12.2021 16:00:
========================

Definition Pattern for new "username":
<communityname>/<useralias>
  * communityname
    - URL allowed signs
      * A-Z, a-z, 0-9
      * '-', '.', '_', '~'
  * useralias:
    - min 5 signs 
      * alphanumerisch
      * keine Umlaute
      * '-' und '_' sind nur zwischen sonst gültigen Zeichen erlaubt ([a-zA-Z0-9]-|_[a-zA-Z0-9])
    - blacklist of keywords, which have to be defined
    - reserved system relevant names must have max 4 signs

**Comment by clauspeterhuebner** [comment]
all requirements of this ticket are part of the Epic: GradidoID and its concepts.
So this ticket will be closed.
