### ISSUE TITLE
🔧 [Refactor] generate the full link in backend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1637]
## 🔧 Refactor ticket

This is also a discussion:

Generate the full link in the backend and transmit it in full to the frontend.
Currently we cannot serve proper links to Gradido-Installations which are in a subfolder `https://test.com/wallet/`. Instead the link will always point to `https://test.com/` and append the  `redeem/ABC123`.

We generate the other links like the email content etc also in the backend and configure it there - I believe we should do the same for the redeem link.

- Additional field link in GraphQL
- Configure base URL for redeem in backend
- Deliver field from backend
- Request and display link from backend instead of building it in the frontend

**Comment by Elweyn** [comment]
@Mogge, @ulfgebhardt,
not sure how to do it best!? Until now we store the code in the DB what is good in my eyes, but if we add the base URL of the Community & redeem/ we can't know how long the code should be:
On localhost I should put the code column to 48, on gdd.gradido.net some other length and on gdd1.gradido.net again some other length...
- gdd.gradido.net/redeem/SOMETHING
- gdd1.gradido.net/redeem/SOMETHING
So a solution could be to just add it to the return value out with code but it would not be to nice!?
What are your though about it?
