### ISSUE TITLE
💬 [Question] Decentralization

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#165]
## :speech_balloon: Question

What is the concept for decentralization?

- [ ] What data is decentralized?
- [ ] How can another participant join the network?
- [ ] What data is centralized?
- [ ] What is the contract one has to sign to join?
- [ ] What are the technical implications?

**Comment by einhornimmond** [comment]
## Decentralized data (data in blockchain)
- Gradido balance and all transactions changing balance
- which public key belongs to which group (community) (every public key can only belong to one group at a time) (many-to-one)
- which email (saved as hash) belong to which public key (maybe many-to-one?)
- which username (saved as hash) belongs to which public key (maybe many-to-one?)
- which group can trade which other group (many-to-many)
- group alias unique in gradido network
- user identification hash unique in gradido network
- voting system
  - voting config (for example how many signatures needed for each creation transaction or how people get roles)
  - votes for giving people special roles
  - data for universal, direct, free, equal and secret ballot (if people want demon cracy)

## How can another participant join the network?
- download and host gradido software
- check if group alias isn't already used (with hedera, special topic for network wide data, use a special discovery transaction to get answear from gradido nodes connected to hedera without the need of knowing gradido node ips)
- contact other group and if both like each other, make  connect group transaction to connect groups and allow trading with each other
- if someones like to support existing groupes with gradido node he uses special discovery transaction to get gradido node ips which host desired groups to synchronize blockchain with them 

## Centralized Data
### Community Server
- activities
- user profiles
- maybe chat and/or forum

### Login-Server (optional)
- public key
- with user email and password encrypted private key
- email and password hash
- with server admin public key encrypted passphrase (optional)

## What is the contract one has to sign to join
contracts I named are the Protobuf message types find in gradido_protocol

### to join existing group
- GroupMemberUpdate with MemberUpdateType = ADD_USER if he wasn't in any group before (signed by user and new group)
- GroupMemberUpdate with MemberUpdateType = MOVE_USER_INBOUND to new group and (signed by user and new group)
  GroupMemberUpdate with MemberUpdateType = MOVE_USER_OUTBOUND to old group (signed by user maybe also by new group)
### join a group with own group
- GroupFriendsUpdate (concept not finished yet)
