### ISSUE TITLE
💬 [Question] Does the account balance now include the decay?

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1652]
## 💬 Question

Does the account balance now include the decay?

**Comment by Elweyn** [comment]
@ulfgebhardt @Mogge @ogerly not sure what you mean with this? The GDD in the top right seem to have the decay included:
Bibi had 1000 at the start, made a donation of 100 with 0,04 as decay, and has now a decay of 0,02. In the top their is 899,94 as balance!

If I try to send 899,94 to someone it is still not allowed to send them!
