### ISSUE TITLE
💬 [Question] Do we want to do Math in the frontend?

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#168]
So far the server returns the balance in Gradido units to the client. This means that the client has to do some math like
```
  state.user.balance = balance / 10000
```
(see `src/store/store.js` line 59)

This could lead to rounding errors in the client. Would it be better to return the amount seen by the user to the client, e.g. do this math on the server before sending the response to the client?

**Comment by ulfgebhardt** [comment]
I think we have to do this till we have a proper API. I think it would be wise to do this in a central unit, so the math is happening in one play only. E.g. use a component `<currency>{value}</currency>` or `<currency value="{value}" />` . While it might be intuitive to use a `<gdd/>` component, the same problem arise for GDT and would duplicate the math code.

To avoid rounding mistakes calculation should happen this way: `floor($value >> 4)`

In the long run this should move somewhere in the backend

**Comment by einhornimmond** [comment]
If you like it better I can change the API output to give you the balance as decimal.

**Comment by Mogge** [comment]
@einhornimmond Yes, please. I really prefer not to do the math in the frontend

**Comment by einhornimmond** [comment]
#171

**Comment by ulfgebhardt** [comment]
closing in favor of #171
