### ISSUE TITLE
🐛 [Bug] Api responses are not uniform and well strutured

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#17]
## :bug: Bugreport

Api responses are not uniform and well strutured

For  `http://localhost/login_api/createUser`
```
{"msg":"user already exist","state":"exist"}
```

For `http://localhost/login_api/createUser`

```
{
details: "Passwort: Bitte gebe ein g&uuml;ltiges Password ein mit mindestens 8 Zeichen, Gro&szlig;- und Kleinbuchstaben, mindestens einer Zahl und einem Sonderzeichen (@$!%*?&+-_) ein!"
msg: "Passwort: Dein Passwort ist zu kurz!"
state: "error"
}
```

Suggestion:

```
{
success: boolean,
error: String
result: {...}
}

**Comment by einhornimmond** [comment]
I use a string for state instead of boolean because I need only one comparisation if(state == 'success') instead of 
if(state == true || state == 'true' || state == 1)
and I can better group the reactions on different cases.

It may not be perfect. 
I have been using this system for quite a long time in various projects and find it really handy. 
But I can rewrite it if you want. It just takes time. 
I use it a lot in community-server, login-server and in the json part I have written in gn for stage2.

**Comment by ulfgebhardt** [comment]
it requires me to do stuff like this:

```
      try {
      const result = await axios.post(LOGIN_API_URL + 'unsecureLogin', payload);
      if(result.status !== 200){
        throw new Error('HTTP Status Error '+result.status)
      }
      if(result.data.state === 'error'){
        throw new Error(result.data.msg)
      }
      if(result.data.state !== 'success'){
        throw new Error(result.data)
      }
      return { success: true, result }
    } catch(error){
      return { success: false, result: error}
    }
```

**Comment by einhornimmond** [comment]
Why so complicated? 
Why not that:
try {
      const result = await axios.post(LOGIN_API_URL + 'unsecureLogin', payload);
      if(result.status !== 200){
        throw new Error('HTTP Status Error '+result.status)
      }
      if(result.data.state === 'success') {
        return { success: true, result }
      }
      return { success: false, result.data.msg }
} catch(error){
      return { success: false, result: error}
}

**Comment by ulfgebhardt** [comment]
Since `data.msg` is not present all times - and for the password stuff I need to use `data.details` or something to get a specific error message. Its not very pressing, but I recommend that we define a well structured API for the whole service. That way we can uniformly handle it.

-> Furthermore You claim to set cookies, but I never get any cookie requests with the http results. Any Idea why that is?

**Comment by einhornimmond** [comment]
You can convert my format into yours with:

function convertResult(result) 
{
	if(result.state ==='success') {
		return {success:true, error:'', result:result}
	} 
	var error = result.msg;
	if(result.details !== undefined) {
		if(typeof result.details === 'string') {
			error = error + '[' + result.details + ']';
		} else {
			error = error + '[' + JSON.stringify(result.details) + ']';
		}
	}
	return {success:false, error:error};
}

**Comment by einhornimmond** [comment]
if state isn't success, msg is set all the time, and sometimes also details with additional details for easyer debugging. 
If you found a place with state isn't success and msg isn't set, I fix it.

**Comment by ulfgebhardt** [comment]
I understand that - tho this makes it even more comlicated. What I would like to have is something like this:

```
try {
  const result = await http.request(url,payload)
  if(!result.success){
    throw new Errror(result.error.msg)
  }
  return {success: true, result}
} catch (error){
   return {success: false, error}
}
```

Further more one could ecapsulate away the whole try catch stuff further and just recieve an success call:

`return myAPI.call(myURLorJustURLSuffix,myPayload);`

**Comment by einhornimmond** [comment]
Oh I see, I have call setHttpOnly to prevent that cookie can be readed by js (._.);

**Comment by ulfgebhardt** [comment]
I simplified this as suggested - for the future I suggest a refactoring of the whole login procedure, api interface & authorization handling. For now we get it to work - and I guess we made some steps there already <3

I will make followup issues and then close this
