### ISSUE TITLE
🐛 [Bug] submit button disabled when total amount to submit is minus

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1703]
## 🐛 Bugreport
submit button disabled when total amount to submit is minus

If I send the entire sum of my GDD then I must 
1. the resulting decay must be taken into account
2. a transaction should not be sendable if the send button on the transaction confirm is disabled when checking or offsetting and I have a minus amount in the total.

**Comment by ulfgebhardt** [comment]
seems not fixed (test on stage2)

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/161154844-06237065-4cea-4cff-8ae1-8237391fb1aa.png)
