### ISSUE TITLE
🐛 [Bug] When session is expired redeem link is not transported

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1736]
## 🐛 Bugreport
When session is expired redeem link is not transported properly.

- Use Vue Times <https://www.npmjs.com/package/vue-timers>
- Check every 10 seconds if the auth token is still valid.
- 1 minute before the session expires please open a modal, with time expiration and the possibility to extend the session

**Comment by ogerly** [comment]
wenn ich die session auslaufen lasse und mich nicht amelde dann bleiben die daten im vuex cookie stehen. wenn ich dann den redeem link erneut aufrufe dann erkennt er nicht das man schon abgemeldet ist und prüft beim abrifend er redeem info nicht ob angemeldet oder nicht. 
dehalb kommt es zu diesem problem. 

vorschlag: beim abrufen des links muss schon backendseitig geprüft werden ob der user noch angemeldet ist .. wenn nciht dann muss der loginbereich kommen mit dem redeem link angehnagen. und dem hinweis .. die sitzung wurde beendet .. blabla

**Comment by ogerly** [comment]
Meeting vom 21.06.2022

- Nutze Vue Times
- Prüfe aller 10 Sekunden, ob das auth token noch gültig ist.
- 1 Minute vor Ablauf der Session bitte ein modal offenen, mit Zeitablauf und der Möglichkeit, die Session zu verlängern
