### ISSUE TITLE
🚀 [Feature] Coverage Tests for Login & Community Server

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#177]
## :rocket: Feature

Have a coverage test for login_server & community_server like for the frontend. So we can make sure we don't drop in coverage.

- [x] Run tests on LS
- [x] Run tests on CS
- [x] Generate Coverage
- [x] Test LS for Coverage Goal in test workflow
- [ ] Test CS for Coverage Goal in test workflow

It is not important how much coverage we have. It is important that we ensure we at least have x% coverage automatically

**Comment by einhornimmond** [comment]
What means LS and CS?

**Comment by ulfgebhardt** [comment]
Login Server and Community Server @einhornimmond
