### ISSUE TITLE
🚀 [Feature] On Auto Logout Show Automatically The Login Page

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#1781]
## 🚀 Feature

```gherkin
Feature: On auto logout go to login page
As a user I want to recognice if I am already logged out or not.
```

At the moment we have this szenario:

After a pause I went back to the Gradido page and do a transaction.
When I do a transaction and click send I am redirected to the login page.
If I login again I eventually can see that the transaction wasn't done.
I can guess that I was automatically logged out already,

**Comment by ulfgebhardt** [comment]
Related to #888
