### ISSUE TITLE
🔧 [Refactor] Menu

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#179]
## :zap: Refactor ticket

We had a discussion about the menu. Currently we have two menus. There is two options:
- Have one menu
- Have two menus with distinctively different tasks

The common consensus was: Two menus, one for banking, one for the user. I disagree tho - I believe one menu is sufficient at the given time, its less work, easier to communicate to the user.

We could not reach a final decision. If I have to decide, I would go with 1 menu as stated above and I will outline it here. Please make a suggestion for the two menu option (@Mogge (?))

Furthermore I'd like to have symbols for every menu entry using fontawesome (or something else) as icon library. The corresponding icons are denoted behind the Menu. The English translation has to be found according to the German words.

Menu:
```
- Überweisen (Statt Senden) (money-bill-wave)
- Umsätze (statt Transactions) (wallet)
- Schöpfen (statt Aktivitäten) (hand-holding-medical)
----
- Stammdaten (Statt Mein Profil & Settings) (address-card)
----
- Ausloggen (sign-out-alt)
```

**Comment by Mogge** [comment]
We agreed on having only one menu.
