### ISSUE TITLE
🚀 [Feature] Event Protocol 2: introduce event creation invocations

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#1795]
## 🚀 Feature

base on the business event protocol concept #1793 
insert at the specific location of the business logic the matching even creation invocation incuding with the correct event type initialization.

**Comment by ulfgebhardt** [comment]
@clauspeterhuebner whats the status on this?

**Comment by clauspeterhuebner** [comment]
issue will be solved by #2797 , close ticket
