### ISSUE TITLE
🔧 [Refactor] Check whether there is an Internet connection

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1824]
## 🔧 Refactor ticket
Check whether there is an Internet connection. If there is not, interrupt the binding process. 
Graphically inform the user that there is no connection to the Internet. 
(red, orange / green, yellow)

### Beispiel Code

``<div id="app">	
	<p>Connected Status = {{connectionStatus}}</p>
	<button @click="myFunction()">Click Me</button>
</div>
<script>
 new Vue({
el: '#app',
  
  data: { 
	  connectionStatus:''
  },
  
   methods:{
    myFunction: function () {	
		if(navigator.onLine){
		this.connectionStatus = "Connected to internet.";
		}else{
		this.connectionStatus = "Unable to connect to internet.";	
		}
    }
   }

});
</script> ``

![FireShot Capture 1154 - Navigator onLine - Web APIs - MDN - developer mozilla org](https://user-images.githubusercontent.com/1324583/164648454-4a51915e-5cb0-4f86-a455-9716f4966790.png)
[https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)

**Comment by BerndHueckstaedt** [comment]
This is also very important when logging in. Recently I got an error message that no account with my data is known. After that I realized that I was offline.
I also remember support tickets where it said that the password no longer works, and shortly afterwards it worked again. This could also be related to that.

**Comment by ogerly** [comment]
no elaboration, too old and will be deleted
