### ISSUE TITLE
🚀 [Feature] On Register: subscribe to Newsletter (Clicktip)

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#185]
## :rocket: Feature

On Register: subscribe to Newsletter (Clicktip)

1. User registers
2. Hook is sent to Clicktip (server) to register his EMail with the newsletter

Furthermore we need an options in the user profile in the client to unsubscribe/resubscribe

1. Where can we find the corresponding api documentation for the clicktip service? @BerndHueckstaedt 
2. Is there an implementation already for this? @einhornimmond 
3. How do we want to handle the tunneling of the clicktip api stuff? Community server? Node server? Login server? @einhornimmond 
4. Design & Implement UI @ogerly 
5. Implement API connection `Frontend <-> Backend` @Mogge

**Comment by einhornimmond** [comment]
Here is the API doc for klicktipp: 
https://support.klicktipp.com/article/393-api-function-overview
It exist a php-Wrapper for it so I think the best would be implement this functionality in community-server. 
But this is a feature which is used only by us. It dosn't belong to gradido, so better I implement it such that it is easy to remove later.

**Comment by einhornimmond** [comment]
First step is done with #241

**Comment by einhornimmond** [comment]
It seems with api key user can only subscribed, unsubscribed and manuel tags can be removed.
So if we like to save the status if user has subscribed to newsletter or not, we must save it in our db.

**Comment by ulfgebhardt** [comment]
It is essential that the user selects the language on register so we send him newsletter in the proper language. It will not be obvious that the user can change his Newsletter language Settings in the wallet and he will not be informed to do so in the newsletter. Therefore it is very important that he gets the right language on the first time.

Furthermore: On register the language menu is coupled with UI, later on it is not. The user can change the UI language separately from the newsletter language.

Furthermore: we should consider to switch the default language to German since that is the main audience at this moment.
