### ISSUE TITLE
🚀 [Feature] Elopage RefID

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#186]
## :rocket: Feature

There is a reference ID which is generated via an wordpress addon and relates to an Elopage RefID.
This ID must be saved for a user upon registration.
Furthermore the user is offered to register a elopage account from the menu in the client.
When the user navigates to the elopage register this RefID must be transmitted.

Do we identify if a user has an account on elopage and advertise it differently? ("Mitglied im Mitglieder bereich werden" vs "Mitgliederbereich")

We need more details how this process is currently working (@einhornimmond @BerndHueckstaedt ) and how it is intended to work (@BerndHueckstaedt ) - also whats the role and functioning of this ominous wordpress plugin (@BerndHueckstaedt )?

**Comment by BerndHueckstaedt** [comment]
Ein geworbener User kommt über einen Ref-Link zur Registration-Page
Der ref-Link kann über Wordpress kommen oder direkt vom werbenden "Publisher".

Die Pid (Publisher-Id) kann sowohl über einen URL-Parameter "pid=12345" übermittelt werden, als auch über einen leicht merkbaren Link: community.com/12345
