### ISSUE TITLE
💬 [Question] Elopage-Registration

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#187]
## :speech_balloon: Question

Clarify which kind of registration feature of Elopage can be used for the new registration process:
- Prio1: does Elopage support a registration-api?
  - if yes, describe the supported API, how we can use it and which data can or must be transferred for a full qualified registration
- Prio2: does Elopage support a registration-deeplink?
  - if yes, describe the link pattern, how we can use it and which data can or must be transferred for a full qualified registration

In both cases a support for the recommandation id (PID) is mandatory

**Comment by ulfgebhardt** [comment]
This is relevant when implementing the register process and therefore should be evaluated during this time. Maybe answer some of the questions and create followup issues

**Comment by Elweyn** [comment]
I looked again at the Elopage API, and if I am not mistaken we can registrate publishers like this:

```JavaScript
var data = JSON.stringify({
  "key": "2619fbae455e294cb5cf3c8d51d248b5",
  "secret": "xYLxwnzZpCfYAHCoU2zo_g7EugyVgsuqmzGC6myS8_2R5ZrUMg1qz6erbyyjSu",
  "affiliate_program_id": "139"
});

var config = {
  method: 'post',
  url: 'http://api.elopage.com/api/publishers//enroll',
  headers: { 
    'cache-control': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW\'', 
    'Content-Type': 'application/json'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```
I just can't understand how elopage knows enough to enroll a new publisher with this informations...
Since Key: Is our key, Secret is also and affiliate_program_id is also something we define.

**Comment by ulfgebhardt** [comment]
I think this call is to enroll an existing publisher to an course/program but I could be mistaken.

**Comment by einhornimmond** [comment]
From the parameters I would assume that you can only enable or enroll a publisher program for one of your product.

**Comment by Elweyn** [comment]
OK so I will contact the Elopage support to know how we could do this.

**Comment by Elweyn** [comment]
The response of the Elopage Support was as followed:
"Yes you could send a deeplink to our registration or I could ask the tech-team to know if we have a API."
The response of this was that they don't have an API but use a third Party where we would pay each time we want to import a new user in elopage.

So the other option would be to make a deeplink:
```
https://elopage.com/s/gradido/registration-de/payment?locale=de&prid=111&pid=&firstName=&lastName=&email=
```

**Comment by BerndHueckstaedt** [comment]
This is a good way to invite the user to register their membership area and get some advantages.

The correct product to be linked to is "basis-de" for german language. So the correct link is:

https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&pid=&firstName=&lastName=&email=

Since we do not have an english product yet, we must use for english the german link too, and change is later.

**Comment by ulfgebhardt** [comment]
- [x] Wie wird die pid von gradido.net nach gdd1.gradido.net (wallet) übertragen? durch einen parameter (geht bei jeder Seite auf gradido.net - cookie wird gesetzt)
  - [x] Wenn eine pid vorhanden ist wird dann ein cookie gesetzt? ja auf gradido.net
  - [x] Wenn ein pid vorhanden ist, wird dann auf die registrierungsseite weitergeleitet? (nein, der nutzer kann auf der Seite browsen, pid sollte auch so auf der Wallet heißen - so ist es kommuniziert)
  - [x] Das ist nicht hinreichend für mich
    - Hey kann ich dir 5 Gradido für das nette Gespräch und den Kaffee geben?
    - Gerne, ich hab aber kein account
    - Registrier doch einfach einen, dauert 1minute, einfach auf gradido.net gehen
    - Ok, mach ich schnell
    - ... 
    - Bin fertig, was jetzt?
    - 1. Optimal
      - Einfach oben auf code scannen klicken und dann hier einscanne
      - ** Handy wird über Tisch geschoben, einscannen **
      - Ok cool, das hat funktioniert, hab jetzt 5 Gradido
    - 2. Suboptimal
      - Einfach oben auf auf QR code clicken und mich mal kurz einscannen lassen
      - ** Handy wird hingehalten, einscannen **
    - Was mach ich jetzt damit?
    - ... 
    (Solange nicht im Mitglieder Bereich registriert geht das! -> pid per Überweisung übermitteln)
    (Mitglieder Bereich manuel (vorname, name, email und pid für elopage) -> incentive, nicht erzwingen)
    (Elopage spenden mechanik untersuchen) (first come first serve nicht konkurrenz, annahme direkt)
    -> spenden link
    -> geld anfordern per username
    -> pid in überweisung nicht notwendig, pid ist an nutzer gebunden
    -> user wird erst mit vorhanden pid auf mitglieder bereich intensiviert
    -> elopage bietet mitgliederbreich als handyapp
  - [-] Es bräuchte eine Dankes-Funktion, die es erlaubt eine Menge an Gradido an einen QR code zu hängen, derjenige der ihn einscannt bekommt diese Gradido (eine art prebuchung) (Wie wird sowas in der Blockchain abgebildet) -> Issue (Dank Scheck, einzulösen bis)
  - [x] Wie übergeben wir die pid an elopage?
  - [x] Wie kann ich links erzeugen wie gradido.net/ulf oder gradido.net/ulfderwanderprediger die de pid implizit beinhalten? (gradido link eher auf community ebene, user hat eine pid hinterlegt)
  - [x] Fall 2 - Wie funktioniert das im einzelnen technisch?
  - [x] Was ist der unteschied zwischen Fall 2 Link und Fall 2 QR-Code?
  - [x] "Nach der Registrierung wird dem neuen User ein Start-Kapital von 100 GDD" warum passiert das nicht in Fall 2 Link? Das erste mal, dass ich davon höre was ist das genaue Konzept, wie wird das in der Blockchain abgebildet? In wieweit ist das vereinbar mit dem Gradido-Konzept? Inwieweit ist das mit der 20GDD pro Stunde vereinbar? (nein, machen wir nicht (vorläufig)) (anwendungsfall: gradido rabatt beim friseur) (Aktivität für 5 Stunden dokumentieren, die unbürokratisch bestätigt werden bei Registrierung)
  - [x] Was ist mit dem Fall, wenn der Nutzer sich zuerst auf Elopage registriert?
  - [x] Oder besser - er hat sich zuvor bereits bei Elopage registriert und Schritt 2 & 3 der alten Registrierung nicht abgeschlossen? (pid & parentpid, parentid bereits vorhanden, pid noch nicht da, ein großer call für das) (muss getestset werden - was ist wenn kein wallet, aber eine elopage vorhanden ist)
  - [x] Wie verhält sich das mit den bestehenden Konten? (parent id von gradido akademie als standart)
  
  ----
  
@BerndHueckstaedt @Elweyn @clauspeterhuebner  Das sind meine Notizen bzgl der Elopage Registrierung. Viele Dinge sind mittlerweile geklärt oder stellen sich anderst dar. Beim lesen ist mir nochmal klar geworden, dass der `pid` in diesem Text auf gradido.net gesetzt wird. Der Auftrag eines Werbenden ist folglich ausschließlich den Nutzer auf Gradido.net zu bewegen. Sollte er sich nun registrieren muss der pid mitgetragen werden.
- Ist das so realistisch?
- Gibt es eine API um den pid von unserer Anwendung aus Wordpress zu holen?
- Wie handeln wir den pid auf unserer Seite? Auch mit einem Cookie? Oder liegt der auf Seiten von Wordpress?
- Oder ist sichergestellt, dass immer ein pid via URL bei uns ankommt und wir müssen uns darum gar nicht kümmern?

**Comment by BerndHueckstaedt** [comment]
Wir haben inzwischen vereinbart, dass die pid überall per URL-Parameter ‚pid=‘ angehängt und weitergereicht wird.

Das gilt für:
Unsere Software z.B. Registrierungsseite
Wordpress
Marktplatz
Elopage

Das ist auch leicht zu lernen für die User: "Häng an deinen Registrierungslink oder einen beliebigen Beitrag auf unserer Webseite ?pid=12345 an".
