### ISSUE TITLE
🚀 [Feature] Copy the Link Text as well

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#1885]
## 🚀 Feature
Have another button to copy both, the link and the text. This way, when pasting the link in an email the user does not have to repeat the text.

Fields to copy:
 * Amount 
 * Sender
 *  Text 
 *  Link 
 *  Expired Date

**Comment by BerndHueckstaedt** [comment]
Text in the language of the sender.  No plus sign in front of the amount, Gradido written out.
Example:
https://gdd.gradido.net/redeem/15234561e08244d018173271774 - <user> sends you 50 Gradido. - "Text text jgdjhgjh djjgd jhjhgjhg hjhgj jhgjhgjhg " - To credit your Gradido, click on the link! It is valid until dd.mm.yyyy.

Text  in der Sprache des Absenders.  Kein Pluszeichen vor dem Betrag, Gradido ausgeschrieben.
Beispiel:
https://gdd.gradido.net/redeem/15234561e08244d018173271774  – <User> sendet dir 50 Gradido. – "Text text  jgdjhgjh djjgd jhjhgjhg hjhgj jhgjhgjhg " – Um deine Gradido gutzuschreiben, klicke auf den Link! Er ist gültig bis dd.mm.yyyy.

**Comment by mahula** [comment]
> Text in the language of the sender. No plus sign in front of the amount, Gradido written out. Example: https://gdd.gradido.net/redeem/15234561e08244d018173271774 - sends you 50 Gradido. - "Text text jgdjhgjh djjgd jhjhgjhg hjhgj jhgjhgjhg " - To credit your Gradido, click on the link! It is valid until dd.mm.yyyy.
> 
> Text in der Sprache des Absenders. Kein Pluszeichen vor dem Betrag, Gradido ausgeschrieben. Beispiel: https://gdd.gradido.net/redeem/15234561e08244d018173271774 – sendet dir 50 Gradido. – "Text text jgdjhgjh djjgd jhjhgjhg hjhgj jhgjhgjhg " – Um deine Gradido gutzuschreiben, klicke auf den Link! Er ist gültig bis dd.mm.yyyy.

Should the other button take place here - in the transactions dropdown in the transaction overview? 
![Bildschirmfoto 2022-07-04 11:52:24](https://user-images.githubusercontent.com/3883288/177131769-87dfcf05-471c-4b18-a42b-36cc2d8ea365.png)
