### ISSUE TITLE
🐛 [Bug] only expired links are not listed 

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1898]
## 🐛 Bugreport
only expired links are not listed 

mir ist eben beim testen auf stage2 folgendes aufgefallen. 
nur, abgelaufene links sind nicht sichtbar. erst wenn ich wieder einen wirklichen aktiven link erstelle.
das problem besteht auch in der 1.8.3 .. ich habe es auf stage1 augecheckt. 

https://user-images.githubusercontent.com/1324583/168221253-08248749-7478-458c-91c2-e5098b4228a8.mp4

**Comment by Mogge** [comment]
@ogerly Still an issue? I think we did something about that ...

**Comment by ulfgebhardt** [comment]
This is still a problem.

**Comment by Mogge** [comment]
The virtual transaction for the amount of GDD to hold available for the transaction links is 0 id there are no active transaction links. Therefore it is not delivered to the wallet. I have no good idea how to solve this and think that it is not important

**Comment by ogerly** [comment]
done
