### ISSUE TITLE
🐛 [Bug] 404 Page shortly visible when navigating to localhost

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#191]
## :bug: Bugreport

404 Page shortly visible when navigating to localhost

**Comment by Mogge** [comment]
Steps to reproduce:
  * login
  * go to `http://localhost:8080/overview`
  * remove `overview` in the URL manually and press enter
  * you see the 404 error

OR
  * go to login page
  * remove `login` in URL manually and press enter
  * you see the 404 error
