### ISSUE TITLE
🔧 [Refactor] Jump back to the redemption link if timeout occurs

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1947]
## 🔧 Refactor ticket

**The problem:**
If you were logged in and have exceeded the time limit and click on a redemption link, you are logged out and land on the normal login page with the corresponding error messages. There you log in and that's it. In other words, you are no longer asked whether you want to redeem the link.

Only when you switch to the other application (e.g. e-mail or Telegram) and click on the redemption link again can you have the amount credited.

**The reason:**
At this point, no user is known to the system because the time has expired. There is no way to attribute this to any user. The system has no decision-making power at this moment and cannot access the store. 

When logging in again, the system should know that it came last from a redemption link and redirect a user to this link after logging in again. 

**Task:**
Find a way to make the system understand that it came from a redemption link and redirect a user back to it.  

_____________________________________________

**Das Problem:**
Wenn man eingeloggt war und die Zeit überschritten ist und auf einen Einlöse-Link klickt, wird man ausgeloggt und landet mit den entsprechenden Fehlermeldungen auf der normalen Anmeldeseite. Dort meldet man sich an, und das war’s. D. h. man wird nicht mehr gefragt, ob man den Link einlösen will.

Erst wenn man jetzt nochmal in die andere Applikation wechselt (z. B. E-Mail oder Telegram) und nochmal auf den Einlöse-Link klickt, kann man sich den Betrag gutschreiben lassen.

**Der Grund:**
An diesem Punkt ist dem System kein User bekannt weil die Zeit abgelaufen ist. Es besteht keine Möglichkeit irgendeinem User dieses zuzuschreiben. Das System hat in diesem Moment keine Entscheidungsgewalt und kann auch nicht auf den Store zugreifen. 

Beim erneuten einloggen müsste dem System bekannt sein das es als letztes von einem Einlöselink kam und einen User zu diesem Link nach einer Anmeldung wieder hinleiten. 

**Aufgabe:**
Finde einen Weg dem System klar zumachen das es von einem Einlöselink kam und leite einen User dahin zurück.

**Comment by BerndHueckstaedt** [comment]
One possibility would be to ensure that the above case does not occur at all by automatically logging out after the session expires and redirecting to a corresponding page: "You have been successfully logged out of the system". Then the two ugly error messages would also be omitted.

Eine Möglichkeit wäre, dafür zu sorgen, dass der o.g. Fall gar nicht ert eintritt, indem man nach Ablauf der Session automatisch ausloggt und auf eine entsprechende Seite umleitet: "Du wurdest erfolgreich vom System abgemeldet". Dann würden auch die beiden hässlichen Fehlermeldungen wegfallen.

**Comment by BerndHueckstaedt** [comment]
Before that, the credit union shows a countdown: "Are you still there? If you are inactive, you will be logged out in xx seconds for security reasons."

Die Volksbank zeigt davor noch einen Countdown: "Bist du noch da? Bei Inaktivität wirst du aus Sicherheitsgründen in xx Sekunden abgemeldet."

**Comment by mahula** [comment]
This has been solved in https://github.com/gradido/gradido/issues/2069.
