### ISSUE TITLE
🐛 [Bug] Login takes 2.5s

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#195]
## :bug: Bugreport
The login takes too long.

### Steps to reproduce the behavior
1. Login
2. See how long it takes
5. Profit

### Expected behavior
Faster, at max half a second. Alternative: Show a spinner.

**Comment by ulfgebhardt** [comment]
I think this is because of the store - the store mechanic seems to be delayed. I am not sure why

**Comment by einhornimmond** [comment]
This is a use of my speedLog.txt.
There you can find the time of AuthenticatedEncryptionCreateKeyTask.
That's where the cpu intense hashing (https://github.com/gradido/gradido/issues/135) take place, what's make login lasting so long. 
In login_server/src/cpp/Crypto/SecretKeyCryptography.cpp line 9 are the default parameter for it:
- opslimit 
- memlimit
- algo

With them the running time can be adjusted, more about you can find here: 
https://libsodium.gitbook.io/doc/password_hashing/default_phf#key-derivation

Currently I have adjusted the parameter such way that the function needs under 0.5s on production vps. 
It has a single core cpu operating on 2,4 GHz and 1 GB Ram.  

It seems running in docker, it needs more time. 1.33s - 1.38s I have in my speed log on my CPU which can reach nearly 5 GHz. 
So for docker we must readjust the values. My plan for future is to put it in config ore calculate automatic on target system. 
But for that I must save the parameter with the saved keys to able to reencrypt with new params if they changed.

**Comment by einhornimmond** [comment]
Maybe it has todo with debug and release build.

**Comment by ulfgebhardt** [comment]
In general the approach to make brute force harder by cpu intensive hashing functions seems flawed. We can just build in a counter of retries and eforce the time of retry between those. What is the benefit of having a cpu intensive hashing function on our server?

**Comment by einhornimmond** [comment]
First of all it used by ethereum and I think also from other crypto currencies for saving the private keys in the wallet.
It is a second line of defence, if someone is able to steal the db data or maybe a db backup. 
I think especially for backup data it could be important. 
It is a difference if an attacker needs 0,5 sec per passwort try especially if user choose simple and easy passwords like 1234 or  a simple words without numbers or he can try 622 million passwords per second (example with sha256 hash on Radeon HD5830).

**Comment by ulfgebhardt** [comment]
This is not an issue - at least not till we have a substantial user load
