### ISSUE TITLE
🐛 [Bug] Registration with Safari Does Not Transaport Transaction Link Code To Login

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#1992]
## 🐛 Bugreport
As @Tirokk reported, the mechanism to transport the link code after set password to the login page is not working.
File: `frontend/src/pages/ResetPassword.vue`, line 92:
```
            this.messageButtonLinktTo = `/login/${this.$route.params.code}`
```

**Comment by Tirokk** [comment]
I checked this again for:

- transaktion links
- contribution links

I used this links to register a new user in both cases and all works fine.
