### ISSUE TITLE
🚀 [Feature] Contribution Resolver

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#2000]
## 🚀 Feature
Create a contribution resolver with:
 * `createContribution`
 * `listContributions`
 * `updateContribution`
 * `deleteContribution` (soft delete)

for a logged in user.

Test the methods.
Seed some contributions

**Comment by Elweyn** [comment]
- createContribution can be send by a user that is logged in mutation:
```
mutation {
  createContribution(amount:"200", memo:"Test contribution 2", creationDate:"2022-06-27")
}
```

**Comment by Mogge** [comment]
All tasks done! Great work!
