### ISSUE TITLE
🚀 [Feature] Basic framework template

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2003]
## 🚀 Feature
Create a template framework that behaves properly for D-P-M. Without content. Please pay attention to the background image. 

The bootstrap style must always be changed beforehand. Please do this in an extra file that rewrites the basic bootstrap. (frontend/src/assets/scss/gradido-template.scss) 
Maybe an extra file for the wallet area after login. 
When we switch off our design, the application must still be executable! 
The extra file can also be used later by the decentralised communities as a style template for their own customised design. 

# desktop
![Main-Page-Epic-Issues-desktop](https://user-images.githubusercontent.com/1324583/175915041-62af57c5-0a41-46e2-a460-486c9af73805.png)

# pad
![Main-Page-Epic-Issues-pad](https://user-images.githubusercontent.com/1324583/175914995-557be933-02b6-4e0a-99fa-6dc605f945ad.png)

# mobil
![Main-Page-Epic-Issues-mobil](https://user-images.githubusercontent.com/1324583/175915017-554992ea-ce68-4df1-9974-4e86f75a6119.png)

**Comment by Hardy-Hart-am-Start** [comment]
![Gradidi_bg_1](https://user-images.githubusercontent.com/102550886/175955893-132d15ee-d67c-4970-860d-86ed0c8efff8.jpg)
![Hintergrund_Farbe](https://user-images.githubusercontent.com/102550886/175955900-a8097ed0-50ff-43fa-9cf5-6d77942d2084.png)
![Hintergrund_Icon](https://user-images.githubusercontent.com/102550886/175955903-d2f7670f-d90e-43be-adba-71f7bfa777cb.png)
![test](https://user-images.githubusercontent.com/102550886/175955906-9ed83bbf-757c-43f3-9271-0b2bb8f33d8c.svg)

**Comment by ogerly** [comment]
done
