### ISSUE TITLE
🚀 [Feature] Meta data from the backend for link previews

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2014]
## 🚀 Feature

In order to enable corresponding link previews for certain dynamic pages, e.g. transaction links and redeem links, metadata provided on the server side is required.

The issues #1885 and #1884 are related to this topic.

**Comment by Elweyn** [comment]
Hi, I just found something that could help resolve the meta tag problems with internationalization:
https://stackoverflow.com/questions/56120701/translate-meta-tags-in-vue-router-with-i18n#56164111

**Comment by ogerly** [comment]
no elaboration, too old and will be deleted
