### ISSUE TITLE
🚀 [Feature] Save Locale in Database

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#209]
## :rocket: Feature
Save the language the user chooses in the database. Load this language on login and set the locale in the frontend accordingly. 

### User Problem
The user must change the language every time logging in when not using the default language.

**Comment by ulfgebhardt** [comment]
There is this feature on the server. You can at least set the language: https://github.com/gradido/gradido/blob/master/docu/login_server.api.md#update-user-data

**Comment by einhornimmond** [comment]
- with unsecureLogin language will be returned as additional user field
- with loginViaEmailVerificationCode language will be returned as additional user field
- with updateUserInfos you can update language in login-server db
- with getUserInfos you can retrieve language of user

**Comment by ulfgebhardt** [comment]
This is only frontend now

**Comment by ulfgebhardt** [comment]
#208
