### ISSUE TITLE
🐛 [Bug] Console Errors When Entering Admin Interface

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#2096]
## 🐛 Bugreport
When entering the admin interface, there is an error on the console:
`TypeError: this.$store.state.creation is null`

**Comment by jjimenezgarcia** [comment]
forget prior mention, error on typing

**Comment by jjimenezgarcia** [comment]
I am not getting such an error
![imagen](https://user-images.githubusercontent.com/99907380/200559118-21921905-4972-4342-bd3f-e2d1c126374b.png)

Please, provide more info of where are you exactly encountering the error.
Thanks!

**Comment by ulfgebhardt** [comment]
1. Go in with seeded data
2. login with peter lustig
3. Login to Admin
4. Red stuff appears

**Comment by Elweyn** [comment]
@Mogge I don't think that we still have this problem!
We get another error:
```
[WDS] Disconnected!
```
But I don't know how we would could fix this.

IMO we can close this ticket

**Comment by Mogge** [comment]
No issue anymore
