### ISSUE TITLE
🐛 [Bug] Typo im Dialog "Meine Beiträge"

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2109]
## 🐛 Bugreport

Im Dialog "Meine Beiträge" wird ein Text ausgegeben, in dem noch zwei Typos enthalten sind:

IST:  Es wird bald an dieser Stelle die Möglichkeit geben das ein Dialog zwischen Moderatoren und dir stattfinden kann. Solltest du jetzt Probleme haben bitte nimm Kontakt mit dem Support auf. 
SOLL: Es wird bald an dieser Stelle die Möglichkeit geben, dass ein Dialog zwischen Moderatoren und dir stattfinden kann. Solltest du jetzt Probleme haben, bitte nimm Kontakt mit dem Support auf. 

Die Stellen im Detail:
IST:     ...geben das ...
SOLL: ...geben, dass...
  und
IST:     ...Probleme haben bitte...
SOLL: ...Probleme haben, bitte...

**Comment by ogerly** [comment]
this dialogue text has been removed as there are now contribution messages.
