### ISSUE TITLE
🚀 [Feature] Support Bearer Header & JWT

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#213]
## :rocket: Feature

We currently have two options to signal our login status:
- via cookie
- via session_id as parameter

While the cookie is a standard way of doing authentication it is limited to one domain. Either load common external sources and use the external domain or use a different mechanic to authenticate. With the login server intended to be shared between different communities each with their own domain, the cookie mechanic does not seem to be a good choice.

The session_id is quite simplistic and pollutes the parameters of a call.

Suggestion: Use of bearer headers. Its the standard, it does not pollute the parameters and is basically invisible for the application. Its easy to write a hook for every call  Furthermore the standard of asymetric encryption would be good - namely JWT (Jason Web Token)

See:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
- Especially: https://tools.ietf.org/html/rfc6750
- For JWT: https://jwt.io/introduction

**Comment by einhornimmond** [comment]
It seems Poco has JWT package, so it should be relative easy to use JWT on Login-Server side. 
https://pocoproject.org/docs/Poco.JWT.html

**Comment by einhornimmond** [comment]
We have decided to put JWT direct in the new Apollo based Community-Server into Action.

**Comment by einhornimmond** [comment]
We can close this issue, isn't it? 
Or should I implement Json Web Token in Login-Server?
