### ISSUE TITLE
🔧 [Refactor] always delete token

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2146]
## 🔧 Refactor ticket

When redeeming a redeem link, it still happens in some cases that the token is not deleted in all cases after a session expires ... so that there can be problems with redeeming a redeem link. 

please check everything again and also observe the behaviour of browser tabs that are open in the background. 
or if you are in the admin area as admin / moderator ... then the session expiration window should basically come up as well. 

when is the token not deleted?  

Beim einlösen eines redeem links kommt es noch in einigen fällen dazu das nach ablauf einer session nicht in allen fällen der token gelöscht wird .. so das es zu problemen mit dem einlösen eines redeemlinks kommen kann. 

bitte alles nochmal genau prüfen und auch das verhalten von im hintergrund offenen browser-tabs beobachten. 
oder wenn man als admin / moderator im adminbereich ist .. dann sollte das session ablauf fenster im grunde auch kommen. 

wann wird der token nicht gelöscht?

**Comment by Mogge** [comment]
I do not think that the problem is a token, that is not deleted. We have to verify the login on redeeming a link

**Comment by Elweyn** [comment]
@Mogge @ogerly 
Is this ticket steel open or can we close it?

**Comment by Mogge** [comment]
This is done
