### ISSUE TITLE
test if correct HTML tag 

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2169]
You could test if correct HTML tag is used my mocking the store and in one test set it to a moderator and in the other set it to a usual user and expect the correct HTML tag for each case …

[admin/src/components/ContributionMessages/slots/ContributionMessagesListItem.spec.js](https://github.com/gradido/gradido/pull/2164/files/1f0bea76c5b71156afecfc66df91a3588577eeac#diff-7475d4bb48e8b4910b2cd544ff990a765fbdec485cfa6a54b04c4c80bed444de)

 ```
   it('props.message.default', () => {
      expect(wrapper.vm.$options.props.message.default.call()).toEqual({})
    })
  })
```

Just a suggestion …

_Originally posted by @Tirokk in https://github.com/gradido/gradido/pull/2164#discussion_r959397193_

**Comment by Mogge** [comment]
The snippet tests the function that is called for the default value of a property. E.g.
```
props: {
  property: { type: object, default: () => { foo: true, bar: false } }
 }
```
And then the test:
```
  it('props.message.default', () => {
     expect(wrapper.vm.$options.props.property.default.call()).toEqual({ foo: true, bar: false })
   })
```
What is this issue for?
