### ISSUE TITLE
🐛 [Bug] check if there is a rounding problem 

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2173]
## 🐛 Bugreport
Please check if there is a rounding problem when the last day of a month is selected for creation but it is already posted in the ninth month. it looks like a whole day is swallowed. 
the problem occurred with a user who selected 31.07 for creation but it was deducted from august. 

the problem cannot be isolated, it must be investigated in detail.

**Comment by Mogge** [comment]
Can we close this? @ogerly
The analysis of @clauspeterhuebner shows the origin of the problem. #2179

**Comment by ogerly** [comment]
done
