### ISSUE TITLE
🐛 [Bug] wrong month for contribution near turn of month

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2179]
## 🐛 Bugreport

if a user creates a contribution near the turn of month there seams to be an error in the correct month assigment.
Details and examples will be collected:

- Example from production:
@Developer @Bernd von Gradido Ihr Lieben, ich wollte für August schöpfen und habe festgestellt, dass ich nur noch 160 GDD schöpfen kann, obwohl es eigentlich noch 900 hätten sein müssen. Wie im Screenshot zu sehen, wurden die GDD für Juli für August gutgeschrieben und für September habe ich noch gar nichts eingereicht und da wird mir angezeigt, dass ich noch 740 GDD einreichen kann.

![Screenshot_2022-09-01_001442](https://user-images.githubusercontent.com/1324583/195763813-0e1e32fb-8372-4263-9a5f-caedc1252ee0.jpg)

![Screenshot_2022-09-01_001746](https://user-images.githubusercontent.com/1324583/195763853-08e8047d-d263-45ea-898b-f67d99c2c9ab.jpg)

**Comment by Elweyn** [comment]
Lokal getestet am 06.09.22:
- Keine möglichkeit neuer Contribution zu erstellen wenn 1000 GDD Geschöpft
- Keine möglichkeit Contribution zu erstellen von 350 GDD wenn 300 GDD offen
- Frage kann dass was mit den Automatischen Schöpfung per Link passieren?

**Comment by Mogge** [comment]
#1435

**Comment by clauspeterhuebner** [comment]
Der Vergleich der Daten in der Datenbank zu der Anzeige im Admin-Interface zeigt m.E. ein Vertauschen der Datumswerte einer Contribution:
![Manuela-gradido_vertauschteContributionDates_1](https://user-images.githubusercontent.com/86960882/188680898-5ddacfa5-191a-494d-b48c-abac2d1ad549.png)
hier sind die beiden Datumswerte created_at=2022-08-11 20:50:41.000 und contribution_date=2022-07-31 00:00:00.000 wie sie in der Datenbank stehen.

in der Anzeige sind diese beiden Werte "gerundet" und passen fachlich nicht zu den gespeicherten Daten.
![Manuela-gradido_vertauschteContributionDates_2](https://user-images.githubusercontent.com/86960882/188681816-7ed01ca1-c167-48ec-99c5-bc9bd536d9a6.png)

Man sieht aber auch, dass die Rundung des Datums created_at=2022-08-11 20:50:41.000 auf den 12.08.2022 nicht korrekt ist, da es bei der UTC mit +2 genaugenommen erst 11.08.2022 22:50:41 ist

**Comment by clauspeterhuebner** [comment]
Nach einem lokalen Test mit folgenden Bedingungen:
- PROD-Daten in lokaler DB
- Anwendung von master-Branch lokal hochgefahren
- Systemzeit auf 01.09.2022 0:20 gesetzt
- im Server-Log ist zu erkennen, dass der Server den 31.08.2022 23:20 hat
- neue Contribution mit ContributionDate=01.09.2022 mit 100GDD erstellen, läuft aber auf Fehler
![lokal-test_am_01-09-2022_00-32_createContribution_fuer_09-2022_3](https://user-images.githubusercontent.com/86960882/188739198-84b0d88a-1bad-4a54-976c-c484c0f88572.png)

Zusätzlich Logausgaben im Code von resolver/utils/creations.ts zeigen folgende Diskrepanz:
![lokal-test_am_01-09-2022_00-32_createContribution_fuer_09-2022_2](https://user-images.githubusercontent.com/86960882/188739759-22872f6a-5d8c-47ce-b3fd-cf883d8be3d0.png)
- die Contribution wird mit contribution_date=01.09.2022 an BE übergeben
- zur Ermittlung des korrekten Schöpfungsmonats erfolgt ein Aufruf von getCreationIndex mit month=8
- die Ermittlung der drei letzten Schöpfungsmonate erfolgt mit dem Aufruf von getCreationMonths und liefert das Array [6, 7, 8]
- im Code wird aber bei der Ermittlung des Index dann eine falsche Abfrage mit (el === month + 1) sprich welcher Wert im Array entspricht dem month + 1 also 9 => Fehler????
![lokal-test_am_01-09-2022_00-32_createContribution_fuer_09-2022_4](https://user-images.githubusercontent.com/86960882/188741916-4a8eb1ef-f3ee-4655-b984-d178444cfa82.png)

**Comment by Elweyn** [comment]
Moin @clauspeterhuebner,
zum ersten Punkt mit createdAt und contributionDate verstehe ich nicht ganz wieso createdAt "gerundet" wird aber contributionDate nicht stehe ich auf dem Schlauch den im Frontend: admin/src/components/CreationTransactionList.vue werden beide gleich eingebunden:
```JavaScript
        {
          key: 'creationDate',
          label: this.$t('transactionlist.date'),
          formatter: (value, key, item) => {
            return this.$d(new Date(value)) // 2022-08-11 20:50:41.000 => 2022-08-12
          },
        },
        {
          key: 'balanceDate',
          label: this.$t('transactionlist.balanceDate'),
          formatter: (value, key, item) => {
            return this.$d(new Date(value)) // 2022-07-31 00:00:00.000 => 2022-07-31
          },
        },
```

Zum zweiten Punkt ist es aber noch seltsammer... Damit dürfte das Schöpfen für den aktuellen Monat nie funktioniert haben... Aber der Date des Server ist im Screenshot noch auf 2022-08-31T23:29:44.505, damit dürfte noch nicht für September geschöpft werden...
