### ISSUE TITLE
🐛 [Bug] No Menu Icon in Mobile View

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#218]
## :bug: Bugreport

![image](https://user-images.githubusercontent.com/15882241/115576876-3320a800-a2c4-11eb-99f8-18e11f52afb4.png)

### Steps to reproduce the behavior
1. Switch to mobile view
2. Open the menu

### Expected behavior
Something that does not look broken.

**Comment by ogerly** [comment]
in dem branch #221  ist alles ok .. die bilder und icons werden angezeigt bei mir. 

besteht das problem noch bei euch  ?

**Comment by einhornimmond** [comment]
no

**Comment by ulfgebhardt** [comment]
Ist nun auch bei moriz behoben mit der neuen nginx configuration
