### ISSUE TITLE
💬 [Question] User Data

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#22]
## :speech_balloon: Question

What data is already stored?

![image](https://user-images.githubusercontent.com/1238238/109234841-bc3bc700-77cc-11eb-87f3-2330f7f9162b.png)

What data is not yet stored?

What data we do not want to store?

What data we do want to store additonal?

**Comment by einhornimmond** [comment]
Username is stored in stage2 version but not used, not implemented in stage0-1
first_name, last_name and email are stored on login-server.

On community-server profile-description and profile-img is stored, but I haven't yet written api functions for it. 

I don't know if we need Address data, that's a question for Bernd.

**Comment by ulfgebhardt** [comment]
I do not find any docu yet to query all that data - Alex will need to upload new user images, show user images, address, nickname, maybe a description? Else the interface he uses will need lot of stipping out stuff - and user profile picture will massively cripple the UI if we do not have that

**Comment by einhornimmond** [comment]
So he uses currently existing code?
And I haven't an interface yet? I can write the interface so it match his code. 
What interface his code is expecting?

**Comment by ulfgebhardt** [comment]
its just important that all the api calls are documented so alex can implement them easily
Whats expected can be seen in the screenshot above - the structure of that api call and if its multiple is up to you ;)

**Comment by einhornimmond** [comment]
I comment api calls, while I implementing them. 
So what is commented is implemented and vice versa.

**Comment by ogerly** [comment]
- firstname 
- lastname
- password 
- userbild
- email
- about me
- location

**Comment by ulfgebhardt** [comment]
Closing this for now, we need more specific issues since @ogerly has reworked the userinterface completely and removed e.g. the profile picture.
