### ISSUE TITLE
🔧 [Refactor] Delete query when redeeming the Redeem link

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2203]
## 🔧 Refactor ticket

When redeeming the Redeem link, there is still one too many prompts.
You click on Redeem and are then asked whether you want to redeem. This query can be omitted.

![Bildschirmfoto vom 2022-09-15 10-55-04](https://user-images.githubusercontent.com/1324583/190361270-cb59447c-bded-4a12-9f7e-dfbec02e6460.png)

**Comment by Mogge** [comment]
Please check the following behavior as well. A transaction/contribution link is not valid. You login, errors are toasted but you are still asked to redeem the link.
