### ISSUE TITLE
🔧 [Refactor] [Frontend] Use The Apollo Client Correctly – Remove Created Vue Hooks

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2286]
## 🔧 Refactor ticket

Use the apollo client correctly - remove created vue hooks

Apparently we do not use the apollo client correctly. Implement its usage correctly and correct all affected components.

@Mogge Please describe and refactor this issue properly and provide examples & documentation for this

### Issues

relates #1872

**Comment by Mogge** [comment]
This could be useful: https://github.com/gradido/gradido/pull/2330

**Comment by clauspeterhuebner** [comment]
associated PR #2341 still closed -> ticket will be closed too.
