### ISSUE TITLE
🐛 [Bug] Golden Border on Frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2288]
## 🐛 Bugreport

We have a golden border at the bottom of our Webpage - it is ugly!

@BerndHueckstaedt Is this intended?

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/49f18bf0-c484-4eae-80f8-004003f4d584)

**Comment by BerndHueckstaedt** [comment]
Yes, its intended, an is beautiful!
