### ISSUE TITLE
🐛 [Bug] Cannot confirm contribution

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2298]
## 🐛 Bugreport

Trying to confirm an users transaction results in this error:
![image](https://user-images.githubusercontent.com/1238238/197576997-5d591993-ac0a-4e41-9030-a9fbd468a295.png)

The user has enough GDD to be created available
![image](https://user-images.githubusercontent.com/1238238/197576337-0be5f623-ed7d-4c56-a76d-71d3993999b7.png)

User has alot of small contributions confirm
![image](https://user-images.githubusercontent.com/1238238/197576595-8dbe9542-4b14-4821-ac05-6ab2170f0f78.png)

**Comment by ulfgebhardt** [comment]
Manually adding up the users contributions for October comes up as 1110 which implies (if added up correctly) there is a problem with the admin interface's value displayed and a major business logic flaw

**Comment by Mogge** [comment]
I assume this is because of changing the month of a contribution is buggy. Therefore we switched it off

**Comment by Mogge** [comment]
We have to talk about this issue

**Comment by Mogge** [comment]
There is a possible fix included in #2229 but instead of merging it, we try to fix more issues within the same PR. Welcome back

**Comment by Mogge** [comment]
On master (wrong data):
![image](https://user-images.githubusercontent.com/15882241/197765964-ca514612-1c45-49b6-97c6-4e49ab5095c8.png)

With fix in #2217 (correct data):
![image](https://user-images.githubusercontent.com/15882241/197765540-91f0e536-785d-4f1e-a591-c90805654ebe.png)
