### ISSUE TITLE
🔧 [Refactor] [Admin] Statistics on its own Page

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2317]
## 🔧 Refactor ticket

Have the statistics on its own page to reduce initial load.

![image](https://user-images.githubusercontent.com/1238238/199203761-00a5f5fe-3a27-4b4b-8f5d-7113e87e99ea.png)

**Comment by mahula** [comment]
Will  accessing this separate statistics page be restricted by user roles (e.g. only for admins), @ulfgebhardt?
