### ISSUE TITLE
🔧 [Refactor] Generate Protobuf on compile

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#232]
## :zap: Refactor ticket

Generate Protobuf on compile. There is Protobuf compiles somewhere in the repository. Those should be generated, maybe cached in an external image to improve performance

### Motive

Have a single source of truth

**Comment by einhornimmond** [comment]
Currently in my build_and_run.sh script it will be checked if protobuf files were already parsed and only if they do not exist they will be parsed. So currently they should be parsed only once, by the first docker-compose up call.

**Comment by ulfgebhardt** [comment]
But you checked in a compiled version didn't you? Like those header files with long hash values in it?

**Comment by einhornimmond** [comment]
On Community Server the compiled protobuf files are checked in, in login-server not. 
I have thought about checking in the compiled protobuf files also in login-server to make compiling more easy and to have the same approach. 
The Login-Server Pages (HTTP-Interface) are also checked in compiled. 
But now I understand you don't like the compiled files checked in?

Not easy for community-server. I must use the login-server docker container to parse th community server protobuf files and after that call in community-server composer dump-autoload
I don't know if it is even possible to do that.

**Comment by ulfgebhardt** [comment]
Yes true, it is common practice to leave out binary files when committing. On the other hand we do have a compiling issue due to time. In the long run we should always have one source of truth ( having the compiled protobuffs checked in with the community server is violating this while at the same time makes it impossible for the common developer to understand if the files are up to date when comparing to the uncompiled sources).
And yes the same applies for the html pages. You can see how it clutters PRs with just generated changes which could be left out. When rebasing Stage2 this was a nightmare since the source line numbers are commented in those compiled html files.

Its both not very important tho, don't waste your time with it now - the html stuff will be left out of the login server at a given point and will solve itself, while the protobuff stuff comes into play when we try to go decentralised.

**Comment by einhornimmond** [comment]
There not binary files. They are quellcode files.
Okay than the parsed proto files in Login-Server stay out of git.

**Comment by einhornimmond** [comment]
And for community-server I will think about a solution.. at some point.

**Comment by ulfgebhardt** [comment]
obsolete
