### ISSUE TITLE
🚀 [Feature] Gradido is free - worldwide on startpage slider

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2343]
## 🚀 Feature

Gradido is free - worldwide on startpage slider

`Gradido ist weltweit kostenfrei.`

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/d031787f-7030-4bb0-adc4-5ebeaaf1829b)
![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/7f374040-5ca5-411c-92d5-add574619042)

There is a key `isFree` in the locales existing showing the sentence on logout:
`Der entsprechende Locale-Key isFree kommt momentan nur in frontend/src/components/LinkInformations/RedeemLoggedOut.vue vor.`

Must be shown on
- [x] logout
- [x] login
- [x] register

**Comment by mahula** [comment]
I will fix that.
