### ISSUE TITLE
🚀 [Feature] User story "User Authentication - forgot / reset password"

### ISSUE THREAD

**Issue by mahula** [gradido/gradido#2352]
### The user story "User Authentication - forgot / reset password"
This is the user story for changing your Gradido passwort from the sign in page.

The story will live written in [Gherkin](https://cucumber.io/docs/gherkin/) in the Cypress e2e feature file `User.Authentication.ForgotPassword.feature`, which will be the human readable test scenario.

---

Feature: User Authentication - forgot / reset password
  As a user
  I want the option to reset my password from the sign in page
  
  Background:
    Given the following "users" are in the database:
      | email            | password | name          |
      | bibi@bloxberg.de | Aa12345_ | Bibi Bloxberg |

  Scenario: Reset password from sign in page successfully
    Given the browser navigates to page "/login"
    And the user navigates to the forgot password page
    When the user enters the e-mail address "bibi@bloxberg.de"
    And the user submits the e-mail form
    Then the user receives am e-mail containing the password reset link
    When the user opens the password reset link in the browser
    And the user enters the password "12345Aa_"
    And the user repeats the password "12345Aa_"
    And the user submits the password form
    And the user clicks the sign in button
    Then the user submits the credentials "bibi@bloxberg.de" "Aa12345_"
    And the user cannot login
    But the user submits the credentials "bibi@bloxberg.de" "12345Aa_"
    And the user is logged in with username "Bibi Bloxberg"

**Comment by ulfgebhardt** [comment]
Looks good, requires #1257
