### ISSUE TITLE
🐛 [Bug] Investigate Hyperswarm connection trouble in docker

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2358]
## 🐛 Bugreport

Investigate Hyperswarm connection trouble in docker.

Apparently there is trouble when running the hyperswarm in docker - it makes the maria db to lose connection.

Investigate and figure out how to solve. Does this problem occur on all maschines?

Background: the hyperswarm dht PR is now part of the master - by setting `GRADIDO_HUB` as dht-topic in the config you should find stage1.

**Comment by mahula** [comment]
Did a specific error occur, when running it in Docker or did id just not work, @Mogge?
