### ISSUE TITLE
💥 [DevOps] Testplan

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#236]
## 💥 DevOps ticket

Create a Testplan which can be reused until we have cypress fullstack tests. This Testplan can be used to generate userstories as well.

- What we test?
- How we test?
- When we test?
- How much effort does each test have

**Comment by ulfgebhardt** [comment]
# Testplan

1. Test with staging data
2. Test with live data on staging

## New Frontend
1. Test Login time on staging, still 2.5 seconds?
2. Send gdd - is the input sensitive to the `,` and `.` separators depending on the language?
3. login, logout
4. login, logout, login when this user just got gdd he never seen before - balance correct
5. password rest works
6. send gdd, balance correct, everything immediately updated?
7. balance & transactions is correct when loggin in & out two users

## Old Frontend
1. Register still works?
2. Schöpfen funktioniert noch?
3. User suchen funktioniert
4. Balance & transactions correct?
5. Old Frontend same as new Frontend regarding balance & transactions?

@einhornimmond @Mogge

**Comment by einhornimmond** [comment]
Reloading (F5) page of frontend failed with 404 Not Found

**Comment by einhornimmond** [comment]
GDT is to short, is has only 2 decimals and need therefore only divided by 100.

**Comment by einhornimmond** [comment]
In new frontend you can send yourself gradidos, than the transaction is display two times. 
![send_myself](https://user-images.githubusercontent.com/67117805/116874981-76f7a380-ac1a-11eb-929a-b85f8ff03868.png)

**Comment by einhornimmond** [comment]
Wrong email is sended with password reset

**Comment by ulfgebhardt** [comment]
Altes frontend muss gestestet werden!
