### ISSUE TITLE
💥 [DevOps][Backend] Have `yarn locales --fix` In The Backend

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#2366]
## 💥 DevOps ticket

Have `yarn locales --fix` In The Backend.
See `package.json` in frontend.

… if PR #2163 is merged.

**Comment by mahula** [comment]
Is this issue about having [this line](https://github.com/gradido/gradido/blob/9879df4eb53438073140ab4e303558cdce3099ed/frontend/package.json#L14) in [the backend's package.json](https://github.com/gradido/gradido/blob/master/backend/package.json) file?
