### ISSUE TITLE
💥 [DevOps] Test with live data

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#237]
## 💥 DevOps ticket

Do a test with live data before deploy so we can be pretty sure things don't break after.

- [ ] Users without the new group_id can recieve gradidos?

**Comment by einhornimmond** [comment]
no, but I will migrate the db manually and set group_id for every user. 
In Register default user_group will be set. If this line is present in Login-Server config 
```ini 
dev.default_group = <group alias>
```
