### ISSUE TITLE
🚀 [Feature] [Federation] Allow federation to persist its secret via Config

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2375]
## 🚀 Feature

Allow federation to persist its secret via Config

- [x] Allow the federation (keypair) to be initialized with a seed
- [x] This seed must be configureable via config
- [x] If the value is not set, select a random seed (does the library do this if you provide `keyPair=null`?).

**Comment by clauspeterhuebner** [comment]
if the seed property is not set, the dht-lib creates the keypair on random base.
with a given seed, it seems the lib creates crazzy keys with less cryptographics. 
the key looks like the following pattern:
- PublicKey: <publickey>
- SecretKey: <seed>xxxxxx<publickey>
- the SecretKey is filled up with xxxx to a fix size for sodium.crypto_box_SEEDBYTES
