### ISSUE TITLE
💬 [Question] Why `CONFIG.EMAIL_TEST_MODUS` Has Boolean `true` Or String `'false'` As Possible Values/Types?

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#2387]
## 💬 Question

Why `CONFIG.EMAIL_TEST_MODUS` has boolean value `true` or string `'false'` as possible values/types?

This seems odd to me!

**Comment by ulfgebhardt** [comment]
Where do you read this? This **was** as bug - is it still?
