### ISSUE TITLE
🐛 [Bug] &&-Notation in unit tests doesn't work in jest

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2408]
## 🐛 Bugreport

&&-Notation in unit tests doesn't work in jest.

Having this: `expect(...) && expect(...) && expect(..)` will only check the last expression not the rest.

- [ ] Find out how to do such tests properly
- [ ] Fix all tests having this issue

**Comment by Mogge** [comment]
What is this? See for example: `backend/src/emails/sendEmailVariants.test.ts`

**Comment by Mogge** [comment]
If you want it in top level do:
```
expect(...)
expect(...)
expect(...)
```
If one expect fails, all the whole test fails.

**Comment by Mogge** [comment]
Please close. This is trivial
