### ISSUE TITLE
💬 [Question] Investigate how the frontend behaves on non-existent users

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2434]
## 💬 Question

Investigate how the frontend behaves on non-existent users.

What if you have a transaction from or to user 103, 218 or 90 (production data)?

- related #2430

**Comment by Mogge** [comment]
* Forntend renders the transaction
 * Error is shown on console
 * linked user name is empty

**Comment by ulfgebhardt** [comment]
This is acceptable behaviour
