### ISSUE TITLE
🐛 [Bug] New Send-EMail not working

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2438]
## 🐛 Bugreport

New Send-EMail not working

![image](https://user-images.githubusercontent.com/1238238/204480722-16709592-6aef-49d6-b437-a718c1ade2fe.png)

When registering a already registered email the newly defined email cannot be sent - instead the users is presented with a graphql error.

Hint: Most likely the pug files are not copied to the build folder and therefore cannot be found when running in production environment

**Comment by Tirokk** [comment]
Solved by #2398
