### ISSUE TITLE
🚀 [Feature] Backend implementation of usecase 'capturing alias'

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2446]
## 🚀 Feature

Base on the concept
https://github.com/gradido/gradido/blob/master/docu/Concepts/BusinessRequirements/UC_Set_UserAlias.md
the backend has to be adapted for these requirements.

- [x] introduce alias on saving user #2727 
- [x] introduce alias-uniqueness validation
- [x] extend search-user with alias
- [x] #2951
- [x] ...

**Comment by Elweyn** [comment]
Has been done by @Mogge
