### ISSUE TITLE
🐛 [Bug] Design bugfixes

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2462]
## 🐛 Bugreport

- https://stage3.gradido.net/overview
  - [x] :question: GDD nicht aktiv
  - [x] Member anzahl nicht aligned mit GDD-Kontostand
  - [ ] Button keine Funktion
  - [ ] Bernd Text
  - [x] Frage: Nutzerzahl woher?
- Last Transactions - RightSide
  - [x] Überschrift nicht bündig
  - [x] 3-Punkte keine funktion
  - [x] Name klickbar (sende Formular)
  - [x] Abstand 
- https://stage3.gradido.net/send
  - [x] Senden Radio-Auswahl Text & Radio Button nicht mittig
  - [x] Check now ohne funktion
  - [x] hr/schatten unten -> weg
  - [x] :question: klick auf die Radiofläche bedient nicht die radiobox
- https://stage3.gradido.net/transactions
  - [x] Decay since last transaction text nicht mittig >>> NEIN, ist wie Stylevorlage
  - [ ] Color schema for avatars (first letter to ascii modulo bootstrap varriants map to varriants without success), success color only for creations
- https://stage3.gradido.net/gdt
  - [x] Datum nicht korrekt formatiert
  - [x] (opt) Box beim aufklappen Abstand nach unten zu groß
- Menü
  - [x] Members Menu Title -> "Schöpfen"
  - [x] Klick auf Members/Schöpfen führt micht immer zu meinen Schöpfungen anstatt auf einreichen 
- https://stage3.gradido.net/community
  - [x] Wenn eine Antwort vom User verlangt wird. und ich das formular  https://stage3.gradido.net/community#edit neu lade, er aber weil eine frage offen ist auf  https://stage3.gradido.net/community#my springt, dies richtig als #hash übergeben werden. 
  - [ ] :question: Amount unklar was gemeint ist -> GDD (20GDD/Stunde)
  - [x] Schatten/Strich seitlich
  - [x] Schatten/Strich unterhalb in erster Box "My contributions"
  - [x] Grauer Balken bei "Moderator Chat" zu groß und nicht bündig außen
  - [x] Click auf Moderator Chat öffnet box nicht
  - [x] Box ist im leeren Zustand zu öffnen
  - [x] öffnen/schließen Verhalten ist unklar -> klick auf leere flächen öffnet box, auf etxt kein Öffnen
  - [x] Abstand zwischen Contributions zu groß
  - [x] Infobox kann weggext werden -> raus, Feature scheint nciht komplett implementiert??!
- https://stage3.gradido.net/information
  - [x] zu viuele boxen, mach nur eine
  - [x] keine Striche/Schatten wenn mehrere boxen
- https://stage3.gradido.net/settings
  - [x] (feat) Community show community name
  - [ ] alter style auf neuen umstellen - gerne hier spaaren und das schieben
  - [x] avatar nicht gleichfarbig

- Mobile
  - [x] Menü nicht öffenbar aufgrund palme
  - [ ] Startseite zu großer Abstand zwischen box & Konto infos
  - [ ] Startseite button zweizeilig
  - [x] :question: Background bruch oberhalb der content box
  - [ ] Kein Avatar im Menü
  - [ ] Beim senden sind die Radioboxen nicht gleichgroß
  - [ ] GDD&GDT Avatare oval
  - [ ] GDD&GDT Aufklapp pfeil außerhalb der box
  - [ ] GDD&GDT Pagination zu groß für minimalen Mobile view(zeige nicht Seite 2 an, sondern nur Pfeile und aktuelle Seite) >>> @mahula pleace
  - [ ] Informations -> keinen außenabstand der boxen

**Comment by ogerly** [comment]
https://stage3.gradido.net/overview
 GDD nicht aktiv
 
 Wie ist das gemeint ?

**Comment by ogerly** [comment]
::  Klick auf Members/Schöpfen führt micht immer zu meinen Schöpfungen anstatt auf einreichen

Wenn eine Antwort von einem User Erwartet wird, dann landet man immer auf der Übersichtsseite der von user eingereichten contributions ..

**Comment by ogerly** [comment]
https://stage3.gradido.net/overview

- [ ]  Button keine Funktion
- [ ] Bernd Text
 Bernd ist in Kenntniss gesetzt. 

![overview-news-kasten](https://user-images.githubusercontent.com/1324583/207620753-7da8e58c-29d0-4ca8-913b-0bfbb0272155.png)

**Comment by ulfgebhardt** [comment]
> https://stage3.gradido.net/overview GDD nicht aktiv
> 
> Wie ist das gemeint ?

![image](https://user-images.githubusercontent.com/1238238/207651746-1acff24f-ca32-4a62-ac02-ca0d4cff789d.png)

The `GDD` box is grey and so is the outline of the box. While this makes sense when switching between GDD and GDT it seems illogical here.

**Comment by ulfgebhardt** [comment]
@ogerly 
- [ ] :question: Amount unklar was gemeint ist -> GDD (20GDD/Stunde)

It is unclear what is ment with `amount` - what does the user have to input here. It can be guessed out of the context on the page (GDD). We can neglect this for now since we want to switch to hours soon.

**Comment by ulfgebhardt** [comment]
@ogerly 

- [ ] :question: Background bruch oberhalb der content box

No longer a problem.

**Comment by ogerly** [comment]
> > https://stage3.gradido.net/overview GDD nicht aktiv
> > Wie ist das gemeint ?
> 
> ![image](https://user-images.githubusercontent.com/1238238/207651746-1acff24f-ca32-4a62-ac02-ca0d4cff789d.png)
> 
> The `GDD` box is grey as if inactive and so is the outline of the box. While this makes sense when switching between GDD and GDT it seems illogical here.

done

**Comment by ulfgebhardt** [comment]
Clsoing in favor of #2469
