### ISSUE TITLE
🔧 [Refactor] [Admin] Remove multiple creation

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2498]
## 🔧 Refactor ticket

Remove multiple creation

![image](https://user-images.githubusercontent.com/1238238/209604317-2093bff3-78ca-469a-8c3c-54da0550c2d5.png)

The functionality is not needed anymore.

Remove the frontend and backend parts of this feature.

**Comment by Elweyn** [comment]
Has been merge!
