### ISSUE TITLE
🚀 [Feature] [Admin] Link Contributionlist to User search

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2499]
## 🚀 Feature

Link Contributionlist to User search

![image](https://user-images.githubusercontent.com/1238238/209604711-b10fd72a-617e-4d9d-907a-77f35781c0e6.png)

When clicking the email of the user in the contribution list the admin interface must navigate to the user search with the search-term being that email.

![image](https://user-images.githubusercontent.com/1238238/209604792-c0cf7312-82e9-4ccd-9087-98b75ec4aa64.png)

**Comment by mahula** [comment]
Is this a duplicate of #2373 ?

**Comment by ulfgebhardt** [comment]
Yes good catch @mahula

**Comment by ulfgebhardt** [comment]
clsoing in favor of #2373
