### ISSUE TITLE
💥 [DevOps] Implement Github Workflows

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#25]
## 💥 DevOps ticket

- [x] Test workfolow
- [x] Test docker builds
- [x] Upload docker file artifacts
- [ ] Test Gradido Node within docker
- [x] Frontend test: `yarn lint`

See: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/.github/workflows/test.yml

**Comment by einhornimmond** [comment]
I cannot fix the error in the github action test workflow.
It needs the community server and login server code, but both repositorys are private so the workflow runner from github cannot access them.

**Comment by ulfgebhardt** [comment]
leaving out gradido node test and migrating it to a refactor ticket
