### ISSUE TITLE
🐛 [Bug] [Design] Leaves are over the user symbol

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2513]
## 🐛 Bugreport

Leaves are over the user symbol covering it:
![image](https://user-images.githubusercontent.com/1238238/211194403-0cc4c18f-5512-499d-928d-e992b0d0f73a.png)

**Comment by ogerly** [comment]
![Bildschirmfoto vom 2023-01-09 11-41-39](https://user-images.githubusercontent.com/1324583/211291425-52076e6d-5170-4760-9bcf-85bad07390f3.png)
