### ISSUE TITLE
🐛 [Bug] To long text in send form has send button still enabled

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2590]
## 🐛 Bugreport

Validation works, but button is active when text is too long.

Offenbar ist der Button aktiv markiert, auch wenn die Nachricht zu lang ist.
![image](https://user-images.githubusercontent.com/1238238/214015311-c6d0600a-3c2e-40bc-b20d-338bd5096f1b.png)
![image](https://user-images.githubusercontent.com/1238238/214015661-85c736fd-025b-41c8-a21a-d0026b2dfb39.png)

**Comment by BerndHueckstaedt** [comment]
Vielleicht kann man unter dem Eingabefeld (wo auch die Fehlermeldungen kommen) einen Zähler anbringen, der die Zeichen von 250 auf 0 herunter zählt? Wenn ja, dann auch beim Schöpfen anbringen.
