### ISSUE TITLE
🐛 [Bug] [Mobile] Buttons on Contributions not properly aligned

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2597]
## 🐛 Bugreport

Buttons on Contributions not properly aligned

![image](https://user-images.githubusercontent.com/1238238/214066093-d00684f8-3e6b-4200-b37a-028438bb587b.png)
`Auf Mobile sind beim Schöpfungeinreichen die Buttons "Abbrechen" und "Senden" nicht nebeneinander.`

**Comment by ogerly** [comment]
![image](https://user-images.githubusercontent.com/1324583/216001510-4f097592-4f00-46ee-824e-7fea9e954125.png)

the problem should be solved
