### ISSUE TITLE
🌟 [EPIC] 1.5.0 Register

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#264]
## 🌟 EPIC

The registration process will be changed:
1. The Registration-Button on the gradido Wordpress pages invokes the registration process of the gradido application
    - the link use a general registration URL without any community dependency
    - the link can be expanded by an optionally PID parameter
2. In the gradido application the registration process starts with a community selection page
   - each community instance knows each community registered in the community network (see community creation process)
   - the user selects the community he wants to register as a new member
   - the optional PID parameter can be checked per request against the GDT-Server, which will know each GDT-Member of Elopage, if the PID is missing or wrong the default PID of the 'Förderkreis' has to be used for the registration process
   - the next button redirects to the registration process of the selected community instance including the mandatory PID
3. the registration process on the community instance
   - equates to the existing registration page of the gradido application
   - the process steps equates to the existing steps of the current registration process
   - at the end of the registration process the registration on elopage will be triggered including the PID parameter
4. Elopage registration Process
   - registration API or Deep-Link
   - transfering the captured data of the new member to Elopage
5. Member collection and PID correlation in the GDT-Server
   - cyclic request the registered Elopage member inkluding the PID
   - store all necessary data of an Elopage member including the PID with the GDT-account
   - offer a service API to request for a PID-check as publisher id

**Comment by Elweyn** [comment]
@ulfgebhardt, @clauspeterhuebner,
my thoughts on the 2nd point is the following:
- In case I make an own community and I invite someone on my community I would not want them to go somewhere else so it would not be nice to have this implemented in the gradido registration.
- In case they go on gradido.net (wordpress) and want to registrate to gradido then their is a page that allows the user to choose a community
This would keep the registration process simple.
