### ISSUE TITLE
🔧 [Refactor] Desktop Sub Menu

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#2685]
## 🔧 Refactor ticket
- Active color "#F5F5F5 inactive color "#383838"
- Max width 400px
- Replace icons
- Font-family: Work Sans Semi Bold;
- Shadow background

___

- Aktive color „#F5F5F5 inaktive color „#383838“
- Max width 400px
- Icons ersetzen
- Font-family: Work Sans Semi Bold;
- Schatten hinterlegen

![image](https://user-images.githubusercontent.com/1324583/217484281-387b54cc-915c-454a-811c-05e1a1641a29.png)

**Comment by BerndHueckstaedt** [comment]
In dem Info-Feld reicht der Text:
"Du hast die maximale Anzahl an Stunden für diese Auswahl erreicht."
Den Satz "Bitte wähle eine andere Tätigkeit" bitte weglassen. Der macht vorerst keinen Sinn, solange wir keine verschiedenen Tätigkeiten oder Kategorien auswählen können.

**Comment by BerndHueckstaedt** [comment]
Beim Zeitraum: klappt da ein Date-Picker auf, mit dem ich den Zeitraum einstellen kann? Das wäre wichtig, um das System als Tagebuch führen zu können, wie wir im letzten Meeting besprochen haben.
