### ISSUE TITLE
🐛 [Bug] Federation database error on CI

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2778]
## 🐛 Bugreport

The reason for this is unclear but should be investigated

![image](https://user-images.githubusercontent.com/1238238/223156590-c48511c6-ac68-4fdc-940b-e58f85f493c6.png)

https://github.com/gradido/gradido/actions/runs/4343613935/jobs/7585975206

**Comment by clauspeterhuebner** [comment]
The reason for DUPLICATE-KEY ERROR is a conflict with the database key-constrain:
UNIQUE KEY public_api_key (public_key, api_version)

One reason for such a conflict is an existing communities-entry with a publicKey based on creation with a dedicated seed and an other community instance creates its publicKey with the same seed. As soon as they connect and exchange their community-federation data per dht-node this conflict will occur.
