### ISSUE TITLE
🐛 [Bug] Staging Server 404 on reload

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#280]
## 🐛 Bugreport

The staging Server produces a 404 when reloading the new frontend. Please correct the nginx configuration on the staging server according to those changes here:
- https://github.com/gradido/gradido/blob/master/nginx/nginx.conf#L60
- https://github.com/gradido/gradido/pull/253/files

This is not needed in production mode:
- https://github.com/gradido/gradido/blob/master/nginx/nginx.conf#L72

![image](https://user-images.githubusercontent.com/1238238/117040186-e8fae600-ad09-11eb-9ac8-b6dd28d7c6a7.png)

**Comment by einhornimmond** [comment]
As I told you I parse the frontend on staging with 
npm run build and serve the dist folder. 
With your change I need an additional server running on port 3000. 
What exactly do this server what nginx cannot do?

**Comment by ulfgebhardt** [comment]
I changed more stuff. Obviously you do not want to run an express server but just serve the files. The express server does just that, it just serves the files. But the nginx config on staging does somehow not recognize the subpaths `.../vue/path`. They are not correctly resolved which is a nginx problem I believe.
If you give me access I can look into this. Do we have the nginx config somewhere checked in?

Express just serving static files: https://github.com/gradido/gradido/blob/master/frontend/run/server.js#L10

**Comment by einhornimmond** [comment]
You find the file on staging.gradido.net if you login via ssh at:
 /etc/nginx/sites-available/stage1

Okay, I have found a solution. 
Adding this line
```
try_files $uri $uri/ /index.html = 404;
```
do the trick.
The whole block no looks like this: 
```
location /vue {
          alias /var/www/html/gradido/frontend/dist;
          index index.html;

          location ~* \.(png)$ {
            expires 39d;
          }
          try_files $uri $uri/ /index.html = 404;
        }
```

**Comment by ulfgebhardt** [comment]
This is deployed in staging right? At least it seems to work there now. @einhornimmond

**Comment by einhornimmond** [comment]
Yes, of course.
