### ISSUE TITLE
🚀 [Feature] KlickTipp: definition of requirements to set and remove tags

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#2834]
## 🚀 Feature: Describe in this issue the business requirements and processes

Gradido-Konto zu Klick-Tipp API
-------------------------------------
*Felder angelegt:*
1. Last: Wann wurde die Aktion das letzte Mal ausgeführt?
- [ ] 'GDD last invited': Datum & Zeit    
       entspricht EVENT_TRANSACTION_SEND_REDEEM
- [ ] Datum & Zeit: 'GDD last sent'        
       entspricht EVENT_TRANSACTION_SEND
- [ ] Datum & Zeit: 'GDD last received'  
       entspricht EVENT_TRANSACTION_RECEIVE
- [ ] Datum & Zeit: 'GDD last created'    
       entspricht EVENT_ADMIN_CONTRIBUTION_CONFIRM oder EVENT_CONTRIBUTION_CREATE

- [ ] Datum & Zeit: GDD last login
- [ ] Datum & Zeit: GDD date of registration

2. Count: Wie oft wurde die Aktion ausgeführt?
- [ ] Zahlenfeld: 'GDD invited count  total'
- [ ] Zahlenfeld: 'GDD invited count 30 days'
- [ ] Datum & Zeit: 'GDD sent count 30 days'
- [ ] Datum & Zeit: 'GDD received count 30 days'
- [ ] Datum & Zeit: 'GDD created  count 30 days'

3. URL der Home-Community z.B. https://gdd.gradido.net
- [ ] GDD Home-Community URL

*Aktionen bei Aktivität*
- [ ] Datum & Zeit  setzen wenn 
  - [ ] Transaktion gesendet wurde:  'GDD last sent'
  - [ ] Transaktion empfangen wurde: 'GDD last received'
  - [ ] Contribution eingereicht wurde: 'GDD last created'
  - [ ] Neuer User erfolgreich per Link eingeladen

Anzahl, wie oft die betreffende Aktion ausgeführt wurde in das betreffende Feld setzen

Alle weitere Logik macht Bernd bei Klick-Tipp

previous conception and requirements
--------------------------------------
As community manager I would like that the Application sends a call to KlickTipp to set a tag on users:
> - seit x Tagen noch keinen Gemeinwohl-Beitrag eingereicht
> - seit x Tagen  noch keine Transaktion (Überweisung o.ä.) getätigt
> - Tags entziehen, wenn es nicht mehr zutrifft.
> Dann könnte man die inaktiven User einladen, aktiv zu werden.
>
> Man könnte auch übemitteln, wenn jemand (k)einen anderen User geworben hat,  etc.
>
> oder alternativ Felder bei Klick-Tipp befüllen:
> Anzahl und Gesamtbetrag der Schöpfungen in den letzten 30 Tagen
> Anzahl und Gesamtbetrag der ausgehenden Transaktionen in den letzten 30 Tagen
> Anzahl der geworbenen neuen User in den letzten 10, 30, 90 Tagen

> Die Fragen die sich stellen sind: 
> - wie beziehungsweisse wann werden die calls zum hinzufügen der tags angestoßen: 
>   - Über einen cron-job
>   - Über Benutzer interaction im admin interface? Wenn ja würde als folge Frage "wo soll die funktion in der UI hin?" entstehen.
>   - ??? Andere Lösungen ???
> - welche tags sollen angelegt werden
> - entfernen der tags müsste dann auch definieren welche tags entfernt werden sollen

**Comment by BerndHueckstaedt** [comment]
Auf Anraten von Ulf habe ich weitere Felder hinzugefügt: 

Datum & Zeit: GDD last login

 Datum & Zeit: GDD date of registration

 GDD Home-Community URL z.B. https://gdd.gradido.net
 
Das URL-Feld brauchen wir für den Link zum Gradido-Konto, da wir ja bald mehrere Communities haben.
Mit "Home-Community" ist die Haupt-Community gemeint, wenn ein User mehreren Communities angehört. An dem Konzept arbeite ich mit Claus-Peter.

**Comment by Elweyn** [comment]
transfered to: https://github.com/gradido/gradido/issues/2857
