### ISSUE TITLE
🚀 [Feature] KlickTipp: implement queries to get the requested klicktipp info from database

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2877]
## 🚀 Feature Query KlickTipp data

- [ ] implement the necessary queries to get the data for the requested klicktipp data
      * first start searching the requested data out of the event-protocoll table
      * if the event-protokoll table will not contain all requested information try to find the data in other tables
- [ ] encapsulate the queries in a dao-class, because the trigger to start the query is still open 
- [ ] implement the invokation of the klicktipp-connector for data-exchange 
       * klicktipp-connector is implemented in #2876

**Comment by clauspeterhuebner** [comment]
* CONTRIBUTION_CREATE
        <pre>
          select 
             e.type, e.created_at, uc.email, u.first_name, u.last_name, u.gradido_id  
           from 
              gradido_community.events e, 
              gradido_community.user_contacts uc, 
              gradido_community.users u  
           where 
              e.affected_user_id = uc.user_id AND 
              e.affected_user_id = u.id AND
              e.type  = 'CONTRIBUTION_CREATE' 
           group by e.affected_user_id 
           order by e.created_at DESC;>
        </pre>

**Comment by Elweyn** [comment]
SQL WIP:
```SQL
select 
  e.type, e.created_at, uc.email, u.first_name, u.last_name, u.gradido_id  
from 
  gradido_community.events e, 
  gradido_community.user_contacts uc, 
  gradido_community.users u  
where 
  e.affected_user_id = uc.user_id AND 
  uc.user_id = u.id AND
  e.type  IN ('CONTRIBUTION_CREATE', '', '', '', '', '')
group by e.affected_user_id, e.type
order by e.created_at DESC;
```
