### ISSUE TITLE
🐛 [Bug] Alignement of the numbers in the transactionlist are not reader friendly

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#289]
## 🐛 Bugreport

Alignement of the numbers in the transactionlist are not reader friendly:

![image](https://user-images.githubusercontent.com/1238238/117043702-dda9b980-ad0d-11eb-95c8-cb483a2957f2.png)

As seen here the GDD values jump depending on how long the string is. I assume this is because of alignment center. Numbers must be orientated to the right.

**Comment by Mogge** [comment]
fixed
