### ISSUE TITLE
🐛 [Bug] incorrect errormessage for wrong contribution-link

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2897]
## 🐛 Bugreport

Wenn man eine beliebige Nummer beim Contribution-Link eingibt, bekommt man folgende Anzeige.

![grafik.png](https://images.zenhubusercontent.com/60e2e8f737203322bcf41bd9/164f4643-92da-4d9e-a7ec-4c176183a0e4)

## 🤖 Todo
- [ ] Default text "redeem 123,45" to "The link is unknown."
- [ ] Redeem button disabled in default

**Comment by ogerly** [comment]
I can't find this anywhere in the code ? 
somehow it must come from the backend. 
also there i only found one thing that "could not find any".
@Mogge ?
