### ISSUE TITLE
🐛 [Bug] GDD not correctly rounded

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#290]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/1238238/117044239-82c49200-ad0e-11eb-8880-c5be7f6eb69e.png)

There is 3 digits after the separator. It should be only 2. It is required to use `floor()` since the user can never spend more then he has.

**Comment by einhornimmond** [comment]
fixed with commit https://github.com/gradido/gradido/pull/273/commits/b10886a8d359c1fd2b701722113674705c40d440
in pr #273
