### ISSUE TITLE
🐛 [Bug] Login Server crashed during our test

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#293]
## 🐛 Bugreport

The login server crashed during our testing.
- [ ] Find out why
- [ ] Fix it
- [ ] How can we stresstest this in the next test?
- [ ] Does it automatically restart?
- [ ] Any other errors during our test?

**Comment by einhornimmond** [comment]
It was an exception thrown after community-server don't answer json request like expected. 
No it is currently not automatic restarting, I had some tries in past with systemd but I didn't work yet. 
I miss the log files. 
Stresstest: Let Login-Server make json request calls and get random not valid jsons as answear.

**Comment by einhornimmond** [comment]
Oh I found errors in an email from test, actually the error messages trigger an error because of missing variable I not longer use.

**Comment by ulfgebhardt** [comment]
@einhornimmond is this fixed?

**Comment by einhornimmond** [comment]
I don't know. 
But it is possible. I think the error occured in connection with pending tasks which I don't longer use.
Now the client must wait until the transaction is finished, and no extra thread is used and therefore no multithtread issuse can occure.
