### ISSUE TITLE
🔧 [Refactor] ListTransaction must return the balance

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#294]
## 🔧 Refactor ticket

ListTransaction must return the balance:

We get a listTransaction result after a successful sendGDD, but we don't get the balance. The backend need to deliver this in order for the frontend to display the correct new balance. Furthermore it would be wise to deliver the balance on every listTransaction call as well, since the amount you have displayed in the menu as balance might differ (because you sent or received new GDD) from your transaction list.

**Comment by einhornimmond** [comment]
fixed with commit: https://github.com/gradido/gradido/pull/273/commits/b10886a8d359c1fd2b701722113674705c40d440
in PR #273
