### ISSUE TITLE
🌟 [RM-Epic] Calculator GradidoRabatt and Course

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#2942]
## 🚀 Feature

So ungefähr könnte der Rechner aussehen 
Die Funktionen sind etwas anders, als bei einem normalen Taschenrechner, eher wie bei einer Ladenkasse:
Multiplizieren und Teilen funktioniert normal
z.B. 5 Stück x 20 Werteinheiten sind 100
Bei + wird die Multiplikation ausgerechnet und eine Zwischensumme gebildet.
Bei = kommt die Gesamtsumme und die Anzeige auf dem rechnen Bild.
Bei C wird alles gelöscht.
Die kleine Rücktaste macht was sie soll.
Ein Klick (und gedrückt halten) kopiert den GDD-Betrag in die Zwischenablage oder generiert später mal einen QR-Code, wenn wir Anforderungslinks / QR-Codes haben. 

![grafik](https://user-images.githubusercontent.com/86960882/231797138-5a849931-1ff0-425d-a21b-38569150a849.png)

GradidoRabatt und Kurs werden permanent gespeichert.
Sie können durch einen Klick auf den Wert geändert werden.
Evtl. können wir auch den Kurs automatisch ausrechnen bzw. aus einer Tabelle auslesen.
Dann brauchen wir nur ein zusätzliches Datenbank-Feld für den GradidoRabatt. 

**Ergebnisse aus dem Architektur-Mtg 18.04.2023**
-----------------------------------------------------------------
- der GDD-Calculator kann im 1. Schritt als eigenständige Anwendung erstellt werden
- es sind zwei grundsätzlich verschiedene Modi angedacht:
  - Modus: Kassen-Bon
  - Modus: Währungstausch
- allgemeine Anforderungen:
  - (Mehrzeilige-, scrollbare) Anzeige analog eines Kassen-Bon
    - 1.Zeile gibt Eingabe 1:1 wieder und scrollt ggf. nach rechts
    - falls wie in Anwendungsszenario-2 Rabatte auf Einzelprodukte gegeben wird, erfolgt in der 1. Zeile die Ausgabe des Prozentsatzes in Klammer nach dem Produktpreis. Beispiel:
      5 x 1,20 (20%) + 3 x 1,99 (5%) + 10 x 0,60 =
    - nach Eingabe der =-Taste erfolgt die Berechnung mit Ausgabe der Beträge unterhalb der Eingabe-Zeile
    - folgendes wird berechnet und aussagekräftig formatiert ausgegeben ( sieh auch Beispiele unten):
      - Euro-Summe
      - Gradido-Rabatt  (wenn der User per Überweisung mit GDD bezahlt)
      - Euro-Betrag       (der vom User zu zahlende Euro-Betrag)
      - DankBar-Betrag (falls der User mit DankBar bezahlt der kalkulierte Tagespreis mit GDB aus dem aktuellen Jahr)
  - Ziffern-Tasten 0-9 und Komma-Taste
  - Operator-Tasten für + und x und =
  - C-Taste zum Löschen der Anzeige und der berechneten Werte
  - Rück-Taste zum schrittweise Löschen des letzten eingegebenen Wertes
  - Taste für Modus-Wechsel
  - 4 belegbare Tasten
    - per lokaler Konfiguration frei konfigurierbar mit Natürlichen Zahlen
    - konfigurierte Werten werden lokal gespeichert
    - im Modus Kassen-Bon mit %-Werten (z.B. 5%, 10%, 15%, 20%)
    - im Modus Währungstausch mit Gradido-DankBar-Werten (z.B. 2GDB, 5GDB, 10GDB, 20GDB)
  - beim Wechseln des Modus wird die Anzeige und alle Beträge vollständig zurückgesetzt
- **Kassen-Bon Modus**
  - **Anwendungsszenario-1**: Der Händler bietet auf alles einen 20%-Gradido-Rabatt.
Der User ist am 18.04.2023 auf einem Markt und möchte Gemüse kaufen. Er sucht sich 5 Tomaten, 3 Gurken und 10 Kartoffeln aus. Der User als auch der Händler möchten nun den Geamtbetrag in Euro ermitteln. Tomatenpreis 1,20€ pro Stück, Gurkenpreis 1,99€ pro Stück, Kartoffelpreis 0,60€ pro Stück. Dies wird wie üblich eingetippt: 
  5 x 1,20 + 3 x 1,99 + 10 x 0,60 =
  - Mit Tippen der =-Taste erfolgt die Ergebnis-Berechnung gemäß  6€ + 5,97€ + 6 € = 17,97€
    -  Euro-Summe:         17,97€
    -  Beträge:
      - Gradido-Rabatt =   0,00 GDD
      - Euro-Betrag =      17,97 €
      - DankBar-Betrag =  0,00 GDB
  - Mit Tippen einer der 4 %-Tasten (hier Beispiel 20%) erfolgt die Betrags-Berechnung
    -  Euro-Summe:        17,97 €
    -  Beträge:
      - Gradido-Rabatt =   3,594 GDD ergibt sich aus 17,97 x 20%
      - Euro-Betrag =      14,376 €       ergibt sich aus 17,97 - 3,594
      - DankBar-Betrag =  4,657 GDB  ergibt sich aus 18.04.2023 ist der 108.Tag im Jahr und der Formel 
         GDD-Betrag + (GDD-Betrag * (1/365) * Tag des Jahres)
            3,594        + (     3,594      * (1/365) *        108         ) = 4,657 GDB

  - **Anwendungsszenario-2**: Der Händler bietet auf Tomaten 20%-Gradido-Rabatt, auf Gurken 5% und auf Kartoffeln 0% Rabatt.
    - Die Eingabe erfolgt in folgender Reihenfolge:
       5 x 1,20 %20er-Taste + 3 x 1,99 %5er-Taste    + 10 x 0,60 =
     - intern merkt sich der Calculator
           6€ mit GDD-Rabatt (6€ * 0,2) + 5,97€ mit GDD-Rabatt (5,97€ * 0,05) + 6€ ohne GDD-Rabatt
  - Mit Tippen der =-Taste erfolgt die Ergebnis-Berechnung
    -  Euro-Summe:         17,97 €
    -  Beträge:
      - Gradido-Rabatt =   1,4985 GDD ergibt sich aus 6 x 20% + 5,97 * 5%
      - Euro-Betrag =      16,4715 €       ergibt sich aus 17,97 - 1,4985
      - DankBar-Betrag =  1,9419 GDB  ergibt sich aus 18.04.2023 ist der 108.Tag im Jahr und der Formel 
         GDD-Betrag + (GDD-Betrag * (1/365) * Tag des Jahres)
            1,4985       + (     1,4985     * (1/365) *        108         ) = 1,9419 GDB
  
- **Währungstausch Modus**
  - der User hat eine Summe in Gradido-DankBar möchte dessen Wert in GDD wissen, weil er die DankBar zB. an jemanden weitergibt, der ihn mit einer GDD-Überweisung dafür bezahlen will
  - in diesem Modus sind die 4-freibelegbaren Tasten mit DankBar-Einheiten belegt zB in den Einhaite 2GDB, 5GDB, 10GDB und 20GDB
  - die Eingabe erfolgt wie im üblich in der Form erst die Anzahl an DankBars, dann x-Taste gefolgt von der DankBar-Einheit entweder über die Ziffern-Tasten ohne Komma oder über eine der frei belegten Tasten
    5 x 1 + 12 x 2GDB + 3 x 10GDB + 1 x 50
  - in der Anzeige wird unterschieden bei der direkten Ziffern-EIngabe der DankBar-Einheit ohne die Einheit GDB und der Eingabe per belegter Taste mit GDB-Einheit hinter der Ziffer
  - mit Tippen der =-Taste erfolgt die Berechnung der Summe und Beträge zum aktuellen Tagesdatum am Beispiel 18.04.2023
    5 x 1 + 12 x 2GDB + 3 x 10GDB + 1 x 50 = 
```
    GDB-Summe  =  109 GDB          ergibt sich aus einfacher Berechnung der Zahlen
    GDD-Betrag =   92,8739 GDD     ergibt sich aus 18.04.2023 ist der 108.Tag des Jahres und der Formel 
          GDB-Summe - 0,5/365 * Tag des Jahres * GDB-Summe
             109    - 0,5/365 *      108       *   109     = 92,8739
    Tageskurs  =   16,1260 Decay   ergibt sich aus GDB-Summe - GDD-Betrag

```

**Comment by ogerly** [comment]
https://gradido.net/de/gradido-zu-dankbar-umrechner/
