### ISSUE TITLE
🚀 [Feature] Calculator as external tool

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2966]
## 🚀 Feature

Create the requested GDD-DankBar calculator as external tool

- [x] New repo under https://github.com/gradido - name it `dankbar-calculator` or similar
- [x] Check in the template provided by Bernd 
- [x] Duplicate the css code for the golden button on that html page and make the button a standard gradido-gold-button
- [x] Publish the calculator via github pages
- [x] create a iframe code which is documented in the repos README.md how to include the calculator as Iframe (the calculator should scale to almost every window size)
- [x] Include the calculator on wordpress
- [x] #2978

**Comment by ogerly** [comment]
https://gradido.net/de/gradido-zu-dankbar-umrechner/
