### ISSUE TITLE
💥 [DevOps] Server time not correct

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#299]
## 💥 DevOps ticket

The Server time is not correct. It is currently GMT+0 which is 2 hours behind us due to summer time. In winter it would be 1 hour behind us. This results in wrong timestamps for the user.

- How do we solve this?
- Local time zone is used to correct?
- Frontend or Backend?
- Do we need a setting for the user to set up his local time?

**Comment by einhornimmond** [comment]
cakephp can me give the right date if I give it a LOCALE

**Comment by ulfgebhardt** [comment]
I moved this to the next release now. I believe its not that important at the given moment. I think we should find a solution soon tho, since transactions are timed and it has a certain importance ;)
