### ISSUE TITLE
🌟 [EPIC] Frontend - User Area pages and components

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#3]
## Pages

-- Login 
       | ---- User Startseite / Übersicht
       | ---- User Profil Ansicht
       | ---- User Einstellungen
               | ---- 
               |
       

### User Startseite nach Anmeldung
es sollten alle componenten auch als einzelansicht von der userübersicht aus aufrufbar sein 

   ## FORMULAR: senden von GDD

   ## TABELLE: liste aller Transaktionen für einen User

   ## FORMULAR: neuer Beitrag für Community

   ## TABELLE: Liste aller Beiträge eines Users

**Comment by ulfgebhardt** [comment]
@ogerly Whats the Status on this?
