### ISSUE TITLE
🐛 [Bug] Password policies not aligned

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#30]
## :bug: Bugreport

Password policies are not aligned. You can register with `123456` but you cannot login with it, since it does not contain special character or letters and is less then 8 characters in total.

This is a sign of duplicate code - restructure would be wise. Furthermore the check for password strength should only occur on register & password change. There is no logic why this check would be happening on login.

### Steps to reproduce the behavior
1. Regster account with password `123456`
2. Try to login
3. Failure
4. ...
5. Profit

**Comment by einhornimmond** [comment]
I cannot replicate the bug. 
In Login-Server password validation is in function src/SingletonManager::checkPwdValidation.
Every function which is used to create or change a password, uses this function. And this function simply return true if in config:
```ini
unsecure.allow_all_passwords =1
```
Oh you are right, in unsecureLogin password validation is called and don't make sense this way. 
I have it changed now. No it makes perfect sense 3:)

**Comment by einhornimmond** [comment]
I could change my password to 1234 and could also login with it on stage1.gradido.com with old frontend.

**Comment by ulfgebhardt** [comment]
ok, so its probl a frontend thing

**Comment by ulfgebhardt** [comment]
Login passwort kriterien beim login nicht sinnvoll?
