### ISSUE TITLE
🚀 [Feature] - api calls please

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#31]
## :rocket: Feature
API calls bitte bereitstellen
- für senden von gradido 
- senden aktivies grundeinkommen aktivitäten (formular community)
- liste der aktivitäten eines users ()

wenn möglich 
- den api-call für das schöpfen
   - bestätigen einer grundeinkommens aktivitäts

**Comment by einhornimmond** [comment]
### 1. Senden von Gradidos:
POST http://localhost/transaction-send-coins/ajaxCreate
```json
{
	"session_id" : -127182,
	"amount": 2000000,
	"email": "max.musterman@gmail.de",
	"memo":"Thank you :)",
	"auto_sign": true
}
```

**Comment by ulfgebhardt** [comment]
closing this for now (activities call is missing, but its ecapsulated in another issue)
