### ISSUE TITLE
🐛 [Bug] Pagination of transactions

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#310]
## 🐛 Bugreport

Transactions are now paginated. This seems problematic in many ways:
- the frontend uses sort instead of the URL parameter
- we don't get the count of how many items are in the list
- we do not implement pagination at all in the frontend

**Comment by einhornimmond** [comment]
"we don't get the count of how many items are in the list"
You are right, that I can fix easy. That's actually one of the reason why I have added state_user_transactions :)
So I can get the count from mysql without the need of joining tables. That would be a performance nightmare with many transactions in db.
