### ISSUE TITLE
🐛 [Bug] Balance calculation is instable

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#313]
## 🐛 Bugreport

Balance calculation is instable. At least in the old frontend one could see instable balances. Those where updated after reloading or a while. We need to make sure that we always show correct values to the user.

Is this still the case? Is the new frontend affected? What are the causes?

**Comment by einhornimmond** [comment]
I think the reason is that model/Transactions/TransactionBase::updateStateBalance in community server don't use decay
My hotfixed live on staging don't work, so I must look at it again.
