### ISSUE TITLE
💬 [Question] Should decay be part of a transaction

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#318]
## 💬 Question

Currently we have two transaction per transaction:
1. The transaction itself
2. The decay transaction ontop of that

This seems to be illogical to split it into two transactions and brings alot of problems:
- the transaction list gets very cluttered
- if you want to change that the client needs to transform the 1-dimensional array into a 2-dimensional manually.

Should the decay be part of a Transaction?

**Comment by einhornimmond** [comment]
With #483 the decay information are now put inside the transactions. 
The only decay transaction left is from last transaction to current date.
