### ISSUE TITLE
💬 [Question] Monthly Decay

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#319]
## 💬 Question

We currently calculate the decay based on a second and allow the user to spend only those he owns based on this by-second decay. On the other hand we create gradido based on a monthly turnus.

Why is the creation not aligned to the decay?
Should we not calculate the decay once a month on a specific date? (e.g. first or last second of a month)
What are the downsides of this?

The upsides would be:
- easier to communicate to the user
- easier to actually do transactions since the decay does not need to be calculated
- aligned with the creation

The game would then be: You have 1 month to pass the bucket (GDD). The one who has it loses at the end of the month (the more GDD you own, the more you lose)

**Comment by BerndHueckstaedt** [comment]
We work on the concept since years.
Dario has the decay-function nearly finished, and we want to deliver in a few days.
There is no need and no time to discuss these basic functions.
