### ISSUE TITLE
💥 [DevOps] Have gradido node running on docker-compose

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#32]
## 💥 DevOps ticket

Have gradido node running on `docker-compose`.

Currently gradido-node is not running when running `docker-compose up`, since due to undefined environment variables it does not start and therefore was commented out.

![image](https://user-images.githubusercontent.com/1238238/110685905-10887300-81df-11eb-81c4-640acb07cf75.png)

Please make it run without predefined environment variables.

### Motive

Have all services running which are required for the full gradido service setup.

**Comment by einhornimmond** [comment]
Why we don't remove it complete from stage1 and add it in stage2 where it is really used and needed?

**Comment by ulfgebhardt** [comment]
I mean, sure go for it - but it would be wise to have stuff running before you remove it.

**Comment by einhornimmond** [comment]
I remove it from stage1 after it is running in stage2, okay?
