### ISSUE TITLE
🚀 [Feature] contribution memo editable by moderator

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#3211]
## 🚀 Feature 

- [x] a moderator should be granted with a dedicated right to modify the memo of a contribution a user has created
- [x] in the admin interface for a dedicated contribution the moderator can open the contributions chat. Next to the Button "Moderator-Notiz" a new Button "Modify Memo" has to be introduced, which will copy the current content of the contribution memo in the edit field of the dialog. The moderator can now modify the content of the memo. 
- [x] On pressing the Button "Senden" the original content of the memo field will be added as a new message in the message list, the content of the edit field will be stored as content of the contribution memo including with update information of the moderators modification action. Optionally the edit field could be get an expressiv background collor to signal the moderator the new "edit memo modus".
- [x] After storing the modified memo by the moderator and the original memo as message the contribution chat dialog will be refreshed and show the contribution memo with a hint about the moderator modification and in the message list the original memo as a new message in the message list.
- [x] in the wallet a modified contribution memo by the moderato will be shown including a hint about this moderator modification action.
- [x] email, user contribution was changed by moderator

**Comment by einhornimmond** [comment]
Which Information should be in the email?
Moderator name? New Contribution Memo? Old Contribution Memo?
Or only the information that a contribution memo was changed by a moderator?

**Comment by BerndHueckstaedt** [comment]
> Which Information should be in the email? Moderator name? New Contribution Memo? Old Contribution Memo? Or only the information that a contribution memo was changed by a moderator?

In principle, I would use the text as in the confirmation e-mail.
