### ISSUE TITLE
🔧 [Refactor] Decay start date

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#322]
## 🔧 Refactor ticket

We decided that the decay will start at a certain date and is not recalculated for the whole existing transactions. It is unclear how we can archive this. Seeral options where discussed:
- Have an own "Start Decay block" (once per chain)
- Have a note transaction defining the date or take its transaction date as start
- Define it in the code statically
- ....

**Comment by einhornimmond** [comment]
I tink "Have an own "Start Decay block" (once per chain)"
is the best solution.

**Comment by ulfgebhardt** [comment]
Its your decision. You are the master of the chain 😄 . Tho I would like you to prioritize this (once the gdd float thing is done) because this prevents us from releasing.
