### ISSUE TITLE
🐛 [Bug] Doubled Minus Sign On Decay Transactions

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#325]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/15882241/117163439-f1175c00-adc3-11eb-9719-3f4a1614d97d.png)

Only one minus sign

**Comment by einhornimmond** [comment]
fixed with commit https://github.com/gradido/gradido/pull/273/commits/851c7cad064d9c1a4c543be2576961311a76ca38 
in pr #273
