### ISSUE TITLE
🐛 [Bug] There is still CORS issues

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#33]
## :bug: Bugreport

Without an addon preventing CORS checks still fail.

![image](https://user-images.githubusercontent.com/1238238/110686946-41b57300-81e0-11eb-91b9-abe16d3f4a66.png)

### Steps to reproduce the behavior
1. Go to localhost:8080
2. Login without CORS block
3. Does not work
4. ...
5. Profit

### Expected behavior

Should work

**Comment by einhornimmond** [comment]
![CORS_Screen](https://user-images.githubusercontent.com/67117805/110750301-9093f480-8242-11eb-8925-3c76e3e02e31.png)

Do you have the right login-server version? Because I didn't get the bug. 
I have commit: 2837ac13f00fa411b826f58edcffc05519a5786e

**Comment by ulfgebhardt** [comment]
This seem to work now
