### ISSUE TITLE
🚀 [Feature] Reset password - Thanks - Overview

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#359]
## 🚀 Feature

After successfully resetting the password we are redirected to the thanks page. There we are redirected to the login page.

We should be logged in after PW reset and redirect to overview page after the thanks page.

Related to #306

**Comment by Mogge** [comment]
To get this working, we need a session id after successful password change. @einhornimmond

**Comment by einhornimmond** [comment]
But to successful change the password you need a valid session, so you already have one. 
The session don't change with password change. 
The setNewPassword function change the password in loaded user and in db.
