### ISSUE TITLE
🔧 [Refactor] Cleanup Git History for login server

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#36]
## :zap: Refactor ticket

Clean the git history of the login server and strip all critical credentials from the history.

### Motive

This is required in order to make it open source.

### Additional context

In this article two methods are described. One uses an additional program, the other uses `git filter`. Both methods will allow you to strip data completely from the repository. Make sure that all branches are affected!

https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by einhornimmond** [comment]
Oh I forget to close this issue
