### ISSUE TITLE
🔧 [Refactor] Spinner everywhere

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#360]
## 🔧 Refactor ticket

We now have a global spinner component. We should use it.
- Can we attach it to the API calls?
- Where are loading times?

**Comment by ulfgebhardt** [comment]
@Mogge Is the Spinner everywhere its needed?

**Comment by Mogge** [comment]
@ulfgebhardt I suggest to close this issue and open new issues when we find something where we need a spinner
