### ISSUE TITLE
🐛 [Bug] Grey page when navigating forward or backward on some occasions

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#363]
## 🐛 Bugreport

Grey page when navigating forward or backward on some occasions.
- Maybe there is a timing issue?
- Slow network?
- How can we handle this?

**Comment by Mogge** [comment]
@ulfgebhardt Still relevant? I cannot reproduce this behavior

**Comment by ulfgebhardt** [comment]
not happening anymore to me. Could be a hardware defect, idk
