### ISSUE TITLE
🚀 [Feature] Decay as part of a transaction

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#369]
## 🚀 Feature

Decay should be part of a transaction to not clutter the transaction list. On the other hand we need to show the user that he received the correct amount. Consider the following example:

- User has 1000GDD, but has not seen his account in a while, therefore he has like 200GDD decay - effectively he has 800GDD.
- Now he receives 300GDD from a friend
- He logs in and now need to see on his transaction list, that he correctly received 300GDD, but also needs to understand that he lost 200GDD during this transaction.
- How can we communicate this? If decay is part of the transaction we would show a amount of 100GDD received which is balance wise correct but not very easy to understand.

**Comment by BerndHueckstaedt** [comment]
In the list view we show only the actual transaction.
