### ISSUE TITLE
🚀 [Feature] Contributions

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#38]
## :rocket: Feature

After analysing some texts from the AGE forum this is my concept to save stuff:

```
- Zeitraum Tage genau, zeitstempel mit hours:minutes:seconds, aber nicht im Interface
  - Calendar selection from - to
  - Button für gesamten Monat 1
  - Button für gesamten Monat 2
  - Button für gesamten Monat 3
  - Last 14 days
  - Last 7 days
  - Last 3 days
- [Story] or Notes
  - Text
  - Amount of Hours
- Story or [Notes]
  - Multiple notes, each 1 liner text & hours
- Price per hour GDD
- Amount GDD total
```

Basically  there is two types of reports:
1. People telling a story with a total amount of hours
2. People listing specific tasks they do with individual hours

While 1 needs a multi-line input, 2. should only have one-line inputs with the option to have multiple activities
To select between the two types: [Story] and [Notes] I suggest tabs:
![image](https://user-images.githubusercontent.com/1238238/110695753-87773900-81ea-11eb-96da-fa43e6271b77.png)

Furthermore I believe its every important to give people a good option to select the time of activity. I believe we should limit its granularity to days, eve tho we should save hours, minutes & seconds in the database (00:00:00) 

Table design (suggestion, mock):

Activity:
- ID
- email
- start_time
- end_time
- hours
- gdd_price
- gdd_amount

ActivityEntry:
- ID
- activityID
- type
- text
- hours

**Comment by ogerly** [comment]
ok

**Comment by ulfgebhardt** [comment]
Besides all this I believe it is very important for people to know their stories are read. They write this because they primarily want to be honored for their work, not to get Gradido. Therefore we need to display the stories somewhere so people can read it. Maybe a random on on each page? Where could that be displayed?

**Comment by einhornimmond** [comment]
Nice Idea Ulf but than I think they must also have the option to not have it shown public.
