### ISSUE TITLE
🚀 [Feature] registration with session

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#4]
## :rocket: Feature

after login the sessionid should be passed to a session cookie

**Comment by ulfgebhardt** [comment]
@Mogge @einhornimmond is this still a thing?

**Comment by einhornimmond** [comment]
I call addCookie on login so it should happen, but if I test with firefox HTTP request Maker I don't see a cookie. 
I don't know if it is my code or if simply cannot test it with Firefox.
