### ISSUE TITLE
🐛 [Bug] Frontend transaction & balance format varies

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#400]
## 🐛 Bugreport

Frontend transaction & balance format varies. If the amount received or sent is ending with one or two zeros after the comma, they are omitted. So a transaction of 400,00 GDD is transmitted as 400 and a transaction of 555,50 is transmitted as 555,5. The frontend must ensure that there is always 2 digits after the comma. This includes the users balance.

**Comment by Mogge** [comment]
fixed
