### ISSUE TITLE
🐛 [Bug] Transaction List wrong pubKey value

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#412]
## 🐛 Bugreport

The transaction list transmits a pubKey value on each transaction which seems to represent my own pubKey on either send or receive transactions. This seems wrong. Maybe we want both receiver and sender pubKeys available.

**Comment by einhornimmond** [comment]
I have checked it, the transmitted pubkey is from the other party. 
The pubkey belong to the user which email is also transmitted. 
In send transactions the receiver, in receive transactions the sender.

**Comment by einhornimmond** [comment]
The frontend gets the public key of the logged in user on login, why I would transfer it with every transaction?
That where a waste of bandwith.

**Comment by ulfgebhardt** [comment]
seems not to be a bug
