### ISSUE TITLE
🐛 [Bug] Umlaut displayed incorrectly - Password reset EMail

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#432]
## 🐛 Bugreport

The Subject of the Passwort Reset EMail contains `ü` which is displayed incorrectly on some clients (Alex)

- [ ] Evaluate & Reproduce Problem
- [ ] Proper encoding possible?

**Comment by einhornimmond** [comment]
Ich habe es geändert, bitte probiert es da wo der Fehler aufgetreten ist nocheinmal mit der Version aus #579
