### ISSUE TITLE
💬 [Question] Elopage allows to register twice

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#438]
## 💬 Question

Elopage allows to register twice for the same user
1. Be logged in with elo page
2. click create new wallet on website
3. See that you are logged in on register Page
4. Register again with the same logged in user
5. ...
6. Profit

**Comment by BerndHueckstaedt** [comment]
Yes, that is correct. The same product is then registered twice at Elopage. But this is not a problem. Our software recognizes if it is the same email address and then does not register a new account.
