### ISSUE TITLE
🐛 [Bug] Building of login Server docker images fails

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#441]
## 🐛 Bugreport

Building of login Server docker images fails on existing repos. New repos allow a clean build. It seems to be related to files residing in the repo being ignored by gitignore.

We need to clean the build before building to avoid those Problems.

![image](https://user-images.githubusercontent.com/1238238/118278004-c1eea200-b4c9-11eb-8451-a594712450f6.png)

**Comment by einhornimmond** [comment]
You need to delete the folder: login_server/src/cpp/proto
then it should work.

**Comment by einhornimmond** [comment]
It can only reappear if someone checks out a old version before I have moved proto compiled files into build folder, build and than checkout a newer version after the version I have moved compiled files into build folder. 
So I would say no, it isn't likely that the bug will reappear. 
And if it does it should be possible to fix it by removing all untracked files with git clean (https://stackoverflow.com/questions/61212/how-to-remove-local-untracked-files-from-the-current-git-working-tree)
