### ISSUE TITLE
🐛 [Bug] Last decay is 2h in the future

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#446]
## 🐛 Bugreport

The last decay value is to high since it is calculated towards local time not server time - this is a error!
![image](https://user-images.githubusercontent.com/1238238/118290300-91f9cb80-b4d6-11eb-8d8e-a99bbd82b038.png)

**Comment by einhornimmond** [comment]
Currently I cannot find it anymore, maybe it occure only shortly after creating decay block. 
It could occure only as long as user hasn't made a transaction after decay block.

**Comment by ulfgebhardt** [comment]
It still have the problem on live

**Comment by einhornimmond** [comment]
Okay it occure only on live. 
I have changed the defaultTimezone for community server to From Berlin to UTC and now it seems to work. 
On staging defaultTimezone is UTC.
I had tested it with CEST but than the vue frontend don't show the transactions

**Comment by ulfgebhardt** [comment]
@Mogge @einhornimmond  Have you solved this? What is with cross-time-zone communities? Do we use a worldwide standard time like GMT+0? What is with winter/summer time? How does this effect the decay?

**Comment by Mogge** [comment]
I think we have solved the timezone issue. Though it is not implemented in the transactions details yet. I expect to receive UTC from the server and translate this to the timezone of the browser.

**Comment by ulfgebhardt** [comment]
@Mogge So the diplay issues are solved
@einhornimmond Changed Servertimes - how is the decay calculation affected? Is this all save now?

**Comment by einhornimmond** [comment]
Decay between transactions is calculcated with the time difference between the transactions. 
For saving the transaction time timestamp will be used. So it is a absolute point in time. 
So the differences between timestamp are independent from timezones.
