### ISSUE TITLE
🎂 [RELEASE] Gradido Final

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#45]
## 🎂 RELEASE

This Release just collects all the tasks not assigned to a specific release Version

**Comment by einhornimmond** [comment]
## Multiple Addresses 
Multiple Gradido Addresses for every user. 
Only at one Address per user creation is possible, therefore we need a way to check on blockchain-level for which address creation is allowed. 

Maybe with HD-Wallet technique from bitcoin.

### Needed for
- Equalization and Environmental Fund
- Public Budget
- GDT 
- multiple E-Mails and username as sender and receiver for transactions

**Comment by einhornimmond** [comment]
## Voting or blockchain based authentication
Normally the user sign there transaction with there private key. 
But for transactions from Equalization and Environmental Fund and Public Budget it isn't possible. 
When I use the same system, everyone how gets hands on private key can spend this money. Once they have access, it isn't possible to to permit it. 

We need a system which is able to track the decision of the community how is responsible and when and how long to spent money from the Equalization and Environmental Fund and Public Budget on blockchain. 
We don't now which system the community will be use, so better we make a system, which can support democracy, consens, consent, council and other forms which exist. 

### Needed for 
- Equalization and Environmental Fund
- Public Budget

**Comment by einhornimmond** [comment]
## GDT 
Think about a way to securly get GDTs into blockchain. 

### Depends on:
- Multiple Addresses

**Comment by ulfgebhardt** [comment]
@einhornimmond Thank you for writing down those Ideas! Can you make an Issue for each of them tho? That way we can assign them to a Release, Sprint and Person at a given time <3
