### ISSUE TITLE
🐛 [Bug] EMail input not valid for some users/emails

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#494]
## 🐛 Bugreport

EMail input not valid for some users/emails

Some users report that even tho they have a valid email as recipient typed in they cannot send gradido to that email. The message "Email muss eine gültige E-Mail-Adresse sein!" is displayed in red to the user.

> Ich habe jetzt mehrfach versucht bei unterschiedlichen Personen Überweisungen zu tätigen. Aber immer wieder taucht nah der Eingabe der E-Mail Adresse der Hinweis in Rot auf:
>
> Email muss eine gültige E-Mail-Adresse sein!

Another report:

> Jetzt versenden angeklickt. Dann taucht Hinweis unter Eingabefeld für E-Mail-Adresse Hinweis auf: Bitte geben Sie eine E-Mail-Adresse ein.

Note: The user reports that it is possible for other users to send GDD successfully. But her account does not allow it for some reason. There is also possible intersection with the leading zeros bug where gdd cannot be sent and the wrong message is displayed. Furthermore it is possible that this is a browser issue.

> Jetzt wollte ich weitere Überweisungen tätigen. Jetzt tauchen bei folgenden Mail Adressen plötzlich wieder Meldungen auf richtige Mail-Adresse angeben: abc.bcd@cde.ch, info@abc.at und gradido.abc.bcd@gmail.com.
> 
 > Wenn ich auf „Jetzt versenden“ klicke öffnet sich unter Empfänger-Eingabefeld ein Fester, in dem wieder aufgefordert wird richtige Mail-Adresse anzugeben.
 
> Bei den Mail-Adressen von Pilipp XXX und Joachim XXX hat es auch hier nicht funktioniert. Beim „Transaktion abschließen“ öffnete sich unter dem Eingabefeld Fenster: Bitte geben Sie eine E-Mail-Adresse ein. Überweisung konnte nicht stattfinden.

**Comment by Mogge** [comment]
I cannot reproduce this behavour

**Comment by ulfgebhardt** [comment]
trim email field to avoid spaces from copy errors as possible error source? @Mogge

**Comment by ulfgebhardt** [comment]
we trim the email now
