### ISSUE TITLE
🐛 [Bug] Double booking for user

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#495]
## 🐛 Bugreport

A user reports that she intended to send an amount of GDD. But the amount was sent twice.

> heute in der Montagskonferenz wurde gesagt, dass Überweisungen vom Konto Login neu (Beta) wieder funktionieren. Am 16.05.2021 hatte ich dann vom alten Konto versucht zu überweisen und dann wurde der Betrag zwei Mal abgebucht.

We need to evaluate when this can happen. Furthermore we need to figure out a mechanic how we can prevent this.

Common case of this would be a replay-"attack" where the user itself does the replay, by clicking twice

**Comment by einhornimmond** [comment]
I could save the last transaction on login-server per user in memory and compare if the same transaction was made before in short time. How long should the time difference?

**Comment by ulfgebhardt** [comment]
I was thinking of modeling the confirmation process. The user requests a transaction, gets a confirm token, sends the confirm with the token. Once this is sent successfully the token is invalid and the user cannot send another request with the same token. Tho I am unsure this is wise to do it that way. I have no clue whats the standard for this use case.

**Comment by einhornimmond** [comment]
Sounds more complicated as my solution.

**Comment by einhornimmond** [comment]
You need one more extra request to get transaction token with your solution.

**Comment by einhornimmond** [comment]
@ulfgebhardt  What do you think? 
#523

**Comment by einhornimmond** [comment]
Standard in crypto is bulletproof but they save balances with other strategy. 
Bei Bitcoin und den meisten anderen Coins, auch bei Iota endet jede Transaktion in mindestens einer unspent-transaction. 
Diese Unspent coins können genau einmal ausgegeben werden. Dann wird eine neue Transaktion angelegt, welche die alte unspent-transaction als Parent hat. Diese Transaktion muss dann alle Coins ausgeben, alle nicht ausgegebenen Coins gelten als fee und gehen an den Miner der den Block mined.
Wenn man also weniger ausgeben will, als mit der letzten Transaktion reingekommen ist, muss die neue Transaktion die Coins aufteilen. Die gewünschte Menge wird zum Ziel gesendet, der Rest geht zurück oder auf eine neue change Adresse im selben Wallet. Das verhindert auf jeden Fall sehr effektiv ein Double-Spent. 
Ist dafür aber in der Umsetzung auch wesentlich komplizierter.
