### ISSUE TITLE
🚀 [Feature] csrf token management

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#5]
## :rocket: Feature

csrf token management

### example **export**

 ```
 export default {
    props: { method: { default: 'POST' }},
    
    data() { return { csrfToken: null }},
    created() {
        this.csrfToken = document.querySelector('meta[name="csrf-token"]').content
    },
}
```
### Oder mit **Store** und **Props**

``` 
 props: ['csrf', 'oldName']`
``` 

### example form:
 ```
<template>
    <form ">
        <input-hidden :value="csrfToken" name="_token"/>

```

TODO: 

eventuell lässt es sich damit recht umstandsfrei einsetzen und nutzen
https://www.npmjs.com/package/vue-csrf

**Comment by einhornimmond** [comment]
I have disabled csrf token for every new community-server ajax request. 
Login-Server hasn't yet a csrf token system.
