### ISSUE TITLE
🐛 [Bug] User-Profil: Cannot save no changes

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#509]
## 🐛 Bugreport

User-Profil: Cannot save no changes

When there is no change i get an error when saving the user profile

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/4dc1f7a3-fe43-42f4-af16-ee0b25c2cda9)

**Comment by ulfgebhardt** [comment]
We handle this in the frontend, but we might think about adjusting this in the backend aswell.

**Comment by einhornimmond** [comment]
added in #519
