### ISSUE TITLE
🐛 [Bug] Password reset fails with error

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#514]
## 🐛 Bugreport

Clicking the link from the email produces an alert with an 502 http error

![image](https://user-images.githubusercontent.com/1238238/121663535-ceedb980-caa6-11eb-8f1b-56075d2df9d5.png)

**Comment by ulfgebhardt** [comment]
@einhornimmond This was a restart due to deployment bug? We can close this?

**Comment by einhornimmond** [comment]
yes
