### ISSUE TITLE
🐛 [Bug] Staging deployment open many many screens

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#515]
## 🐛 Bugreport

Staging deployment open many many screens
-> Processes do not end properly
-> Check that the right services are started
-> Chekc that all others are closed

**Comment by einhornimmond** [comment]
The command: 
screen -XS login quit
don't work like expected, so with each new deploy a new screen is opened.

**Comment by einhornimmond** [comment]
Deploy runs for every push, not only for master branch pushes :/

**Comment by einhornimmond** [comment]
Okay, the screen command  work like expected.
It gets only than problems when multiple pushes came in short time. 
I have fixed now. I create a lock file and allow only one update at a time. 
The only negative side: If more than one push in short time occure, stage1 build the first pushed version and is therefore not up to date.
