### ISSUE TITLE
🐛 [Bug] Cannot test password reset properly due to limitations

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#516]
## 🐛 Bugreport

Cannot test password reset properly due to limitations. Have an option to allow to disable those restrictions
for staging/testing. Is this needed?

![image](https://user-images.githubusercontent.com/1238238/121664020-550a0000-caa7-11eb-9d97-44f04251210c.png)

**Comment by einhornimmond** [comment]
You need only to delete the email verification code which is used for password reset also. 
You'll find it in email_opt_ins.
