### ISSUE TITLE
🔧 [Refactor] Fix up Frontend for Presentation

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#52]
## :zap: Refactor ticket

This is the TODO-List for next week Thursday. It is based on https://stage1.gradido.net/vue/

- [x] @BerndHueckstaedt might require some text changes. Those changes get delivered to you by him.
- [x] `Remember me` or also `Passwort merken`: check if this feature has functionality - if so finish implementation and have correct behaviour. If there is no implementation remove the checkbox & text and related code

![image](https://user-images.githubusercontent.com/1238238/111681090-2e7b5680-8823-11eb-8727-b00921a9d3f1.png)

- [x] There is no error produced to the user if the login fails. Only the console shows a `success: false`
- [x] `Forgot Password` - Check if functionality is implemented and what could be implemented with the current backend. Make a followup issue for issues regarding this.

![image](https://user-images.githubusercontent.com/1238238/111681928-13f5ad00-8824-11eb-9039-3a4d22e2740f.png)

- [x] Rename English `Imprint` into `Legal Notice`
- [x] Correct link to gradido.net legal notice
- [x] Correct link to gradido.net privacy policy
- [x] Remove `License` Link

![image](https://user-images.githubusercontent.com/1238238/111681869-0809eb00-8824-11eb-90f3-41bc7fa1c9a6.png)

- [x] On Register: The Form-Error-Messages are not translated if set to german
- [x] On Register: Privacy Policy not linked correctly

![image](https://user-images.githubusercontent.com/1238238/111681984-2374f600-8824-11eb-91ee-dd77d5851995.png)

- [x] EMail for register contains incorrect URL with double slash @einhornimmond 

![image](https://user-images.githubusercontent.com/1238238/111682120-4a332c80-8824-11eb-8b68-ee892c9469b3.png)

- [x] Followup Issue how we can/have to adjust the EMail for the new Frontend, since the link goes to the old frontend @einhornimmond 
- [x] Menu Logout has different background by default. better have a proper hover effect?

![image](https://user-images.githubusercontent.com/1238238/111682457-a8600f80-8824-11eb-8d3a-9b04194f56e9.png)

- [x] Edit Profil Button seems to have an incorrect color

![image](https://user-images.githubusercontent.com/1238238/111682521-c463b100-8824-11eb-9599-b3b129bbf862.png)

- [x] Button colors are all over the place - define a consistent style

![image](https://user-images.githubusercontent.com/1238238/111682612-df362580-8824-11eb-8b4d-5492a0a15c10.png)
![image](https://user-images.githubusercontent.com/1238238/111682626-e4937000-8824-11eb-9fc9-d25ee9315a87.png)
![image](https://user-images.githubusercontent.com/1238238/111682656-ec531480-8824-11eb-9636-c2458f44c0c7.png)
![image](https://user-images.githubusercontent.com/1238238/111682676-f1b05f00-8824-11eb-91c0-d6177f4f10bf.png)
![image](https://user-images.githubusercontent.com/1238238/111682756-03920200-8825-11eb-9251-d763122c4c41.png)

- [x] Profil contains data we cannot change like position, workplace, location, note etc. Remove this for now @ogerly . Please define what we can save in the backend currently @einhornimmond 

![image](https://user-images.githubusercontent.com/1238238/111682978-4358e980-8825-11eb-8139-cfa4a31b0a48.png)

- [x] Profil transaction count and other statistics is incorrect

![image](https://user-images.githubusercontent.com/1238238/111683048-553a8c80-8825-11eb-9b5e-f1b77a513d8d.png)

- [x] Profil show more button does nothing

![image](https://user-images.githubusercontent.com/1238238/111683108-64b9d580-8825-11eb-8200-b8fc0b4f4ae3.png)

- [x] Menu translations are inconsistent

![image](https://user-images.githubusercontent.com/1238238/111683215-7dc28680-8825-11eb-929e-281b100a506e.png)

- [x] Activities have dummy data

![image](https://user-images.githubusercontent.com/1238238/111683296-93d04700-8825-11eb-8bfd-0046b67ebe17.png)
![image](https://user-images.githubusercontent.com/1238238/111683377-aba7cb00-8825-11eb-9ffd-77321d9a71ae.png)

- [x]  Transactions are not shown correctly since we call localhost and not use the `.env` variables correctly

![image](https://user-images.githubusercontent.com/1238238/111683447-cb3ef380-8825-11eb-8e9f-f8e21c5c50d6.png)

- [X] Remove `Bitte trage jede Arbeit einzeln ein` text
- [X] Remove placeholder `{Name der Community}`
- [x] Hide activities since we cannot save them (must be easy to enable again)

![image](https://user-images.githubusercontent.com/1238238/111683669-148f4300-8826-11eb-9bca-d6a168504e18.png)

- [ ] Form field evaluation Errors are not displayed consistently

![image](https://user-images.githubusercontent.com/1238238/111683809-3e486a00-8826-11eb-92fc-0f44a04322ce.png)

- [x] Different fonts & margins in send gradido form

![image](https://user-images.githubusercontent.com/1238238/111683956-6b951800-8826-11eb-8bd9-66daa1779b2a.png)

- [ ] No Error Feedback when trying to send gradido and it does not work
- [ ] Cancel on Send Gradido form does not close the send window.

![image](https://user-images.githubusercontent.com/1238238/111684060-85365f80-8826-11eb-928c-9cf7b0eba41e.png)

### Motive

We want to make a Video of the new Frontend and deploy the whole thing to staging and later on to live.

**Comment by ulfgebhardt** [comment]
We will do the next test on Tuesday <3

**Comment by einhornimmond** [comment]
with api_password_reset #82 link in email verification email is set in login-server config

**Comment by einhornimmond** [comment]
fixed // it was only a / to much in login-server config

**Comment by ulfgebhardt** [comment]
closing this, most things seem to be done and a followup issue exists #87
