### ISSUE TITLE
🔧 [Refactor] Make components of the input fields

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#528]
## 🔧 Refactor ticket

The input fields need to be components which will be reused everywhere.
- password field
- password + password repeat
- old_password + repeat_password
- email field
- ...

**Comment by ulfgebhardt** [comment]
Is this done?

**Comment by Elweyn** [comment]
@ulfgebhardt, 
@ogerly and I are pairing and he is saying that the following are components:
- password 
- password repeat
- change password
- email

We think it is done!
