### ISSUE TITLE
🔧 [Refactor] Redesign Toast messages

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#547]
## 🔧 Refactor ticket

Redesign Toast messages
- [ ] fit into our design
- [x] use bootstrap toasts instead of eternal library
- [ ] Position top center
- [ ] Consider to have errors to be clicked away instead of auto disappear

**Comment by Mogge** [comment]
Position top center? I disagree. This is ugly as hell

**Comment by Mogge** [comment]
I do not consider to click away the messages. I think this is bad user experience when we mess up and generate errors
