### ISSUE TITLE
💥 [DevOps] Enforce 60% converage (frontend)

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#553]
## 💥 DevOps ticket

Enforce 60% coverage

**Comment by ogerly** [comment]
![giphys](https://user-images.githubusercontent.com/1324583/122362309-511f2780-cf58-11eb-80b7-55be5f6a00d0.gif)

**Comment by Elweyn** [comment]
@Mogge, @ulfgebhardt,
We need to transfer this issue to the new epic? 
Or is it done?
