### ISSUE TITLE
🔧 [Refactor] Switch language only in user profile

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#557]
## 🔧 Refactor ticket

Switch language only in user profile not on every page.
-> Make sure the behaviour is correct when a new user registers
-> Is the browser language read correctly?

**Comment by ogerly** [comment]
![FireShot_Capture_293_-_Wireframe cc_-_The_go-to_free_online_wireframing_tool _-_wireframe cc](https://user-images.githubusercontent.com/1324583/132480749-2565efd5-6f35-423e-97ca-09f59a869265.png)
