### ISSUE TITLE
🚀 [Feature] Show Decay since last transaction 

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#569]
## 🚀 Feature

Show Decay since last transaction. The rest of the decay transaction will be hidden in the transaction themselfs. To have a valid balance the decay since the last transaction must be part of the list.

Pagination must take this into account.

**Comment by ulfgebhardt** [comment]
@einhornimmond Does this work already and how is it with the pagination?

**Comment by einhornimmond** [comment]
Pagination only influence the transactions, not the decay transaction entrys. 
So if you request 5 transactions you will get 5 transaction plus one decay transaction entry. 
The decay transactions are only virtuell, they not saved in db.

**Comment by ulfgebhardt** [comment]
But I expect to get 25 entries when I request a page size of 25. But when i do this with page 1, I get 26 entries. Can we have an exception for the first page to be 24+1?
Page 1 = 1 - (n-1) + decay
Page 2 = n - (2n-1)
Page 3 = 2n - (3n-1) ....

Par Example:
n = 5
Page 1 = 1 - 4 + decay
Page 2 = 5 - 9
Page 3 = 10 - 14

Formalized this is:
n = page count
p = current page
PageStart = n^(p-1)
PageEnd = p*n-1
FirstPage starts with 1 instead of 0 and therefore delivers only n-1 entries which makes space for the decay

**Comment by einhornimmond** [comment]
I can use this modi for pagination:
page and limit or 
offset and limit.
When I use page, offset is automatic calculated from (page - 1) * limit
So offset and limit are the native mysql parameter for the limit function. 

With your algorithmus one entry will be missing. 
For page 1, n = 5;
PageStart (offset) = 0
Limit = 4
return entry 1-4

For page 2, n = 5:
PageStart (offset) = (2 - 1) * 5 = 5
Limit = 5
return entry 6-10

(https://www.mysqltutorial.org/mysql-limit.aspx)
So entry 5 is missing.
