### ISSUE TITLE
🐛 [Bug] updateUserInfos allows unsecure password

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#588]
## 🐛 Bugreport

`updateUserInfos` allows unsecure password. When using the password change feature in the user profile, the user can, due to missing client side validation, send unsecure passwords like `123` as password change request to the backend. The unsecure password is accepted.

**Comment by einhornimmond** [comment]
I remember a time when someone in particular, I won't name names now, complained about not being able to set 123 as a password. That's not a bug, that's a feature.

But of course you can disable this feature in Login-Server Config. 
For Docker Build you find it in folder:
configs/login_server/grd_login.properties
The last option: unsecure.allow_all_passwords
If you put a # in front of it and restart login-server, you "bug" is gone. 

In Production this option isn't enabled. You can try if you can set your password on gdd1.gradido.com to 123
simply via: https://gdd1.gradido.com/account/updateUserPassword

**Comment by ulfgebhardt** [comment]
We have the unsecure flag in the backend, but the frontend requires the harsh conditions for the password. Therefore the flag renders an inconsistency.

**Comment by ulfgebhardt** [comment]
@ollivah This is related to the latest question - check this out ;)

**Comment by ulfgebhardt** [comment]
This is still a problem with current implementation. On `updateUserInfo` the validity of the password is not checked
