### ISSUE TITLE
🔧 [Refactor] Userprofile password change layout suboptimal

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#589]
## 🔧 Refactor ticket

Userprofile password change feature has suboptimal layout. It looks unfinished and not properly designed on desktop and is very big on mobile.

Desktop is very big and bloated. No constant alignment seems to be used

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/97fe1f7b-922d-42d4-b09e-c0e09c30e706)

Mobile:

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/cb9e88a1-0271-4557-b90f-179930d96cd2)

**Comment by ogerly** [comment]
I think this task can be closed, the graphical representation currently has a state that is ok. 

![FireShot Capture 515 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/133739959-6ef3097b-e2b1-424a-8d36-4f632069eefd.png)

![FireShot Capture 516 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/133740063-95df282c-a43a-48ea-8c85-2f0869370f9d.png)
