### ISSUE TITLE
🐛 [Bug] Mobile: Send button not floating properly

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#591]
## 🐛 Bugreport

Mobile: Send button not floating properly.

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/a262dd11-09d4-44cc-9926-c0234f552f56)

Only the German version is affected

**Comment by ogerly** [comment]
![FireShot Capture 013 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/126032580-afd75a28-c38e-4fa3-aa4e-8e56dc22fded.png)
![FireShot Capture 014 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/126032583-6f031d83-ea07-4a29-b6f6-c8d3623538a3.png)
![FireShot Capture 015 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/126032589-a8f0947a-04ca-446c-83ad-4d5e15c72a88.png)


das sind zur zeit meine ergebnisse.
