### ISSUE TITLE
💬 [Question] Decay date & time definitions

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#593]
## 💬 Question

We need to evaluate the decay date & time definitions. Is is obvious to the user when and why he loses GDD due to decay?
When creating GDD how exactly is decay calculated?
To what extend can the mechanic be abused?

**Comment by einhornimmond** [comment]
With every send coins and creation transaction which reach Community Server this happen:

- Entry in Table: Transactions
  read entry from db to get value of received field (DEFAULT CURRENT_TIMESTAMP)
- Entry in Table TransactionSendCoins or TransactionCreations
- 1-2 Entries in Table StateUserTransactions one for each in the transaction involved users
  in this entry also decay to last transaction of user is calculated (time diff between received timestamp from transaction and balance_date timestamp from newest state user transaction entry with same state_user_id)
- update state_balance entry for user with new balance at date of finished transaction

**Comment by einhornimmond** [comment]
Later with Gradido Node (C++) the calculation will has a much greater accuracy and Community-Server gets the transactions together with calculated decay. On Gradido Node the GDD value has 6 additional decimal places.

**Comment by ulfgebhardt** [comment]
I consider this solved
