### ISSUE TITLE
🐛 [Bug] Mobile: Toast not full width

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#595]
## 🐛 Bugreport

On mobile the toast is not full width which looks a bit off. It is also not readable in its entirety on some devices.

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/1e4cf1ad-9b0b-44a9-9ff5-10dc1150cf7d)

**Comment by Mogge** [comment]
We cannot change this with the package we use. It would be nice to get the in build bootstrap vue toasts running.
