### ISSUE TITLE
🐛 [Bug] Toast two X

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#596]
## 🐛 Bugreport

The Toast popup has two X symbols. The left one does not have any functionality.

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/1719d834-cc4a-4a27-a79d-8c0eecf70bbc)

**Comment by Mogge** [comment]
The first 'X' is the symbol for the error.

**Comment by Mogge** [comment]
The package we use does not allow this kind of customization.
