### ISSUE TITLE
🚀 [Feature] Userdaten - Testbenutzer - test.json

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#6]
## :rocket: Feature

Testbenutzer

Es sollte eine userabfrage zum test eingerichtet werden. 

Enthält Daten des aktuell eingeloggten Benutzers, z.B.: mein Testbenutzer:  
```
{
  "created": 1578688666,
  "disabled": false,
  "email": "email@gmail.com",
  "email_checked": true,
  "first_name": "Max",
  "group_alias": "gdd1",
  "ident_hash": 2928827813,
  "last_name": "Miau",
  "public_hex": "2ed28a1cf5e116d83615406bc577152221c2f774a5656f66a0e7540f7576d71b",
  "role": "admin",
  "username": "",
  "balance": 174500, // Gradido Cent, 4 Nachkommastellen (2 Reserve) entspricht 17,45 
  "id": 1,
  "errorCount": 0
}
```
Das sind im Grunde die Benutzerangaben aus der Login-Server Datenbank.

session :int Login-Server session id, notwendig für alle ajax-request.

**Comment by einhornimmond** [comment]
that shouldn't been open because my email is in there.

**Comment by ulfgebhardt** [comment]
I think we can consider this done
