### ISSUE TITLE
🐛 [Bug] Description Cannot Be Empty

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#616]
## 🐛 Bugreport
When calling `POST http://localhost/login_api/updateUserInfos` with 
```
User.description:  ""
User.first_name:  "Some"
User.last_name: "Name"
```
I get
```
errors:  [ "User.description is empty" ]
0: "User.description is empty"
msg: "User.description is empty"
state: "error"
valid_values: 1
```

**update**
same goes for `first_name` and `last_name`

**Comment by einhornimmond** [comment]
Yes, my code assume if you set the field description you like to change it.
Hm... but if people like to clear the description? I don't consider this case.
Ok so I remove the empty check for description to allow clearing it.
