### ISSUE TITLE
🐛 [Bug] Response after Reset Password

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#632]
## 🐛 Bugreport
When a user requests to reset the password a second time, it is said that an email was send, which actually is not the case.

**Comment by ulfgebhardt** [comment]
I think this is due to a security change we did. When requesting a reset we need to make sure that an attacker cannot determine the existence of an email. Therefore its said the email is sent every time.
Any suggestions how to solve this?
Is this actually a security issue?

**Comment by einhornimmond** [comment]
Yes you are right. 
If the email was used, the link clicked the entry in db was deleted which is also used for checking if a email was already sended. 
So after clicking on the link and then for example accidently closing the browser, you can start the process over and request a new email.
