### ISSUE TITLE
🔧 [Refactor] Display of Decay in Transaction Details

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#636]
## 🔧 Refactor ticket

Suggested solution:

balance before transaction    X
decay            D
transaction amount       T

balance after transaction =     X - D + T

**Comment by ogerly** [comment]
Do you mean like this? 
![FireShot Capture 192 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/128988626-d428d4f7-2f85-4053-befb-5a5af7995cc5.png)

**Comment by ogerly** [comment]
decay and transaction amount should be taken minus 

balance after transaction = X - D - T
