### ISSUE TITLE
Install Apollo Server with a 3rd Person

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#651]
## 💥 Apollo Server axio call goes into exception
I tried to test the login call from the Apollo Server, this always goes in the catch block around the axio call.
@Mogge made the same test and in his development environment it works.

We need a 3rd Person that tries the backend. 
- [x] Checkout the branch: backend_setup
- [x] Build Docker: docker-compose up or docker-compose up --build
- [x] Send to localhost:4000 a graphql query that uses login
Change the email value and the password:
```
{
	login(email:"test@test.com", password:"test123") {
		sessionId
		user {
			email
			firstName
			lastName
		}
	}
}
```

**Comment by einhornimmond** [comment]
It is working by me.
I get this result: 
```graphql
{
  "data": {
    "login": {
      "sessionId": 439762313,
      "user": {
        "email": "dariofrodo@gmx.de",
        "firstName": "Dario",
        "lastName": "Frodo"
      }
    }
  }
}
```

And this is my .env:
```ini
PORT=4000
GRAPHIQL=true
LOGIN_API_URL=http://login-server:1201/
COMMUNITY_API_URL=http://localhost/api/
```

**Comment by Elweyn** [comment]
Since it is working for @einhornimmond I need to make a bit more research on my local machine...
I restarted the analysis. 
When I call the unsecureLogin methode of the login_server I get a JSON Error message as followed:
```JSON
{"msg":"unknown call","state":"error"}  
```
The "msg": "unknown call" is setten in the class JsonUnknown that is created if the configs don't correspond to the /unsecureLogin call. It only goes in this block if the following is true: 
```
(ServerConfig::g_AllowUnsecureFlags & ServerConfig::UNSECURE_PASSWORD_REQUESTS)
```

So the problem could eventually be fixed if I can configure them so that the if statement is true!

**Comment by Elweyn** [comment]
@einhornimmond found the error

In the .env file the LOGIN_API_URL=http://login-server:1201/ without the explizit call to the underneath path.

**Comment by ulfgebhardt** [comment]
Closing this since it seems to be working for everyone now
