### ISSUE TITLE
[FEATURE] Community Server API call to GDT Server to get a "GDT Transaction List"

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#657]
## Community Server call to GDT Server
The frontend needs data to show the GDT transaction list, so we need to define a API call that will send the stored data.

**Comment by einhornimmond** [comment]
Add API Call for frontend to get GDT transactions,
sort out informations which aren't neccessary for frontend.

Update GDT Api Call to also allow pagination.

**Comment by ulfgebhardt** [comment]
@einhornimmond Whats the status on this? As I understood it you have a PR for apollo, but whats about the session with alex? Did you finish implementing this?

**Comment by einhornimmond** [comment]
No, I still need to update the format for the gdt entries created with publishers to have it similiar to the other so is more easy for alex.
