### ISSUE TITLE
[DevOps] Set-up GDT Server on staging

### ISSUE THREAD

**Issue by Elweyn** [gradido/gradido#672]
## Set-Up GDT Server on staging
As team we need to test the GDT logic so we need to install the gdt server on the staging maschine.

**Comment by einhornimmond** [comment]
You find the gdt on staging on this url:
https://gdt.gradido.net
To able to login to setup own test data I have made a admin account and write the passwort in keybase in the php-js group.
It is maybe only for testing yet I am cautious when it comes to passwords.

The url for the list transactions call is this: 
https://gdt.gradido.net/GdtEntries/listPerEmailApi/<email>

Currently it exist only one entry for email dariofrodo@gmx.de and one global modificator 

from 01.01.15, 15:00 until 31.12.20, 12:00
20 %

**Comment by einhornimmond** [comment]
In the GDT repository you find in doc folder now also elopage_webhook.md describing the format of webhook for creating own gdt entries out of elopage transactions with publisher links

**Comment by ulfgebhardt** [comment]
The correct URL therefore is: `https://gdt.gradido.net/GdtEntries/listPerEmailApi/dariofrodo@gmx.de`

**Comment by ulfgebhardt** [comment]
Can you provide a link to the docu? I cannot seem to find it. @einhornimmond
