### ISSUE TITLE
🚀 [Feature] Allowed Special Character for Password

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#684]
## 🚀 Feature
Discuss which characters should be allowed as special character for password. 
Better don't use character which can be used to write malicious scripts. 

Currently allowed are:
@$!%*?&+-_

Claus missed the # character.

**Comment by ulfgebhardt** [comment]
I think the user should not be limited in his password choice within an unicode charset like utf8/16. If he wants to use emojies as a password why would we prevent him to?

**Comment by einhornimmond** [comment]
As I have written the code to check if the password meets the criteria, I don't know how to check for special char if all are allowed.
So it is mainly for technical reason. But maybe I now found a way and can allow all.
