### ISSUE TITLE
💥 [DevOps] Document Server Infrastructure

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#693]
## 💥 DevOps ticket

Document Server Infrastructure

- What Servers do we have?
  - Provider
  - CPU
  - RAM
  - Other metrics
- What is running on it?
- Do we have monitoring for it?
  - Security?
  - Performance?
- Backups?
  - Do we have them?
  - Of what Servers?
  - What exactly is backuped?
  - Where is it backuped to?

- Do we need or want to migrate to a different infrastructure?
- How could such a infrastructure look like?

- What are our expenses for given infrastructure?

**Comment by einhornimmond** [comment]
I will write it down but not here in the open. 
I consider this information security relevant so I will only send it through save channels like keybase.
But not all team members are currently with us in keybase.

**Comment by ulfgebhardt** [comment]
Just send me and @clauspeterhuebner a pdf via discord and we will figure out what parts need to be kept private and which can be part of the official documentation <3

**Comment by einhornimmond** [comment]
I consider discord as unsafe even the PM channel.

**Comment by einhornimmond** [comment]
I have it uploaded in nextcloud
https://wolke.gradido.net/apps/files/?dir=/Gradido%20Konzept&fileid=359

**Comment by ulfgebhardt** [comment]
Many thanks for this! Do we know anything about the processor/disk/network usage of those servers?
It seems that we might be able to remove the support Server if we combine it with the main server?

**Comment by einhornimmond** [comment]
CPU is currently not much used,
Main: ~ 500 MB Memory free, disk: > 10 GB free
Support: ~ 300 MB Memory free, disk > 800 GB free

Zammad cannot run on Main, it's need at least 8 GB Ram or 4 GB and an additional server for elastic search with 4 GB:
https://docs.zammad.org/en/latest/prerequisites/hardware.html

We don't use wekan (Kanban-Board) anymore, isn't it? When I remove this, then Gradido should actually run on the support server if it doesn't consume much more resources than wekan.

**Comment by einhornimmond** [comment]
If someone likes to hack a gradido server direct he needs as much information as possible. 
With this documents published in the open half of his work is already done!
We can publish the specs of the server on which gradido is able to run, but why publish all the servers from Gradido-Academy and my private Servers I use for testing?
What is the benefit there?
I don't like my servers configuration out in the open for everyone to read.
