### ISSUE TITLE
🚀 [Feature] Session Cookie: GRADIDO_LOGIN

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#7]
## :rocket: Feature

Session Cookie: GRADIDO_LOGIN Access Token 

Login über eingebundene Login-Seite auslesen der session_id aus dem Session Cookie: GRADIDO_LOGIN Access Token vom Login-Server anfragen: GET https://staging.gradido.net/appRequest/acquireAccessToken?session_id = <GRADIDO_LOGIN> Du kannst auch den Cookie wieder mitschicken, solange die Login-Server Basis-url die gleiche ist, müsste das auch funktionieren. Antwort:
```
{
  "state":"success", 
  "access_token" : "<integer>",
  "group_base_url":"<Community Server Base Url>"
  }
```
Unterschied Access Token von der session_id: Access Tokens sind länger gültig Du kannst über eine gültige session_id einen Access Token erhalten der eine Woche gültig ist. Die Client-IP des Aufrufess muss die gleiche sein, mit der eingeloggt wurde.

Mit einem gültigen Access-Token kannst du eine session_id erhalten. GET https://staging.gradido.net/appRequest/appLogin?access_token = Mit jedem Aufruf wird die Gültigkeit der Access-Tokens erneuert. Antwort:
```
{
  "state":"success", 
  "session_id" : "<integer>"
}
```

**Comment by einhornimmond** [comment]
Access-Token Code exist in Login-Server since stage 2 and was planned for Native Mobile App, it isn't necessary for current vue-js client version.

**Comment by ulfgebhardt** [comment]
@einhornimmond @Mogge Is this still a thing?

**Comment by einhornimmond** [comment]
I can proceed with the request token code if we need it. 
But I don't see it in Browser-Version Use. 
On Smartphone it could be useful so that user don't need type in his credentials each time.
