### ISSUE TITLE
💥 [DevOps] Analyse Login & Community Database

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#703]
## 💥 DevOps ticket

Analyse Login & Community Database and figure out which data is stored in both. Furthermore define Name-Conventions (aligned with the tools we use - `typeorm`) and find data not used.

**Comment by einhornimmond** [comment]
I dont' understand. I thought we keep the existing dbs. 
They use the cakephp Names-Convention, snake-case, tablenames in plural form.
TypeORM use CamelCase, Tablenames in singular form.
So to support the Names Convention of typeorm we must change nearly every table and fieldname. 
Maybe it is better to create a new table with typeorm names convention.
