### ISSUE TITLE
🔧 [Refactor] Get Rid of Warnings in Specs of UserProfileTransactionList

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#713]
## 🔧 Refactor ticket
The test of UserProfileTransactionList throws warnings:
```
 [BootstrapVue warn]: observeDom: Requires MutationObserver support.
```
Find a way to eliminate them!

**Comment by Elweyn** [comment]
@Mogge, @ulfgebhardt,
I will remove the window.alert('success message') and window.alert('error message') and replace it with either $toaster success or error method so we can make a proper test like we would like to have it when we use it.
