### ISSUE TITLE
🚀 [Feature] Newsletter Management in User Profile

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#729]
## 🚀 Feature

The user wants to:
- [ ] see his email list subscriptions
- [ ] subscribe to lists hes not enlisted yet
- [ ] unsubscribe to those he is listed

The user does this in his account settings since he expects it there
- [ ] Refactor Settings Design

**Comment by Elweyn** [comment]
@einhornimmond does this PR (https://github.com/gradido/gradido/pull/241) has something to do with this issue?

**Comment by einhornimmond** [comment]
Klicktipp works with tags and for gradido it exist many tags. 
But Bernd has said that not all in use anymore. 
So we need also a place to write down which tags should be used.

**Comment by einhornimmond** [comment]
Th PR #241 isn't finished yet.
Maybe nodejs can access the RSET Api from klicktipp directly?
https://support.klicktipp.com/article/388-rest-application-programming-interface-api

**Comment by Elweyn** [comment]
So I made some research and found the following javascript project: https://github.com/brunokrauss/klicktipp-api.
It is: A node translation of php Wrapper of the klicktipp API. (https://support.klicktipp.com/article/394-php-wrapper)
If we look at this file: https://github.com/brunokrauss/klicktipp-api/blob/main/klicktippAPI.js we can see the definition of the functions we would need:
- signin
- login
  - subscribe
  - unsubscribe
- logout
- ...

**Comment by Elweyn** [comment]
I made some test with the javascript project it seems that there is no .d.ts file in the project so we have some problems to import it in our typescript files.
Need to look further inside it!
