### ISSUE TITLE
🐛 [Bug] GDT Transaction ID is missing

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#740]
## 🐛 Bugreport

GDT Transaction ID is missing

We get null values for GDT transaction ids (or so I understood). This made us switch from a direct GDT-Connection to the Community-Server-Tunnel (why? @Mogge ).
Apparently we get null values for the transaction ids, which are used as unique identifier for a GDT-Transaction analog to the GDD-Transactions

**Comment by einhornimmond** [comment]
Please check again.

**Comment by einhornimmond** [comment]
I think @Mogge switched to Community-Server-Tunnel because the gdt call needs instead of session_id email as parameter.
