### ISSUE TITLE
💥 [DevOps] Deployment on Staging with yarn not npm

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#745]
## 💥 DevOps ticket

Deployment on Staging with `yarn` not `npm`

**This issue might be obsolete if we decide to change deployment completely**

**Comment by einhornimmond** [comment]
What's the reason for that?
Because you like yarn more than npm?

**Comment by ulfgebhardt** [comment]
We use `yarn` for development and have a `yarn.lock` defining the specific package versions we use. If you use `npm` you will have a `package-lock.json` - since this is not present a new one is created when calling `npm install` - which will result in other packages used.

**Comment by einhornimmond** [comment]
I use npm when working on apolle, because yarn don't work on windows.

**Comment by ulfgebhardt** [comment]
fixed
