### ISSUE TITLE
🔧 [Refactor] Apollo Server has URL /graphql - why?

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#750]
## 🔧 Refactor ticket

Apollo Server has URL `/graphql` - why?

Please serve the graphql under `/` - or why would we need other parts that are not graphql?

-> This complicates nginx configuration (even tho solveable its not nice - I serve the server in nginx under `host/backend` and the server itself serves und `/graphql` making an URL `host/backend/graphql`)

**Comment by Elweyn** [comment]
@ulfgebhardt the changes is something pretty fast to do or do I see it wrong?
Is it important? If yes we should take it to the next sprint. If not we take it if we have capacities for it.

**Comment by ulfgebhardt** [comment]
done
