### ISSUE TITLE
💬 [Question] Test for GDT 21%-Event

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#786]
## 💬 Question

We should perform a GDT 21% Test before running the campaign

**Comment by einhornimmond** [comment]
Yes, how would you do that?
I thought we have already test it. 
But I can add another campagin entry in gdt on staging.

**Comment by ulfgebhardt** [comment]
I thought we gonna test with live data again. If we all agree to not do further testing, we can close this. But my last info was that we want to do that ?!
