### ISSUE TITLE
🐛 [Bug] Reset Password does not work (Register)

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#787]
## 🐛 Bugreport

The Reset-Password Component does not react to a password reset. When pressing the Reset Button on the register Page, the password stays. The two corresponding tests are skipped.

Two Options:
1. React to an `reset` event
2. Watch the props for changes https://stackoverflow.com/questions/44584292/how-to-listen-for-props-changes

Todo:
- Have the password reset when pressing the reset button
- Have the two skipped tests enabled

**Comment by ulfgebhardt** [comment]
Same applies for the language

**Comment by ogerly** [comment]
hebt sich auf .. weil wir das reset raus nehmen https://github.com/gradido/gradido/issues/816
