### ISSUE TITLE
🔧 [Refactor] Prolong JWT on each request

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#789]
## 🔧 Refactor ticket

Prolong JWT on each request. Currently the JWT is generated when logging in an not refreshed.
We agreed to send a new Token with every request to prevent the force-relog every 15min.

Additional this issue #785 can be implemented on top of that to increase security.

**Comment by einhornimmond** [comment]
Why with each request? Is it not enough only prolong it shortly before expire?
Maybe if it expire in one minute ore less.

**Comment by ulfgebhardt** [comment]
The JWT spec allows exactly that - extend when needed = in short range of expire. With the `sessionId` the expire time is not carried with it - therefore we just enforce it and use the JWT mechanism on top till we can replace the whole thing. We basically encapsulate the `sessionId` as much as possible to use mechanics like expiresIn and alike.
