### ISSUE TITLE
💬 [Question] Klicktipp Usage as part of the AGBs

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#801]
## 💬 Question

We need to inform the user about our usage of the 3rd party association with Klicktipp and our datatransfere to that company(email, name etc), or is this already covered by our dataprotection/agbs?

**Comment by Elweyn** [comment]
Hi @clauspeterhuebner, @BerndHueckstaedt, 

We would need a lawyer to writte an AGB or what should be the Prozess for this?

**Comment by ulfgebhardt** [comment]
brexit?
