### ISSUE TITLE
🚀 [Feature] update registration link on wordpress page(s)

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#802]
## 🚀 Feature

- change the wordpress pages to use the new "registration URL" defined by the new registration process
- append the optional URL parameter PID to the registration URL

**Comment by clauspeterhuebner** [comment]
@ulfgebhardt: are the changes on the wordpress-pages done with the last hotfix-rollout? 
If yes, the ticket can be closed too.

**Comment by ulfgebhardt** [comment]
They are done, but not part of the hotfix - we have to wait for a new deploy unless we want to do another hotfix. We merged some admin hotfixes instead

**Comment by ulfgebhardt** [comment]
this is done
