### ISSUE TITLE
🚀 [Feature] community selection page as 1st page of registration process

### ISSUE THREAD

**Issue by clauspeterhuebner** [gradido/gradido#803]
## 🚀 Feature

1. new page to select a community
2. shows a single selectable list with the names of all communities
3. the names of all communities and their registration URL has to be requested per service invocation at the community instanz ( see community creation process)
4. shows an Abbruch and Weiter Button
5. Weiter Button is enabled as soon a community is selected
6. optional: a given PID parameter check per request invocation against the GDT-Server, returns a valid PID - the given one or the default PID of the Förderkreis
7. pressing the Weiter button invokes the registration process on the selected community incuding the mandatory PID

**Comment by ulfgebhardt** [comment]
I disagree completely with this feature - this is  centralized approach again. We should talk about this in a refinement @clauspeterhuebner @BerndHueckstaedt

**Comment by ulfgebhardt** [comment]
Suggestion:

![image](https://user-images.githubusercontent.com/1238238/133757987-ca57d96e-6a61-47b7-9d19-7c7fa19a4a4b.png)
