### ISSUE TITLE
🐛 [Bug] Some entries on GDT List cannot be opened

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#825]
## 🐛 Bugreport

Some entries on the GDT cannot be opened.

![image](https://user-images.githubusercontent.com/1238238/133802761-b9ad1216-b11e-44a5-ab25-658bffd1aca8.png)

As seen in the picture, when clicking this entry only a small space appears, no infobox

**Comment by ogerly** [comment]
unfortunately cannot reconstruct the scenario
