### ISSUE TITLE
💬 [Question] Different Design of GDD & GDT Lists

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#826]
## 💬 Question

The design when opening the entries on GDD & GDT differ. Is this on purpose? What would that purpose be?

GDD:
![image](https://user-images.githubusercontent.com/1238238/133803273-69716345-5004-4600-b811-ac3d78cba998.png)

GDT:
![image](https://user-images.githubusercontent.com/1238238/133803190-e8802502-e0b1-4a8c-8d5e-b9973c94d088.png)

**Comment by ogerly** [comment]
The style of the GDT list has been adapted to the style of the GDD list.

![FireShot Capture 544 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/134465982-c853eb8d-21d9-474e-9006-1e734b85486e.png)
