### ISSUE TITLE
💬 [Question] Analyse how users differ on elopage and our service

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#829]
## 💬 Question

Analyse how users differ on elopage and our service.

Since we change the registration process, we should evaluate how many users are registered on elopage and our service.
- How many are equal
- How many are only on elopage
- How many are only on our service

**Comment by einhornimmond** [comment]
Login-Server save some data from elopage requests from specific product types which lead to account creation if user (email) hasn't already a account. 
This table contains 1995 distinct email addresses. 
The users table contains 1966 users. Email is a unique key in users. 

To get more specific I must create a mysql query for that or write a new custom http-page on login-server which compare the emails. 
Or have you other ideas?

**Comment by einhornimmond** [comment]
1940 seems to be equal

**Comment by einhornimmond** [comment]
@ulfgebhardt ich habe dir bei keybase geschrieben. 
Solche Zahlen in aller Öffentlichkeit zu präsentieren halte ich für keine gute Idee. 
Ich habe meine Zahlen hier geändert und würde dich gerne bitten die entsprechenden discord nachrichten des bots zu löschen oder zu bearbeiten in denen meine Zahlen drin stehen.

**Comment by ulfgebhardt** [comment]
Ist gelöscht
