### ISSUE TITLE
🐛 [Bug] Problem with duplicate calls and GT Server

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#841]
## 🐛 Bugreport

There was a problem reported twice of events be calculated twice for users if two calls happen simultaniously.
Is this permanently resolved?

**Comment by einhornimmond** [comment]
Yes it is.
On GDT-Server I make sure that this change will be done only once. 
I have tried locking db with lock table but that didn't work. 
Now I write a lock file to hard disk while changing and remove it once done.
