### ISSUE TITLE
🐛 [Bug] Wordpress Konto login zeigt auf altes Frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#843]
## 🐛 Bugreport

The Wordpress page [coin](https://gradido.net/de/coin/) redirects to the old frontend when clicking login.

![image](https://user-images.githubusercontent.com/1238238/133887271-8d1c8295-78c3-4d1d-be86-28710d1a292b.png)

Note: We will most likely change the URL of the new frontend to [gdd1.gradido.com](https://gdd1.gradido.com/). Therefore in the future we might need to change all the links again.

**Comment by BerndHueckstaedt** [comment]
Done!
