### ISSUE TITLE
🔧 [Refactor] Show correct language string in Profile

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#858]
## 🔧 Refactor ticket

This should say "Deutsch" and "English" accordingly.
![image](https://user-images.githubusercontent.com/1238238/133940332-c069db47-9d4b-4cdf-ba2e-8f0fa24b1bdd.png)

**Comment by Elweyn** [comment]
@ogerly, @ulfgebhardt, 
Alex and I have seen that their is a problem with this component since it sends updateUserInfos without the email.
How do we continue?
Do we make another ticket or do we fixe it in this ticket?

**Comment by ulfgebhardt** [comment]
I am for changing this call instead @Elweyn https://github.com/gradido/gradido/issues/875
