### ISSUE TITLE
🐛 [Bug] Profile Page Borders

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#859]
## 🐛 Bugreport

The corners of the gray panes can only be round on the right side. The left side cannot be rounded.
![image](https://user-images.githubusercontent.com/1238238/133940361-428e791c-ecec-43b7-941b-9f25e7762a96.png)

See #850 for a related issues

**Comment by ogerly** [comment]
in PR https://github.com/gradido/gradido/pull/887
