### ISSUE TITLE
💥 [DevOps] FINAL FRONTEND for Video

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#87]
## 💥 DevOps ticket   
- [x] sprache :: kein NULL mehr !!! 
- [x] senden :: senden von GDD 
- [x]  senden :: erscheinen in der transaktionsliste
- [x]  activity :: datum in der activity datum
- [ ]  activity :: hinzufügen der neuen form 
- [x] QR-Code scanning
- [ ] Error anzeigen, wenn Transaktion fehlschlägt
- [ ] Transaktions liste muss korrekt sein nach überweisung (update solle sofort da sein)
- [ ] Make new version 0.9.3
- [ ] Deploy to staging
__________________________________
**superman**
- [ ]  bei null transaktionen :: "Du hast noch keine Transaktionen"

**Comment by einhornimmond** [comment]
- [ ] correct user balance

**Comment by ulfgebhardt** [comment]
Made followup Issues - considering this done
