### ISSUE TITLE
🐛 [Bug] Missing Transaltion - change username

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#898]
## 🐛 Bugreport

When changing the username we get an untranslated text.

![image](https://user-images.githubusercontent.com/1238238/134713491-f9b4bc50-7f41-4151-ba15-8d2b6b28db80.png)

Why do we not detect this? Can we detect this? @Mogge

**Comment by ogerly** [comment]
this is not the username this is the name of the user
