### ISSUE TITLE
🔧 [Refactor] Improve Docker builds

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#9]
## :zap: Refactor ticket

Docker builds take a long time and certainly can be optimized (analysis required)
Furthermore docker files are partially split into two files (login_server) - utilize build stages

### Motive

Make it faster, better, simpler

**Comment by einhornimmond** [comment]
I use already build stages and I have split them to make if faster.
If I use only one dockerfile and even with target in docker-compose it builds release and debug,
although the release builds are not needed in the debug target and vice versa.

**Comment by ulfgebhardt** [comment]
lets close this for now and see if we can optimize this further at a later point
