### ISSUE TITLE
🚀 [Feature] Delete Account

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#900]
## Problem
Currently user accounts cannot be deleted, at least not which have gradido transactions.
Accounts without transaction can be deleted via console using mysql command line client. 
User especially with send coins transaction shouldn't be deleted because this will destroy parts of the blockchain. 
Some transactions cannot be validated any longer after that.
Currently user accounts simply marked disabled and cannot receive any further transactions. 
But this not ok from data protection point of view. 

## Solution
Instead simply disabling users, remove first- and lastname from table and replace the email by a random string.
So the state_user entry with public key stay, the blockchain stay valid but it isn't longer possible to find out which user that was once. 
For that of course a interface is needed. Maybe put it into the search.

## TODO
- new action for search (community-server search js)
- json request for login server for user delete (also elopage_buys)
- button in gdt server to also remove all data from a user
- community-server api call for remove user (delete without transaction, else clear names and exchange email with random string to keep database intact)
- find a way to remove user also from backups

**Comment by ulfgebhardt** [comment]
Closing in favor of #497
