### ISSUE TITLE
🐛 [Bug] Total of Transaction Calculcation not properly rounded

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#901]
## 🐛 Bugreport

Total of Transaction Calculcation not properly rounded

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/a325b3b3-b199-4783-8c46-26310808181c)

**Comment by ogerly** [comment]
![FireShot Capture 712 - Gradido Account - stage1 gradido net](https://user-images.githubusercontent.com/1324583/137330669-b9adb68e-4793-4ada-b25e-003ac250d66f.png)

die formatierung fehlt in der gddtransaction list
