### ISSUE TITLE
💥 [DevOps] Publish docker images for login & community server

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#92]
## 💥 DevOps ticket

Publish docker images for login & community server on dockerhub (github workflow)

Consider to check for some more speedup options when building on github(fresh) and locally(mostly rebuilding - maybe cache the build folder on a volume?)

**Comment by einhornimmond** [comment]
I cannot cache the build folder in volume because volumes only accessable after docker build.
I can push the building out of docker build and into container startup like the frontend do it.

**Comment by einhornimmond** [comment]
Login-Server in Release build ist uploaded:

**Comment by ulfgebhardt** [comment]
i think we have to do something about the tags, but other than that should be all good. <3
