### ISSUE TITLE
🚀 [Feature] Storing final balance of last transaction

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#922]
## Problem
In the current stage without extern node-server the manipulation protection don't work properly. 
For that and for able to cut off older transactions from blockchain sometimes, a way is needed to get a correct not-manipulated balance without scanning all transactions.

## 🚀 Feature
Store the final balance after the last last known transaction in a new transaction.
If this value will be included in the bytearray for signing and with the txhash the value can not be simply changed after without replaying whole blockchain and for that all private keys from all involved users are needed.
It is possible that in the time the transaction check for last transaction and the transaction is finally on the blockchain, another transaction could be slipped in between. Therefore the id of the last known transaction must be saved and validation code must be check also the referenced transaction and if another was in between to make sure that the value is still valid.

**Comment by Elweyn** [comment]
We store the balance in transaction!
