### ISSUE TITLE
🚀 [Feature] Handle PID in Frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#941]
## 🚀 Feature

We need to handle a PID parameter in the frontend.

- The PID is the publisher ID, a referral, from EloPage.
- This PID is transmitted via Parameter to our application: `ourapplication.com/path?pid=123`
- The PID is a number(!) of a specific length(?)

We want to:
- [X] Save the PID in our application
- [ ] Remove the parameter from URL (?)
- [X] Allow the parameter on every route and handle it properly according to our rules
- [ ] Transmit the PID with the register process
- [ ] Transmit the PID with the login process
- [X] Allow a revisit of the page without losing a previous PID (?)(cookie)
- [ ] Handle different PIDs and have priorities defined
- [ ] (Backend) Have a default pid if none present (not really this issue)

It is ok to implement only parts of the mechanic (e.g. do not save it across sessions), but tickets for the missing parts need to be made.

Minimum requirement:
- Properly handle the PID on the register process
- Allow multiple entry points to the application with a pid and have it available in register.

**Comment by Mogge** [comment]
@ulfgebhardt Is this path example `ourapplication.com/path/?pid=123` coorect? I would expect `ourapplication.com/path?pid=123`

**Comment by ulfgebhardt** [comment]
> @ulfgebhardt Is this path example `ourapplication.com/path/?pid=123` coorect? I would expect `ourapplication.com/path?pid=123`

You are right. Corrected

**Comment by Mogge** [comment]
@ulfgebhardt  The `pid` query is cought for all routes and stored in the store under s`tate.publisherId`. This part of the state is not deleted after logout, so it should be available in the same browser.

You really want to manipulate the URL after catching the `pid`?

The transmissions should be done in another PR, when the process of the `pid` is defined.

The handling of multiple `pid`s must be defined, including priorities.
