### ISSUE TITLE
🚀 Combine Stage1 with Stage2

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#97]
## :rocket: Feature
Combine stage1 with stage2 such that it is possible to switch with a config between centralized and decentralized use with hedera.

### Dev Problem
- No longer porting new features and bugfixes between stage1 and stage2.
- Simpler testing for most of functions without needing a hedera account for it.

### User (People which will host it) Problem
User can decide bythemself which version they like to use and can test gradido without hedera account for example for 
the gradido-game. 

### Implementation
Starting from stage2: 
- implement config in community-server to decide which system to use
- update login-server stage2 to able to use both systems
- decide if using old transaction task system for centralized transactions or better orient at new system from stage2
- update community-server to prevent using both systems on same dataset 
- config to enable or disable decay

**Comment by ulfgebhardt** [comment]
I really like this! This way we will have a stable API across technology choices
