### ISSUE TITLE
🔧 [Refactor] Test Decay Information in Frontend

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#975]
## 🔧 Refactor ticket
The unit test of the decay information is missing. There are calculations inside the template which must be tested.

Todos:
- [ ] Slots in Transaction lists - no if else
- [ ] test for those slots
- [ ] reduce calculations in frontend, refine gdt result in backend
- [ ] GDD/GDT/Percentage Types (slot-components)
- [ ] Test all the remaining calculations in the frontend

**Comment by ulfgebhardt** [comment]
@Mogge is this still a valid ticket?
